### ISSUE TITLE
Implement UI for displaying a list of tabs currently in a container

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot-containers#10]
When the user clicks the name of a container in the pop-up, show the list of currently open tab titles in that container, so they can quickly see which tabs will be affected by the Show/Hide/Open actions.

**NOTE**: Favicons are a stretch feature.

Screenshot updated by @groovecoder on 2016-12-29 from [updated InVision mockup](https://mozilla.invisionapp.com/share/UP9IMW6SF#/screens/208642772).

![testpilot-containers-tabs-list-mockup](https://cloud.githubusercontent.com/assets/71928/21546776/fe493530-cda6-11e6-9aa7-6b437f481d65.png)

**Comment by groovecoder** [comment]
Could be "very tricky" to reveal the list of tabs on the side of the pop-up like that. How about a forward/backward sliding type design like we have in the Blok pop-up?
