### ISSUE TITLE
Cookie Manager breaking with TypeError: ContextualIdentityService.getIdentityFromId(...)

### ISSUE THREAD

**Issue by kjozwiak** [mozilla/testpilot-containers#103]
@bakulf, because of issue #102... We're running into [bug#1319929](https://bugzilla.mozilla.org/show_bug.cgi?id=1319929) which is breaking the cookie manager. However, the STR are a little different this time around.

STR: (assuming you've already installed fx51/container test pilot)

* click on the "Containers" button
* remove the "Personal" container from the list
* click on the new tab button "+" and select "Personal" container
* load any website within the newly created container (reddit.com in this instance)
* create a new tab and visit about:preferences#privacy
* click on "remove individual cookies"

You'll notice that the cookie manager is completely broken. Visiting the browser console will yield the following error:

`TypeError: ContextualIdentityService.getIdentityFromId(...) is undefined cookies.js:88:15
	gCookiesWindow._isPrivateCookie chrome://browser/content/preferences/cookies.js:88:15
	gCookiesWindow._loadCookies chrome://browser/content/preferences/cookies.js:503:13
	gCookiesWindow._populateList chrome://browser/content/preferences/cookies.js:52:5
	gCookiesWindow.init chrome://browser/content/preferences/cookies.js:35:5
	onload chrome://browser/content/preferences/cookies.xul:1:1`

<img width="1278" alt="cookiemanagerissue" src="https://cloud.githubusercontent.com/assets/2602313/22169881/c722ee7e-df45-11e6-9661-a1416f879ddb.png">

**Comment by bakulf** [comment]
This is fixed. Now you cannot create an 'unknown' container from the plus menu.
