### ISSUE TITLE
Plus Panel (New Tab) UI Broken

### ISSUE THREAD

**Issue by kjozwiak** [mozilla/testpilot-containers#105]
@bakulf, mind taking a look? 

e4b6b6cb7fa481342339e491f4fa251d0f49d9c3 is the first bad commit
commit e4b6b6cb7fa481342339e491f4fa251d0f49d9c3
Author: baku <baku@mozilla.com>
Date:   Fri Jan 20 10:29:50 2017 +0100

    Plus panel

:040000 040000 ee5891245e1c0ff9dc2a3d59233642699e0d43cf 7ab8c2fa247d5c2ab8e430029d2e4c4b00cc7f0b M	data
:100644 100644 37c8889c96cd0d860769acf6696c18c217e08b74 6dd87d4d53a72f5521c28f28d25d8affbe9d8738 M	index.js

<img width="1306" alt="newtabpanel" src="https://cloud.githubusercontent.com/assets/2602313/22228164/5c9fb992-e19d-11e6-96b5-a6f2165351e5.png">

**Comment by bakulf** [comment]
@jonathanKingston can you take a look?

**Comment by jonathanKingston** [comment]
That looks superb... :shipit:

@kjozwiak is this Mac only, I haven't seen it look like this in a few weeks since my initial playing with the patch.

**Comment by kjozwiak** [comment]
@jonathanKingston it looks like it's happening on both Win/macOS.. It's appearing correctly under Ubuntu..

* Ubuntu 16.04.1 LTS x64 - PASSED (Working) 
* macOS 10.12.2 x64 - FAILED
* Win 10 Pro x64 - FAILED

![issue](https://cloud.githubusercontent.com/assets/2602313/22313823/99656882-e32c-11e6-8748-81fb87bfbe9f.png)


However, when you're closing tabs under Ubuntu, the mouse will quickly hover over the "+" button and will popup the submenu for a few seconds.. I've created #111
