### ISSUE TITLE
Pass a security review

### ISSUE THREAD

**Issue by wresuolc** [mozilla/testpilot-containers#108]
I need a reasonably-done .xpi file that we can send to the security team for review before we launch.

**Comment by jonathanKingston** [comment]
Which team is responsible for these reviews out of interest?

**Comment by groovecoder** [comment]
I'm pretty sure it's ours/Tanvi. 😜

**Comment by wresuolc** [comment]
I ask the AMO reviewers to look at it as well as a testpilot-security mailing list which has a few folks from the moz security team on it

**Comment by TanviHacks** [comment]
It's usually me and Dan.  So in this case, it will mostly be Dan.

**Comment by wresuolc** [comment]
We passed the security review 🎆 .  Next up is the add-on code review.  I'm waiting on the .xpi from @groovecoder  -- he promised it by the end of today. :)

**Comment by groovecoder** [comment]
Afraid that won't happen @wresuolc 😢

**Comment by wresuolc** [comment]
success 💯
