### ISSUE TITLE
Implement hide containers API functionality

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/testpilot-containers#11]
Clicking the hide and show buttons in the containers drop down menu should use a web extensions (like?) API which shows and hides all of the tabs in the cookie jar we are wanting to hide.

We may want this as part of the native patches into Firefox however for now I think it makes sense to monkey patch this into the WebExtension API for this addon to use.

**Comment by groovecoder** [comment]
So there's no existing native API for hiding all tabs for a specific container/jar?

**Comment by jonathanKingston** [comment]
I think we need a way to actually hide tabs by id something like:

```js
browser.tabs.hide([1,2,3]);
browser.tabs.show([1,2,3]);
```

We have a way internally of hiding tabs (I think we use this for prerendering and some other functionality?) and I think we should try and expose this somehow. Getting the list of per container ids can come from the other APIs proposed.

**Comment by jonathanKingston** [comment]
We would also have to decide what would happen if I hide personal container tabs then open a new personal container.

- Would it reject opening it?
- Keep only this new one open
- Show all personal containers

/cc @johngruen

**Comment by johngruen** [comment]
My hunch is that all personal container tabs should open, but i will talk to UX

**Comment by ChenMorpheus** [comment]
@johngruen @jonathanKingston 
I am thinking the same way what John suggested. Let's show all personal containers when users want to open a new personal container.

**Comment by bakulf** [comment]
I submitted a patch.

**Comment by bakulf** [comment]
This is fixed.
