### ISSUE TITLE
possibly adding a longer hover delay for the plus panel button

### ISSUE THREAD

**Issue by kjozwiak** [mozilla/testpilot-containers#111]
We should look into possibly adding a longer hover delay for the plus panel button, or look into other possible solutions if the delay isn't viable. When you're closing tabs, the mouse will quickly hover over the "+" button and will popup the submenu for a few seconds..

Example of the issue:
* https://youtu.be/PDfLZL52VAY

**Comment by jonathanKingston** [comment]
@kjozwiak this *fingers crossed* should be fixed with: https://github.com/mozilla/testpilot-containers/pull/109

**Comment by kjozwiak** [comment]
https://cloud.githubusercontent.com/assets/71928/22376710/b4848ae6-e474-11e6-982e-19ee161d7730.gif
