### ISSUE TITLE
Create tooltips throughout the Containers Test Pilot

### ISSUE THREAD

**Issue by TanviHacks** [mozilla/testpilot-containers#112]

**Comment by TanviHacks** [comment]
@kjozwiak - can you take an inventory on what has and what doesn't have tooltips?

**Comment by kjozwiak** [comment]
Current available tooltips:

* Container button under toolbar -> `Containers`
* Sort Containers button -> `Sort Containers`
* "+" button -> `Create new container`
* Pencil button under "Edit Containers" -> `Edit [container name] container`
* Trash Can button under "Edit Containers" -> `Remove [container name] container`

Possibly adding the following tooltips:

* "Edit Containers" button in the main container menu
* "< Exit Edit Mode" button
* ">" button to the right of each container
* "+" button to the left of each container (if we're keeping the +)

**Comment by TanviHacks** [comment]
Not needed for: 
"Edit Containers" button in the main container menu
"< Exit Edit Mode" button

**Comment by groovecoder** [comment]
"Edit Container" single icon (the pencil)
"Delete Container" single icon (the trash can)

**Comment by kjozwiak** [comment]
Please see the following issues for other area's that could use tooltips as reported by SV while going going through their Shield Study pass via #617:

* #609 - There is no tooltip that displayes the full container name
* #615 - There is no tooltip that displayes the full websire URL from a container

**Comment by jonathanKingston** [comment]
> "Edit Container" single icon (the pencil)
> "Delete Container" single icon (the trash can)

This looks like it was already in place just the hit target was only the image.
