### ISSUE TITLE
Data dashboard

### ISSUE THREAD

**Issue by TanviHacks** [mozilla/testpilot-containers#118]
Talk to the data team about creating a data dashboard after our metrics are done in #113 and #117

**Comment by johngruen** [comment]
@TanviHacks yep yep. @clouserw ususally files tickets for these, so I'm going to assign him.

**Comment by johngruen** [comment]
@TanviHacks so we have confirms pings coming in here, we can leave this open since there's no dashboard yet, but we have the ability to make them :)

**Comment by johngruen** [comment]
@clouserw and I will follow up with Ilana

**Comment by groovecoder** [comment]
The dashboard has started here:

https://sql.telemetry.mozilla.org/dashboard/txp-containers-executive-summary

I'm comparing its data with our questions and asking rrayborn questions in #tacostand

**Comment by ChenMorpheus** [comment]
@groovecoder 
I read through the ticket(Measurements Questions Draft #113), but there are still some variables I am not quite sure if I understand correctly in the dashboard. Is there a document describing all these variables for us to go deeper with the data?

**Comment by groovecoder** [comment]
@ChenMorpheus did you see the metrics doc here?

https://github.com/mozilla/testpilot-containers/blob/master/docs/metrics.md

**Comment by ChenMorpheus** [comment]
@groovecoder 
 That's exactly what I need. Thank you!!

**Comment by groovecoder** [comment]
@ChenMorpheus Are you planning to work on this? This is all on sql.telemetry.mozilla.org.

**Comment by ChenMorpheus** [comment]
@groovecoder 
Thanks for the information. I know the dashboard website, I just need to understand some variables of Containers to monitor if there are any unusual patterns which might help us fine tune the design.

**Comment by jonathanKingston** [comment]
@groovecoder is this done?

**Comment by groovecoder** [comment]
Done until we start to ask more questions of the data, but we can do those 1-by-1.
