### ISSUE TITLE
Change container UI when hovering over the '>' arrow

### ISSUE THREAD

**Issue by groovecoder** [mozilla/testpilot-containers#120]
When I hover over the '>' arrow, remove the '+' icon on the row and highlight the '>' somehow, so I know that clicking on the '>' is a different action than '+'.

**Comment by youwenliang** [comment]
I think the behavior was supposed to be: 

1. Clicking '+' will add selected container
2. Clicking elsewhere will go down to the next level, the same as clicking '>'
3. And the '+' icon is supposed to have hover state (grey -> blue), so we didn't put hover state for '>'

Check out the prototype here:
https://mozilla.invisionapp.com/share/WSAD2SU4H
