### ISSUE TITLE
shouldn't allow containers being opened within PB

### ISSUE THREAD

**Issue by kjozwiak** [mozilla/testpilot-containers#123]
We shouldn't be allowing containers to be opened within PB..

STR (assuming you've already installed the testing environment):

* launch PB via Hamburger Menu -> New Private Window
* click on the "Container" icon and open several default containers

You'll notice that they're being opened within the PB window which shouldn't be allowed as we block containers from being opened within PB everywhere else.. This also creates several UX/UI issues as demonstrated in the second screenshot.

<img width="1280" alt="pb" src="https://cloud.githubusercontent.com/assets/2602313/22394949/ba669f48-e4fc-11e6-92b1-e249a9ff6c17.png">

<img width="1275" alt="dropdownissue" src="https://cloud.githubusercontent.com/assets/2602313/22394973/6fd7a00c-e4fd-11e6-831e-91798a93a745.png">

**Comment by bakulf** [comment]
@TanviHacks, @johngruen Do we want to disable the popup button or we want to show a panel saying: containers are disabled on PB?

**Comment by bakulf** [comment]
I wrote a patch to disable the addon in privateBrowsing. The button is not clickable and the popup is not shown.
