### ISSUE TITLE
Audit files in XPI

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot-containers#125]
Was randomly testing the **onboarding-v2-20** branch and ran `> $(npm bin)/jpm xpi` locally and noticed the generated _testpilot-containers.xpi_ seems to be roughly 18MB.

A bit misleading since I think bundled /node_modules/ is about 15.5 MB of that (86%).
But yeah... something to re-check once we start doing official signed builds.

**Comment by bakulf** [comment]
Your XPI is 18Mb because it contains the node_modules directory.
Try to install npm modules globally, or move them out of the addon folder and the size will be ~63kb.

**Comment by groovecoder** [comment]
We could also fix this by adding [a `.jpmignore` file](https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpmignore) to exclude `node_modules/`.

**Comment by pdehaan** [comment]
Yeah, .jpmignore is :+1:. Adding this, then running `$(npm bin)/jpm xpi` reduces my XPI down to 98KB (on onboarding PR branch):

```
.git/
docs/
test/
node_modules/

.env
.eslintrc.js
.gitignore
.htmllintrc
.jpmignore
.stylelintrc
.travis.yml
testpilot-containers.xpi
```

Heck, I'll even throw that into a PR, just for giggles.

**Comment by pdehaan** [comment]
Ref: #128 (PR)
