### ISSUE TITLE
New Container Tab broken under file menu under OSX

### ISSUE THREAD

**Issue by kjozwiak** [mozilla/testpilot-containers#127]
@bakulf, it looks like commit 5fbc42a2888bb04b22201d7d7390ab85ca85e6e8 has regressed the containers access point via the file menu. 

**STR under fx51:**

* close all the currently opened windows
* while FX is still running, select File -> New Container Tab -> and select any container
* once the new window appears with the container, select File -> New Container Tab

**STR under fx52:**

* once fx is running, click "File -> New Container Tab"

Bisect results:

commit 5fbc42a2888bb04b22201d7d7390ab85ca85e6e8
Author: baku <baku@mozilla.com>
Date:   Mon Jan 23 09:34:19 2017 +0100

    File Menu updated

:100644 100644 01a4afc41d7ebe68d387ee29f9d03de889230431 52685930fea666f619fa3a30512799ae9214cc7f M	index.js

**Comment by kjozwiak** [comment]
This appears to affect the macOS platform and not the others.. I went through the following platforms when @bakulf couldn't reproduce the issue:

* macOS 10.12.2 x64 - _**FAILED (issue is reproducible)**_
* Ubuntu 16.04.1 LTS - **PASSED (issue isn't reproducible)**
* Win 10 Pro x64 - **PASSED (issue isn't reproducible)**

I'm assuming this has something to do with the menu being part of the OS under macOS, while under Ubuntu/Win, it's under the FX file menu.

**Comment by jonathanKingston** [comment]
Replicated, debugging.
