### ISSUE TITLE
Implement tab color bars to match UX spec

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot-containers#13]

**Comment by TanviHacks** [comment]
Is this issue about the tab highlighting overline/underline?

**Comment by ChenMorpheus** [comment]
@johngruen @TanviHacks 
I assumed this ticket is for the purpose Tanvi asked. Please find the attached measurement for details, and let us know if any questions, thanks.

![container-tabbar](https://cloud.githubusercontent.com/assets/18019946/21711113/f38873b8-d427-11e6-8548-9ed3783b83de.png)

**Comment by jonathanKingston** [comment]
Related bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1325902

**Comment by johngruen** [comment]
@jonathanKingston i think we're good here and can focus on that polish bug #96, but i'll wait til you get back
