### ISSUE TITLE
old/new container menu from "+" new tab button overlapping

### ISSUE THREAD

**Issue by kjozwiak** [mozilla/testpilot-containers#130]
Because we're setting ["privacy.usercontext.longPressBehavior;1"](https://github.com/mozilla/testpilot-containers/blob/86e3cb48869c8115918db7b5cd160ebee843faa5/index.js#L55), you'll run into situations where you can have two drop down menu's appear from the "+" new tab button. We should be disabling the long press and keep the "hover" functionality that's currently being used.

<img width="458" alt="twodropdowns" src="https://cloud.githubusercontent.com/assets/2602313/22481078/d3fa52d4-e7c1-11e6-85a8-5332fd5edf35.png">

STR:

* launch fx (assumes you have the test pilot installed)
* long press the "+" new tab button and the old container menu will appear
* scroll through the containers in the old menu, and the new container menu will appear as per the above screenshot

**Comment by groovecoder** [comment]
Long-press doesn't exist in 51, right? So I assume this is a 52-only bug?

**Comment by kjozwiak** [comment]
> Long-press doesn't exist in 51, right? So I assume this is a 52-only bug?

Yup, it's only affecting fx52 and not fx51.. However, it's still occurring in fx51, commented [here..](https://github.com/mozilla/testpilot-containers/pull/135#issuecomment-277355641)
