### ISSUE TITLE
adding two new colours under "choose a color"

### ISSUE THREAD

**Issue by kjozwiak** [mozilla/testpilot-containers#131]
I think we should add two more colours to make this look a little more symmetrical. Thoughts?

<img width="296" alt="00c8c2ce-e7ad-11e6-907b-ea426a88b324" src="https://cloud.githubusercontent.com/assets/2602313/22483727/74d095d8-e7cc-11e6-8f70-588b056e0dee.png">

**Comment by pdehaan** [comment]
... or at the very least, add more internal padding so it's 5x2 instead of 5+3

**Comment by jonathanKingston** [comment]
The padding is actually wrong anyway... I just threw this together to get the functionality working. The radio buttons underneath these icons are a pain to style.

**Comment by TLHuang** [comment]
Sorry for the late reply, Fang is on PTO and will be back on next Monday. From the visual perspective, the current palette is covered most of the color options, and it should be enough for the users. I don't think the symmetry will be an issue here.

**Comment by fangshih** [comment]
The original layout should be able to fit 7 colors in one line. Each circle should have 17px and with 12px padding in between. The back button on the left should be 33px. Here is the spec for the padding. 
![6-edit mode](https://cloud.githubusercontent.com/assets/4862573/22875128/fcd751f0-f204-11e6-9f49-d9c6d0c9ff6d.png)
You can also find rest of panel from this issue 
https://github.com/mozilla/testpilot-containers/issues/55

Hope it works, Thanks! :)
