### ISSUE TITLE
being able to restore individual hidden tabs

### ISSUE THREAD

**Issue by kjozwiak** [mozilla/testpilot-containers#137]
With our current implementation of restoring hidden tabs, a user would have to restore all the tabs in a particular container just to view one or two specific tabs, and then hide them all again.. This doesn't seem like good UX.

Users should be able to open hidden tabs via the following two methods:

* "show these container tabs" which loads the entire list in the appropriate container which is already implemented
* Click on a particular tab within the list to open tabs individually

Spun off from the discussion in #46.

**Comment by bakulf** [comment]
I think we need a UX feedback here because currently, the tabs are shown or hidden. Here you are introducing a 3rd state where some tabs are shown and others are not. Also the UI should be updated, I guess.

**Comment by kjozwiak** [comment]
Closing this issue... We've discussed this in our weekly container meeting, and we've decided that we're going to make this list non-clickable. I'll create a new bug to add UI that indicates that the tabs cannot be clicked when they're being hidden.
