### ISSUE TITLE
Implement select-on-hover container picker

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot-containers#14]
<img width="421" alt="screen shot 2016-12-15 at 4 20 13 pm" src="https://cloud.githubusercontent.com/assets/3323249/21242436/5c2bdff6-c2e2-11e6-89b9-3cad22300dbd.png">

Tanvi had some concerns here about spoofing this UI from web content but it seems like a very unlikely attack vector to me. ANYWAY, this UI may not be 100% final, but we should assess the feasibility first.

**Comment by groovecoder** [comment]
This will almost certainly require a bootstrap add-on; i.e., can't do this with SDK or WebExtension APIs.

**Comment by groovecoder** [comment]
In fact, we would have to use a VERY old-school overlay add-on to do this. Is it vital to test our hypothesis about the UI?

**Comment by TanviHacks** [comment]
@johngruen turns out this UI isn't really practical/possible in an addon.  We could try to uplift https://bugzilla.mozilla.org/show_bug.cgi?id=1272256 to 51, or leave it out of the test pilot experiment.

**Comment by ChenMorpheus** [comment]
@TanviHacks Based on bug1272256, it seems that we won't uplift to 51. I just want to reconfirm that technically we can still keep long press to open a new tab in Test Pilot, right?

**Comment by bakulf** [comment]
I take this bug. I'll try to implement something similar to bug 1272256 in the addon.

**Comment by bakulf** [comment]
This landed today. The UI is not exactly how we want, but jkt will work on it.
