### ISSUE TITLE
Improve empty "container tab list" panel

### ISSUE THREAD

**Issue by groovecoder** [mozilla/testpilot-containers#142]
Possibly unrelated to this specific PR (or not), but we may also want to consider a better empty state for container tabs with no tabs. Maybe set a min-height and have some option to open a new tab for the empty container:

![nightly_and_re___mozilla_testpilot-containers__hide_tabs____close_tabs___46__-_peterdehaan_gmail_com_-_gmail](https://cloud.githubusercontent.com/assets/557895/22492668/dddf1820-e7df-11e6-86fe-358683593a57.png)

... because _that_ ^^ isn't a super great user experience.

---

![menubar_and_nightly_and_for__94__for__95__more_ui_updates_by_groovecoder_ _pull_request__129_ _mozilla_testpilot-containers_and_bno_news_on_twitter___full_text__dhs_secretary_kelly_announces_thomas_homan_to_take_over_as_acting_ice_director_](https://cloud.githubusercontent.com/assets/557895/22492699/11f698b8-e7e0-11e6-9a86-e66733082ded.png)

(versus this improved UX for tab containers with 1+ open tabs)

**Comment by johngruen** [comment]
Easiest thing would be to make empty containers un-clickable...this would mean hiding the caret.
