### ISSUE TITLE
adding UI to let users know that hidden tabs are not clickable

### ISSUE THREAD

**Issue by kjozwiak** [mozilla/testpilot-containers#147]
As discussed in our weekly container meeting, we should add some type of visual indicator that lets users know that the "hidden" tabs that are being listed in a specific container are not clickable.

<img width="304" alt="hiddentabs" src="https://cloud.githubusercontent.com/assets/2602313/22603383/1d316e88-ea15-11e6-8820-397680c0961b.png">

**Comment by ChenMorpheus** [comment]
@kjozwiak Thanks for noticing. We can simply disable these listed tabs with grey out. (see image below) When users unhide this container, all listed tabs become clickable. 
![2017-02-10 2 36 07](https://cloud.githubusercontent.com/assets/18019946/22816753/bd98c464-ef9e-11e6-8b81-4ddd3b44e245.png)
