### ISSUE TITLE
visual issues with custom container tabs

### ISSUE THREAD

**Issue by kjozwiak** [mozilla/testpilot-containers#150]
There's some visual issues when creating customer containers. When I initially create a customer container, the initial tab will have the top portion of the tab missing from the tab bar. It will also overlap with the "+" new tab button.

This is the issue that @groovecoder also ran into while demoing containers. I can reproduce this pretty easily by simply opening a brand new custom container.

* the top of the tab is missing from the initial custom container tab
* the tab and the "+" new tab button are being overlapped

<img width="539" alt="customcontainer" src="https://cloud.githubusercontent.com/assets/2602313/22604249/a4203836-ea18-11e6-8c55-6d6f7a4f2d1c.png">

Platform being used: macOS 10.12.3 x64

**STR under fx51:**

* create a new custom container via the test pilot "Containers" button
* close all currently opened windows and ensure that FX is still running
* select "File -> New Container Tab -> [select the custom container created previously)

**STR under fx52:**

* create a new custom container via the test pilot "Containers" button
* simply open the new customer container and you'll see the issues in the tab bar.

**Comment by groovecoder** [comment]
Note: I never saw this until I used the Mac File menu.

**Comment by kjozwiak** [comment]
> Note: I never saw this until I used the Mac File menu.

With fx51, you'll need to use the "File Menu" to reproduce the issue.. However, with FX52, you simply open a customer container from the test pilot and you'll run into the issue. I added the STR for both versions in the original comment.
