### ISSUE TITLE
Restoring hidden containers after restart

### ISSUE THREAD

**Issue by TanviHacks** [mozilla/testpilot-containers#156]
Say a user hides their personal container and then later restarts the browser.  Can they unhide their personal container, or is it gone?  What is the current experience with the addon today, and what should the UX be?

**Comment by bakulf** [comment]
Currently, those tabs are gone because they objects kept in memory, not real tabs, and so the sessionHistory will not restore them.

**Comment by ChenMorpheus** [comment]
@bakulf 
I might still need some clarification. According to the current behavior, restarting the browser doesn't automatically restore these hidden tabs, but can users unhide these tabs to reopen them by clicking "unhide this container" in the container menu? Or the list is gone forever when user restart the browser?

**Comment by bakulf** [comment]
We have to decide what we want :) I was just describing the current implementation. We can easily change it.

Currently, when the browser restarts, the hidden tabs are forgotten. If we want to keep them after a restart we have to consider the following issues:

1. We need to add a way to remove/close an hidden tab without showing it. What about if I want to close an hidden tab? How can I do it without opening it again?

2. how do we interact with session restore? If FF crashes, at the next restart, FF shows about:sessionrestore with a list of opened tabs to restore. If the user doesn't want to restore them, what should we do with the hidden tabs? (btw, whatever we decide to do here, it can be tricky to implement)

3. what about if the user doesn't want to restore the previous tabs? I guess here we want to forget the hidden tabs as well.

**Comment by jonathanKingston** [comment]
So from looking at this, the sdk storage uses promises which means every place that we use `this._identitiesState` to use the storage might need to change to async, this changes a lot of code. Let me know if that will be how it is implemented @bakulf as it might impact other issues in merging etc.

My other idea for storage was just to store when closing windows rather than block on closing and hiding tabs etc.

**Comment by TanviHacks** [comment]
As for user behavior, this is how I think it should work:

If the user has selected about:preferences#general, "When Firefox restarts" : "Show your windows and tabs from last time", hidden container tabs should still be hidden.  If the user does not select this, then the hidden containers will disappear along with the rest of the regular and container tabs.

This means we have to store the hidden container tab URIs somewhere that doesn't disappear on restart.

In addition, if a session crashes, the browser restarts, and the user chooses to reload their previous crashed session, the hidden containers tabs should still be hidden.

@bakulf please take a look at this, along with Jonathan's previous comment and let us know if there are implementation issues with this approach.  Thanks!

**Comment by bakulf** [comment]
I just submitted a PR for this.

**Comment by grahamperrin** [comment]
> … [if you shutdown or restart your browser, hidden container tab lists are deleted.](https://github.com/kesselborn/conex/issues/26#issuecomment-333992885) …

As far as I can tell, no deletion with Multi-Account Containers 4.0.3 with Firefox 56.0 (64-bit) on FreeBSD-CURRENT: 

![2017-10-04 19 08 46](https://user-images.githubusercontent.com/192271/31193813-170cfcb0-a93d-11e7-8b82-bd1cc6bf15d7.gif)
