### ISSUE TITLE
Edit container looks broken

### ISSUE THREAD

**Issue by bakulf** [mozilla/testpilot-containers#157]
![screenshot](https://cloud.githubusercontent.com/assets/515957/22689612/095cd0d0-ed32-11e6-9afe-968d99fdce0c.png)

This is what I see locally. Fresh profile, current master.

**Comment by groovecoder** [comment]
Linux?

**Comment by jonathanKingston** [comment]
@groovecoder this happens because the CSS won't align in all OS's and dpi etc (I was expecting this)
The input overlays the other fields and the -999px doesn't work. The radio is there for accessibility.

Looks like linux yeah, however must be different dpi perhaps.
