### ISSUE TITLE
getting a signed build that works with release for testing

### ISSUE THREAD

**Issue by kjozwiak** [mozilla/testpilot-containers#159]
We need to start testing the container add-on using a released version of FX rather than relying on node/jpm which doesn't mirror the real environment that the add-on will be running under. An example of things that we need to check is session restore. Because we're running under node/jpm, every time the browser is closed/restarted, the session is restored to a clean state. This makes it difficult to test certain features.

**Comment by groovecoder** [comment]
I added @kjozwiak @bakulf and @jonathanKingston to the addon on AMO so they should all be able to see all versions of the .xpi here:

https://addons.mozilla.org/en-US/developers/addon/containers-experiment/versions

@pdehaan - what's your AMO email address? I'll add you too.

**Comment by pdehaan** [comment]
@groovecoder I don't think I've ever signed up for AMO. I usually just grab the XPIs that get posted to Test Pilot (or build them myself).

**Comment by kjozwiak** [comment]
Thanks @groovecoder, I've managed to install the XPI on the latest release without any problems. I'll start using the XPI along side the latest version via node/jpm and post any issues that I manage to find.

**Comment by kjozwiak** [comment]
I'm going to close this off so it's off our issues queue. As @groovecoder mentioned above, the XPI has been created and signed and is working with released versions of fx.
