### ISSUE TITLE
removing containers from about:addons doesn't disable containers feature

### ISSUE THREAD

**Issue by kjozwiak** [mozilla/testpilot-containers#173]
When removing containers from about:addons, it doesn't correctly disable the container feature. The following pref's are still enabled, even after several fx restarts:

```
privacy.userContext.enabled;true
privacy.usercontext.about_newtab_segregation.enabled;true
```

I'm not sure if this will differ when users install the feature via the test pilot program rather than directly using the XPI. But currently, simply removing Containers from about:addons still leaves the feature pref'd on... If this is going to be handled by the test pilot application rather than our XPI, please close this bug :)

STR:

* install the latest container XPI (used containers_experiment-0.0.2-fx.xpi)
* once installed, remove the add-on from about:addons under "Extensions"
* restart fx
* open about:config and search for "userContext"

You'll notice that the feature is still enabled even though it has been removed from about:addons.

**Comment by TanviHacks** [comment]
Jonathan or Baku - can you look at this?

**Comment by kjozwiak** [comment]
Test Cases Used:

* ensured that the following prefs have been reset to the correct values once containers have been removed
** privacy.userContext.enabled
** privacy.userContext.ui.enabled;false
** privacy.usercontext.about_newtab_segregation.enabled
* ensured that the "Containers Experiment" entry is removed under "Extensions" via about:support

* ensured that the following container access points have been removed once the container add-on has been removed
** file -> open container tab
** right click context menu -> open link in new container tab
** menu under the new tab "+" button
** container test pilot button under the toolbar
** open container tab under hamburger -> customize

Issues found:

* Cookies/Containers are not being removed when disabling the add-on #174
* menu appears if quickly hovering over new tab + button when container add-on is removed #182
* restoring container tabs after the add-on was removed #183
* "Open Container Tab" button not being removed from Customize when add-on removed #186
