### ISSUE TITLE
cookies not being removed from cookies.sqlite when removing container add-on

### ISSUE THREAD

**Issue by kjozwiak** [mozilla/testpilot-containers#174]
We're not removing container cookies when the feature is disabled or removed via:

* disabled using `privacy.userContext.enabled;true` under about:config
* removing the container XPI via about:addons (containers_experiment-0.0.2-fx.xpi)

When someone removes/disables the container feature, the cookies are still being stored within cookies.sqlite and can be re-used. If someone re-installs/re-enables the container feature, they could potentially use an already established session. I've reproduced a similar situation using facebook.com as described below:

* install fx51.0.1 or fx52.0b5 with the latest container XPI (used containers_experiment-0.0.2-fx.xpi in this instance)
* once installed, login into facebook.com using a personal container
* remove the container XPI via about:addons under "Extensions"
* disable the container feature via about:config (see #173)
* restart fx (containers should be completely removed/disabled)
* inspect cookies.sqlite and you'll notice that the cookies are all still present (used SQLite Manager)
* re-install the same container XPI
* open a personal container and visit facebook.com

You'll still be logged into the same account as before as the cookies haven't been removed from the sqlite database when the container XPI was initially removed.

CCing @TanviHacks & @bakulf. I've also created [bug#1338735](https://bugzilla.mozilla.org/show_bug.cgi?id=1338735) to get this fixed in the nightly implementation of containers.

**Comment by TanviHacks** [comment]
We should essentially "delete" all containers on uninstall, so that no cookies/localstorage/etc from those containers exist after uninstall.  On reinstall, the users will get the 4 predefined containers with no content in them.

Although, there may be limitations to what an addon can do an uninstall time.  I'm not sure.

**Comment by groovecoder** [comment]
Is this MVP? Is it bug or enhancement? (I'm doing a quick triage of these issues so when I submit an `.xpi` file today I can show AMO review team what the outstanding changes will be before launch)

**Comment by kjozwiak** [comment]
I see this as a bug rather than an enhancement. We shouldn't be leaving behind any data related to containers once the user removes the add-on. I don't think users will be happy if they realize that cookies from them testing the container feature are still being stored once they decide to remove the add-on. Definitely an MVP in my opinion.
