### ISSUE TITLE
Containers created by addons when the addon is disabled?

### ISSUE THREAD

**Issue by bakulf** [mozilla/testpilot-containers#178]
I see 2 options:

1. We restore the previous containers
2. We just remove all the containers, and reintroduce the default 4 ones?

I vote for 2 (it's easier). Of course this is an issue just for nightly users.

**Comment by ChenMorpheus** [comment]
I would prefer the first one since users might not think "disable" is equal to "erase all data." If we do go the second one, I would recommend prompting warning message when users turn off the add-on, showing something like "this will remove all relevant data, are you sure to disable the add-on?"
