### ISSUE TITLE
Open Container Tab & Arrow Down menu's using older UI

### ISSUE THREAD

**Issue by kjozwiak** [mozilla/testpilot-containers#181]
There are two container access points that are currently still following the old UI as pictured below. They're also not displaying the icons for custom containers.

We can either:
* remove these two access points when someone installs the container test pilot
* make the two menu access points use the same UI as other container access points 

**_Open Container Tab under Hamburger -> Customize:_**

<img width="183" alt="screen shot 2017-02-14 at 11 05 15 am" src="https://cloud.githubusercontent.com/assets/2602313/22937439/9ed05154-f2a6-11e6-94cd-53f9fc324a04.png">

**_Arrow down menu when there's enough tabs opened:_**

<img width="442" alt="screen shot 2017-02-14 at 11 04 48 am" src="https://cloud.githubusercontent.com/assets/2602313/22937505/c7fc4844-f2a6-11e6-831b-e9a11b728a2f.png">

**Comment by bakulf** [comment]
This bug is fixed.
