### ISSUE TITLE
Implement Containers Onboarding

### ISSUE THREAD

**Issue by TanviHacks** [mozilla/testpilot-containers#20]
https://mozilla.invisionapp.com/share/WF9INQMBM#/screens/208645244

Currently slides 3, 4, and 5.

**Comment by groovecoder** [comment]
Hmm ... where can we get the visual assets for this? I.e., these 2 graphics:

<img width="216" alt="container-intro" src="https://cloud.githubusercontent.com/assets/71928/21611787/f369b9a0-d193-11e6-866a-b52deb4afb04.png">

<img width="206" alt="container-sort" src="https://cloud.githubusercontent.com/assets/71928/21611794/f9e0c97c-d193-11e6-9489-819a20c15b3e.png">


@fangshih @johngruen - do you know?

**Comment by johngruen** [comment]
@groovecoder I don't think i have access to that Dropbox folder. This one's on Fang! I'll make sure she gets the message.

**Comment by fangshih** [comment]
Hey @groovecoder We are still working on the wording for this part, so these two visual assets may change later on. But here are the temporary one for now. Thank you!! 
[tour-assets.zip](https://github.com/mozilla/testpilot-containers/files/683868/tour-assets.zip)

**Comment by TanviHacks** [comment]
There are some panel height issues.

**Comment by fangshih** [comment]
![onboarding](https://cloud.githubusercontent.com/assets/4862573/22243223/56430378-e261-11e6-9d0b-d1cca51be89b.png)


Updated the tour assets with the new copy. 
[tour-assets-v2.zip](https://github.com/mozilla/testpilot-containers/files/726301/tour-assets-v2.zip)

**Comment by jonathanKingston** [comment]
Those intro assets look stunning! 😍
