### ISSUE TITLE
Change container tabs list from secondary pop-up to inline

### ISSUE THREAD

**Issue by groovecoder** [mozilla/testpilot-containers#22]
We're unable to spawn secondary pop-ups in WebExtensions like this:
<img width="532" alt="addon-secondary-popup" src="https://cloud.githubusercontent.com/assets/71928/21437908/19090dba-c84c-11e6-9892-e143a9d7823e.png">

Instead, we need to do inline content in the same pop-up. Like the History section of the settings menu:
![settings-popup-history](https://cloud.githubusercontent.com/assets/71928/21437968/6eca7eb4-c84c-11e6-8f12-9b10a29cd20b.gif)

**Comment by ChenMorpheus** [comment]
@groovecoder 
We'd updated the spec to have inline content. You can find more details in InVision:
https://mozilla.invisionapp.com/share/YQ9V2WYRZ
Please let us know if any questions, thanks.
![2017-01-06 3 42 00](https://cloud.githubusercontent.com/assets/18019946/21710925/c672da4a-d426-11e6-87d3-9892e93f5161.png)
![2017-01-06 3 41 40](https://cloud.githubusercontent.com/assets/18019946/21710926/c6737f2c-d426-11e6-9ce1-23542ef5d79e.png)
