### ISSUE TITLE
original icons seem like they're overlapping older assets when initially creating container tabs

### ISSUE THREAD

**Issue by kjozwiak** [mozilla/testpilot-containers#237]
When you initially open a container using one of the four default containers (Personal, Work, Shopping, Finance), the awesome bar icon will look like it's overlapping another icon. If you switch tabs and then return to the container tab, the awesome bar will show the correct icon.

**Example of issues under macOS:** (https://youtu.be/usB0dWxsDLo)

<img width="155" alt="screen shot 2017-02-21 at 4 05 41 pm" src="https://cloud.githubusercontent.com/assets/2602313/23190934/df6764a6-f84f-11e6-87a0-9804dd3eae09.png">

<img width="176" alt="screen shot 2017-02-21 at 4 05 58 pm" src="https://cloud.githubusercontent.com/assets/2602313/23190935/e2b00b18-f84f-11e6-9554-2ebe0993f62b.png">

<img width="148" alt="screen shot 2017-02-21 at 4 06 08 pm" src="https://cloud.githubusercontent.com/assets/2602313/23190936/e51bdfda-f84f-11e6-97e0-a0d0c747619e.png">

<img width="174" alt="screen shot 2017-02-21 at 4 08 17 pm" src="https://cloud.githubusercontent.com/assets/2602313/23190964/faede59c-f84f-11e6-9b9c-41081d077b17.png">

STR:

* install the latest XPI (containers_experiment-0.9.2-fx.xpi) under FX51.0.1 (327e081221b0)
* open a personal container via the Container button under the toolbar
* you'll notice that the personal icon that's being displayed under the awesome bar is incorrect
* switch to another tab and then return to the personal tab, you'll notice that the correct icon is now being displayed under the awesome bar

This issue occurs on all four of the default containers that come "pre-installed" (Personal, Work, Shopping, Finance).

**Comment by johngruen** [comment]
@kjozwiak i think this is a caching issue

**Comment by TanviHacks** [comment]
@johngruen can we make this stretch?  this is only if they change the icon.

**Comment by johngruen** [comment]
This is stretch.

**Comment by johngruen** [comment]
@kjozwiak at this point MVP is anything critical and launch blocking.

**Comment by jonathanKingston** [comment]
I couldn't replicate on Ubuntu however I think we can fix post release. It wasn't that obvious when we were looking at it. I don't actually think it is caching as it looks like the older icon is layered underneath and those styles haven't been removed etc.

**Comment by kjozwiak** [comment]
> @johngruen can we make this stretch? this is only if they change the icon.

This happens with a stock XPI without changing any of the icons and simply opening "Personal, Baking, Finance, Work" will reproduce this problem.

If we comfortable with users seeing incorrectly rendered awesome bar icons as soon as they open a "Personal, Baking, Finance, Work" container, then we can make this a stretch.

**Comment by jonathanKingston** [comment]
I lied, I can replicate in 51 but not in 52

**Comment by johngruen** [comment]
@kjozwiak i still think this is stretch. Doesn't mean it's not important, but we are more-or-less out of time before launch tomorrow. That having been said we should fix this asap.

Can you confirm this is an issue on a clean profile? The Personal Icon currently in master is the fingerprint so I'm not sure why you'd see the silhouetted person except b/c of some icon caching

**Comment by TanviHacks** [comment]
So personal should get fixed with the icon change back to fingerprint.  We shoudl confirm.  Work and shopping don't look bad.  Finance doesn't look great, but we can deal with it for a day or two.

**Comment by kjozwiak** [comment]
> Can you confirm this is an issue on a clean profile? The Personal Icon currently in master is the fingerprint so I'm not sure why you'd see the silhouetted person except b/c of some icon caching

@johngruen I was using the latest XPI (containers_experiment-0.9.2-fx.xpi) which probably didn't have all the latest changes. However, using the latest pull, before @jonathanKingston's fix above, Banking, Finance and Work were still affected.
