### ISSUE TITLE
Probably need a length limitation for custom container names

### ISSUE THREAD

**Issue by youwenliang** [mozilla/testpilot-containers#240]
If a user typed a very very long name for a custom container, this happens:
<img width="1440" alt="screen shot 2017-02-22 at 4 39 31 pm" src="https://cloud.githubusercontent.com/assets/8919308/23203541/e72902a2-f91d-11e6-8ebd-6d5436009140.png">

It breaks the awesome bar, and also the container doorhanger becomes horizontally scrollable.

**Comment by johngruen** [comment]
Haha, good catch...32 chars?

**Comment by jonathanKingston** [comment]
Text overflow... perhaps we should limit in code also though.
