### ISSUE TITLE
If Containers add-on is disabled, all the opened container tabs are also closed (Windows)

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot-containers#243]
[Notes]:
- In my opinion this could affect the user experience because the users loses the opened tabs and maybe also important data.	
- If we want to keep this beahvior maybe a warning should be displayed when the users disables the add-on.

[Affected versions]:
- Firefox 51.0.1	
- Containers 0.9.3

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have Containers add-on installed on the created profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites.
2. Open at least two website in a new container (eg. Personal).
3. Go to "about:addons" page and disable Containers add-on.
4. Observe the crated container tabs.

[Expected result]:
- Containers add-on is successfully disabled and the tabs are unaffected. 

[Actual result]:
- Containers add-on is successfully disabled, but also the opened containers tab are closed.

[Additional Notes]:
- On Mac Os the container tabs are not closed, but the colored line is now displayed on the top of the tabs. 
- Here is a screen recording with the issue: https://goo.gl/711LJy

**Comment by groovecoder** [comment]
This works as intended - when users disable the experiment, we want to remove all traces of their container usage.

But yes - we should show them a warning message.

**Comment by TanviHacks** [comment]
In the uninstall callback, prompt the user to let them know that all container data will be deleted with the uninstall.

**Comment by TanviHacks** [comment]
Fast followup

**Comment by groovecoder** [comment]
See https://github.com/mozilla/testpilot-containers/commit/b9cc9ad7dc1d47f9c9e9886764fc9d1fe2e3b666 ... there's not a way to do this. 😢
