### ISSUE TITLE
After Container tabs are moved to a new window, a link is wrongly opened in two new tabs when using Ctrl+Click or Middle Click shortcuts

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/testpilot-containers#244]
[Affected versions]:
- Firefox 51.0.1
- Containers 0.9.3

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Containers add-on is installed on a new clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to https://en.wikipedia.org/wiki/Main_Page and open a few links in container tabs. (eg. Personal)
3. Click the "Containers" button from the browser toolbar.
4. Click the arrow next to the previously used container and choose to "Move tabs to a new window".
5. From one of the newly opened window, Ctrl/Cmd+Click or Middle Click a link.
6. Observe the behavior.

[Expected results]:
- A new container tab is opened with that link.

[Actual results]:
- The link is opened in two new container tabs.

[Additional Notes]:
- Here is a screen recording with the issue https://goo.gl/b1I0R6.

**Comment by johngruen** [comment]
Cannot repro this on nightly.

**Comment by SoftVision-CiprianMuresan** [comment]
User Agent  Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:54.0) Gecko/20100101 Firefox/54.0
Build ID  20170222030329

Odd, I can reproduce on the latest Nightly as well. The move to a new window must be done from the Containers toolbar button. (see Steps 3 through 5)

**Comment by TanviHacks** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1325014

**Comment by bakulf** [comment]
I can reproduce it and I think it seems a bug in platform. I'm debugging it.

**Comment by bakulf** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1342001

**Comment by bakulf** [comment]
This is definitely a platform bug connected with multi-e10s.

**Comment by groovecoder** [comment]
WONTFIX in add-on.
