### ISSUE TITLE
Hide current active tab in container

### ISSUE THREAD

**Issue by groovecoder** [mozilla/testpilot-containers#25]
Need Tanvi and/or @johngruen to decide if this is the desired behavior:

When a user hides a container, be sure to hide the current active tab if it's in the container, so they fully and completely hide that container.

**Comment by groovecoder** [comment]
Removing the bug label, because the implementation in https://github.com/mozilla/testpilot-containers/pull/27 does this.

@johngruen and/or @TanviHacks - if either of you decide we *want* to keep the current active tab open when the user closes its container, just file a new issue to that effect.

**Comment by TanviHacks** [comment]
I think we need to close the current active tab if it is the container type that the user chooses to Hide.  So, if user is viewing a Personal tab, and clicks Hide on Personal, the current Personal tab that is in view should get hidden.  We can ask John to confirm in tomorrows meeting.
