### ISSUE TITLE
The Container icon is no longer displayed on the browser toolbar when it's re-enabled if Tab Center is also installed

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot-containers#258]
[Affected versions]:
- Firefox 51.0.1	
- Containers 0.9.3

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have Tab Center and Containers add-ons installed through Test Pilot on a new clean profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites.
2. Go to "about:addons" page and disable Containers add-on.
3. Re-enable Container add-on and observe the icon from browser toolbar.

[Expected result]:
- The Container icon is correctly re-displayed on browser toolbar.

[Actual result]:
- The Container icon is no longer displayed on the browser toolbar.

[Notes]:
- If the browser is restarted the Container icon will be correctly displayed on the browser toolbar. 
- Also, if Tab Center is disabled/removed, the issue is no longer reproducible.
- Here is a screen recording with the issue: 

![containers icon](https://cloud.githubusercontent.com/assets/19226534/23261605/af7042e0-f9df-11e6-8f5d-ebedfdf6a43e.gif)

**Comment by groovecoder** [comment]
This was fixed in 0a58786

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and is no longer reproducible with the latest Containers (1.0.1) build. The Container icon is correctly displayed on browser toolbar.
