### ISSUE TITLE
First log in attempt fails when opening a specific Fecebook link in a new container tab

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot-containers#263]
[Affected versions]:
- Firefox 51.0.1	
- Containers 0.9.3

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have Containers add-ons installed through Test Pilot on a new clean profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites.
2. Open a new container tab and navigate to a private Facebook profile (eg: https://goo.gl/aB2NmS).
3. Try to log in and observe the page behavior.

[Expected result]:
- You are successfully logged to Facebook and page content is displayed.

[Actual result]:
- Log in fails and "Cookies Required" error appears.

[Notes]:
- At second attempt you are successfully logged to Facebook.
- The issue is also reproducible for Facebook public pages if you try to log in from the top blue Facebook bar (here is a screen recording: https://goo.gl/x4arYf).
- Here is a screen recording with the issue: https://goo.gl/5gycxk.

**Comment by johngruen** [comment]
@SoftVision-CosminMuntean hey, so we think this might have been something specific to your setup, but we'll test and figure out what to do

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue on 3 different machines (Windows 7, Windows 10 and Mac OS 10.12) using a new clean Firefox profile and the issue is reproducible.

If the Facebook profile provided in step 2 is opened in a new container tab and try to log in from the top blue Facebook bar, log in fails and the "Cookies Required" error is displayed.

**Comment by kjozwiak** [comment]
@SoftVision-CosminMuntean, I can't seem to reproduce this issue on my end.. I managed to successfully login into several different public FB pages, including the ones you mentioned above without any issues which you can see happening [here](https://youtu.be/ImhIysSbIvk). I tried to reproduce the problem with the following platforms:

* macOS 10.12.3 x64 --> logged in without issues
* Ubuntu 16.04.2 LTS x64 --> logged in without issues
* Windows 10 Pro x64 --> logged in without issues

@SoftVision-CosminMuntean, are you running any software on the machine that might be interfering with cookies? If you close the cookie policy that you get from FB before you login, do you still get the same error message? Does this issue occur when you're logging into FB via their main login portal?

Perhaps it has something to do with being in Europe and their cookie laws? @jonathanKingston, mind trying this on your end and see if you get similar results?

**Comment by kjozwiak** [comment]
@jonathanKingston, Bah, I forgot you're travelling!

**Comment by SoftVision-CosminMuntean** [comment]
I have manually configured my connection settings in the browser using a US proxy (from about:preferences#advanced).  I have created a new Facebook test account and I have retested the issue, but is not reproducible. 
This leads me to believe that indeed this has something to do with European cookies.

**Comment by kjozwiak** [comment]
Thanks @SoftVision-CosminMuntean! I'll see if I can debug this later and see why containers are behaving differently.

**Comment by kjozwiak** [comment]
This issue is actually affecting FX as a whole and not just containers. I've managed to reproduce this using `fx52, fx53, fx54 and fx55` without any containers using the STR that @SoftVision-CosminMuntean added above. As discussed during our weekly triage meeting, I've created a [WebCompat](https://webcompat.com/issues/5528) issue.

As this is happening without even using containers and on channels with containers disabled, I'm going to move this issue into Stretch pending @bakulf's results.

Adding @bakulf as as an assignee as discussed during our triage meeting last week.

**Comment by kjozwiak** [comment]
@adamopenweb from the WebCompat team managed to [reproduce the issue](https://github.com/webcompat/web-bugs/issues/5528#issuecomment-293037365) and has marked it as `status-needsdiagnosis`.

I'm going to move this into stretch until we know more. Either way, I doubt this is a contianer problem as it affects FX in general.

**Comment by adamopenweb** [comment]
>Either way, I doubt this is a container problem as it affects FX in general.

@kjozwiak makes sense as I tested on a fresh profile.

**Comment by jonathanKingston** [comment]
Closing this as @kjozwiak raised https://github.com/webcompat/web-bugs/issues/5528#issuecomment-293037365 it doesn't seem to be related to containers.
