### ISSUE TITLE
[Enhancement] Containers onboarding tour should be displayed after enabling it, not after clicking the toolbar button

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot-containers#266]
[Affected versions]:
- Firefox 51.0.1	
- Containers 0.9.3

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "testpilot.env" string pref was manually added with "dev" value on a new clean profile in "about:config" page.
- Test Pilot add-on was previously installed from "testpilot.dev.mozaws.net" on the profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to testpilot.dev.mozaws.net.
2. Click the Containers experiment card and enabled it.
3. Observe the browser behavior.

[Expected result]:
- The Containers onboarding tour is automatically displayed in the top right corner of the page.

[Actual result]:
- The Containers onboarding tour is displayed only after clicking the Containers button from browser toolbar.

**Comment by johngruen** [comment]
We'd need to pass an event from test pilot to signal that the user is done with our onboarding.

**Comment by jonathanKingston** [comment]
From speaking with @johngruen I'm pretty sure that we don't want to do this as he mentioned other addons do this and he wasn't expecting it.

I guess we could use a content script to message pass from test pilot. In web extensions I don't think there is a way to open that at the moment yet anyway.

Feel free to reopen if this is not the case.
