### ISSUE TITLE
Links opened in containers are not differentiated from normal links in "List all tabs" drop-down list

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/testpilot-containers#268]
**[Affected versions]:**
-Firefox 51.0.1 and up
-Containers Experiment 0.9.3

**[Affected Platforms]:**
-All Windows
-All Mac
-All Linux

**[Prerequisites]:**
-Containers Experiment (v0.9.3) is installed on a Firefox new profile.
-Open multiple tabs with websites (container tabs and normal tabs) so that the "List all tabs" button is displayed near the "New Tab" button.

**[Steps to reproduce]:**
1. Open Firefox with the profile from prerequisites.
2. Click on "List all tabs" button.
3. Observe the items that are opened in containers.

**[Expected result]:**
- The links that are opened in containers are marked with the container color.

**[Actual result]:**
- All links look the same. There is no difference between the one from containers and the ones opened in normal tabs.

![container vs normal](https://cloud.githubusercontent.com/assets/9248513/23309301/d52fce38-fab6-11e6-99fb-f78bbce4ae05.jpg)

**Comment by johngruen** [comment]
WONTFIXING since all this does is take you to the tab
