### ISSUE TITLE
Add question to survey about incompatible experiments

### ISSUE THREAD

**Issue by groovecoder** [mozilla/testpilot-containers#271]
When a user answers the survey about Containers experiment, ask them if they encountered the incompatibility message and what they did about it. (I.e., disabled incompatible add-ons?)

**Comment by groovecoder** [comment]
@johngruen - can you write a survey question for this?

**Comment by johngruen** [comment]
yep

**Comment by groovecoder** [comment]
So this question seems to be:

### Did you run Containers with an incompatible add-on? What did you do when you saw the incompatibility message?
* I disabled the incompatible add-ons
* I disabled Containers
* I used both add-ons together

**Comment by johngruen** [comment]
This is not a good survey question, gonna ask about it as a general Test Pilot matter in our ongoing user research.
