### ISSUE TITLE
Move to new window survey question

### ISSUE THREAD

**Issue by TanviHacks** [mozilla/testpilot-containers#274]
Since the move to new window is going to be disabled sometimes, our metrics on it might be a little skewed.  So add a survey question about this.

**Comment by TanviHacks** [comment]
This can be Sprint 1 if MVP isn't going to happen.

**Comment by groovecoder** [comment]
### Did you move Container tabs to a new window?
* Yes
* No
* The Move feature was incompatible with my other Experiments

**Comment by johngruen** [comment]
Done
