### ISSUE TITLE
container menu's not initially refreshing when removing/adding containers

### ISSUE THREAD

**Issue by kjozwiak** [mozilla/testpilot-containers#295]
When removing or adding a container via the "Container" button, the list won't initially refresh until you close/re-open it. When removing a container, it will still appear in the list until the menu is closed/re-opened. Same thing applies to creating containers.

**I know it's last minute, but I think this is an MVP due to the following two reasons:**

* _users will initially think that the "+" doesn't work when they don't see their containers being listed_
* _when removing a container, you can still create a new tab with it until it's removed from the list.. this could lead to more serious issues down the road_
* _changes are not correctly being added into other access points such as the file menu, New Tab "+" button and the right click context menu.. Users will need to restart FX to see these changes appear in those menu's_

> Container Button not being refreshed: https://youtu.be/wV0knsysLDI
> Other access points not being refreshed: https://youtu.be/z2Fbl0QeA9I

STR (removing containers):

* install containers_experiment-1.0.3-fx.xpi under fx51.0.1
* open the container menu via the "Containers" button under the toolbar
* select "Edit Containers" and remove the personal container

You'll notice that the personal container is still being listed even though it as been removed. Once you close/re-open the container menu, the list will refresh and the personal container will be removed.

STR (adding containers):

* install containers_experiment-1.0.3-fx.xpi under fx51.0.1
* open the container menu via the "Containers" button under the toolbar
* select the "+" button and create a new container

You'll notice that the new container isn't being listed under the menu. Once you close/re-open the container menu, the list will refresh and the new container will correctly appear.

**Comment by kjozwiak** [comment]
This is also affecting File Menu's, New Tab "+" button and the right click context menu. With those specific access points, FX needs to be restarted for all these changes to propagate into the menus.

Example:

* remove/add a new container via the "Containers" button under the toolbar
* you'll notice that the above access points will not be updated
* restart fx and you'll see the new changes in the menu's

**Comment by johngruen** [comment]
@groovecoder @bakulf we've got to launch some time. I'd consider this a blocker, could we get this addressed first thing in the morning. Test Pilot launch is provisionally scheduled for 12PM PST

**Comment by Softvision-VladBacia** [comment]
Verified the fix on latest Dev Edition and the issue is no longer reproducible with Containers Experiment 1.0.4 .
