### ISSUE TITLE
File Menu -> New Container Tab

### ISSUE THREAD

**Issue by TanviHacks** [mozilla/testpilot-containers#30]
When you turn on usercontextid in about:config, the File menu gets a new entry for:
"New Container Tab"

1) Do we want that in the addon?
2) If we don't want this in the addon, is there a way for the addon to remove that File menu item?
3) If we do want this in the addon & we don't call this experiment "Containers", can we rename "Container" to something else via the addon?

This one will take product and engineering to answer.

@johngruen @groovecoder @jonathanKingston @bakulf

**Comment by groovecoder** [comment]
@jonathanKingston is pushing limits of what the add-on can do. I would say if that file menu item is controlled by a pref, the add-on can set prefs easily. Likewise, if the name 'Containers' is hard-coded into the code-base in Firefox, the add-on can't change it to something else.

**Comment by TanviHacks** [comment]
Its not currently controlled by its own pref.  It is controlled by privacy.userContext.enabled, which has to be turned on to get containers in general to work.

**Comment by jonathanKingston** [comment]
I really don't think we can do this without breaking lots of things. The only super crazy alternative... is to make the spaces code not use containers at all and do what @bakulf's addon does that uses AppID however I don't really know the implications of that other than the tabs won't be stylable in the same manner.

@groovecoder / @bakulf can SDK addons change translation strings, perhaps that is the other avenue?

**Comment by bakulf** [comment]
Changing the label  value of XUL elements is quite simple from an addon. For instance, from a chrome code, running as JSM, we can easily do:

`document.getElementById("alltabs_containersTab").label.replace(/Container/ig, "Space")`
