### ISSUE TITLE
removing cookies from default containers when disabling/removing experiment

### ISSUE THREAD

**Issue by kjozwiak** [mozilla/testpilot-containers#300]
Disabling/Removing the Container feature won't remove the cookies that are associated with the default containers. As per our IRC conversation, we should do the following:

* if the user already had containers enabled, we don't remove the cookies from the default containers
* if the user didn't have the container feature enabled before they installed the experiment, we'll clear all the cookies that are associated with containers

As per IRC, we should fix this ASAP but I don't think we need to block release. If someone does finds this bug, we could get headlines like "Containers doesn't really secure you and leaves behind cookies" etc.. We could get some bad press, especially as this is aimed as being a privacy/security experiment. But I might just be paranoid!

STR/Example: https://youtu.be/_1JXYWG0EKw

**Comment by groovecoder** [comment]
@bakulf - I think https://github.com/bakulf/testpilot-containers/commit/50b58f649f512011386888e738ee91dbb066c765 fixed this issue?
