### ISSUE TITLE
Containers configuration is empty

### ISSUE THREAD

**Issue by crabel** [mozilla/testpilot-containers#302]
The container configuration window does only open a bit, it loks empty. See screenshot:
https://pageshot.net/oZchcqGAQ5wzhlER/file

How can I find out, what's causing the issue? I really would like to create my own categories. :-) Is there a debug mode?

I have several addons installed, that might interfere with the addon e.g. Noscript, ublock, Cookie Monster. Javascript console shows no errors on click.

**Comment by SoftVision-CiprianMuresan** [comment]
@crabel, thanks for the feedback. I have also ran into this problem, but only on older Nightly builds (eg. 2016-10-02).
Could you please post your Firefox version, Containers version and the OS you are on?

**Comment by crabel** [comment]
Firefox: 52.0b9 (64-Bit)
Containers: 1.0.4
Ubuntu 16.10

**Comment by groovecoder** [comment]
You may also need to check the [Browser Toolbox](https://developer.mozilla.org/docs/Tools/Browser_Toolbox) JS console. That's where add-on code errors are shown.

**Comment by crabel** [comment]
Thanks for the hint, I have enabled the Toolbox and I see the following error on click:
Error: Failed to retrieve the identities. We cannot continue.  popup.js:47:13

**Comment by groovecoder** [comment]
That suggests [`refreshIdentities`](https://github.com/mozilla/testpilot-containers/blob/3fb697640118ffcf30e79948ba05a6081a037e69/webextension/js/popup.js#L51) is failing. I suspect noscript is blocking the `browser.runtime.sendMessage` call?

Does disabling NoScript fix it?

**Comment by crabel** [comment]
No, but I think I found it.

I tried to disable addon after addon and it still didn't help. But after removing Cookie Monster, I realized that I cannot login anymore anywhere. I found, setting cookies was disabled in general.

I am not sure if it was disabled by that plugin or if I have disabled it by hand at some point in the past and cookie monster just overruled it "on demand".

Maybe you could check if cookies/localstorage are "disabled" and give some kind of meaningful message/hint? Most likely this will affect only users who use such a plugin or set this manually, so they should now what to do about it.

**Comment by groovecoder** [comment]
Thanks for digging into it!

**Comment by AdKiller** [comment]
I seem to have the same issue, but I have cookies enabled cookies and local storage. Also, disabled all addons and the problem persists-- that is the popup menu opens a little bit but it is empty.

Firefox 52.7.3 ESR 64 bit
OS Win 10 Pro 1709
