### ISSUE TITLE
Allow classifying of sites or urls as private,work, ...

### ISSUE THREAD

**Issue by crabel** [mozilla/testpilot-containers#306]
Some urls/sites are always "private", some are always "work". At least for me. So, it would be nice, if those urls would be opened automatically as "private" or "work" when I type them or select them from bookmarks.

Currently I have to choose the type of a tab, before I open it. Otherwise it is opened in a "standard" tab.

But I really would like to be able to simply type the url or choose it from my bookmarks and the correct (previously "mapped") tag is used automatically.

Note:  This feature shouldn't extend to links I click, only to bookmarks and links I type.
Note2: If I select the type "private" manually, it should also not override my manual setting.

**Comment by groovecoder** [comment]
We anticipate this enhancement may get a lot of up-votes. :)

**Comment by chris-morgan** [comment]
> Note: This feature shouldn't extend to links I click, only to bookmarks and links I type.

By “links I click” I presume you mean from inside the browser. Links from *outside* the browser should open in the classified container as though I had typed them.

**Comment by cpeterso** [comment]
Once the extension has the capability to remember containers for sites, it would be interesting to include a default classification list for popular sites. So out of the box, facebook.com might automatically be assigned to the Personal container and amazon.com to the Shopping container without any user configuration.

**Comment by crabel** [comment]
@chris-morgan Yes, I meant: "Links I click in a tab". Links from outside should be treaded the same as bookmarks or links I enter in a new tab. I also don't think a container should change. When I open a "private" container and type a "work" url, it should stay "private". (Note: I am not a 100% attached to this behavior, but I think it is the most clear/logic/intuitive)

The main question for me is, will people understand that. I mean, you are in the shopping container and click some link "Login with Facebook" or something. And then they complain, because they are already authenticated (of course, in the other container). But that's a question that affects the whole idea of containers. I think, the idea of separation needs to be communicated very clearly, e.g. with a nice image showing that each container is "its own world".

**Comment by jonathanKingston** [comment]
If we implement this only for URL bar and bookmarks I think we could drop the default on link clicks within containers perhaps.

We could also consider cookies in other containers to provide the user with options on link press too. So if the user has clicked a link within work mail to github we could look at cookies and offer a modal to allow them to approve jumping into a work or personal container. That way we keep the security/privacy benefits of containers whilst offering the most contextual UX.

**Comment by kyleloyka** [comment]
Could this idea be expanded so that by default, there could be a separate container for every (visited) root domain?

**Comment by groovecoder** [comment]
@kyleloyka - that's essentially [First Party Isolation](https://www.torproject.org/projects/torbrowser/design/#identifier-linkability) as done by Tor. It's [being uplifted to Firefox](https://wiki.mozilla.org/Security/FirstPartyIsolation).

**Comment by Shnoulle** [comment]
> would be interesting to include a default classification list for popular sites.

No default classification : who made decisioon about popular site ? Why i can't use facebook as professionnal only, (and currently need facebook as facebook container, like twitter as twitter container)

**Comment by klint** [comment]
I totally support this request. Either with simple URL-matching rules or regex-based for those who dare :)
Thanks

**Comment by ChenMorpheus** [comment]
That's a great feature we're missing right now!! I'd tried to come up with some mockups which might combine different requests on Github, but I still want to know more about the feasibility before digging deeper. 

Based on @crabel 's request here, I was wondering what flexibility we have for awesome bar and bookmark since I remembered that we could not effect awesome bar or Firefox library?  Please noted that the attached screen is my rough ideas for quick feasibility check and also try to provide more inspirations, thanks.

![awesome bar](https://cloud.githubusercontent.com/assets/18019946/24535461/cffdddb8-1606-11e7-8214-93ef41c362c9.png)
![awesome bar copy](https://cloud.githubusercontent.com/assets/18019946/24535463/d2d5850e-1606-11e7-99ca-8c9cc6ec7403.png)

**Comment by groovecoder** [comment]
WebExtensions are growing a tiny omnibox suggestion feature:

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/omnibox/SuggestResult

But ...

1. Add-on omnibox suggestions are only shown when the user enter's the omnibox keyword, and we only get 1 keyword. So it would have to be something like "contain facebook.com"
2. The `SuggestResult` description is plain text, so we can't style the suggestion. We would only be able to do something like "Open facebook.com in your Personal container".

The other UI mock-ups shown here go well beyond WebExtensions, or even SDK add-on abilities. So we may not want to even try them? 😐

**Comment by Morikko** [comment]
> Allow classifying of sites or urls as private,work, 

If the sites part is done, the urls is not fully supported.

My use case would be to set `https://github.com/my-company` to `Work` container and all other Github URLs to no container for example.

Also suggested here by someone else: https://discourse.mozilla.org/t/suggestion-define-container-assignemnts-for-url-patterns/14104/2

> Absolutely love this extension as it helps me at work, by separating SSO identities from each other. Though I’d love it even more if it allowed to fine-tune the url it assignes to a container.

> Some websites have areas accessible only by certain identities - for me it’s StackOverflow for teams, where a team area is defined by a prefix in url path section. If the extension allowed me to manually set the url pattern to assign to a container, I would be able to open team area in needed container using my corporate account, while the public area using my personal account
