### ISSUE TITLE
How is "Move Tabs to New Window" supposed to work?

### ISSUE THREAD

**Issue by TanviHacks** [mozilla/testpilot-containers#31]
Can the addon move the tabs in their current state?  Or does it have to close and reopen them (losing unsaved data and history?)  If the latter, is it even worth testing/experimenting with?  That seems like it will break a lot of things for users.

For example, if I'm paying bills and I click on "Move Tabs to New Windows" for my banking container, closing and reopening those pages will likely cause me to be logged out of all my banks.  Instead of being happy with the convenience of having all my banks lined up in one window, i'll be suffering through relogging into each of them.

**Comment by bakulf** [comment]
This is possible without reloading the content. gBrowser exposes a (non-documented) method called "swapBrowsersAndCloseOther". What we have to do is:

1. create a new window A,
2. for each container tab for any existing window B, open a tab in the window A and then do:
3. windowB.gBrowser.swapBrowsersAndCloseOther(containerTab, windowA.gBrowser.theNewTab);
