### ISSUE TITLE
Create a UI that displays cookies, localstorage, etc. for each container

### ISSUE THREAD

**Issue by mrdokenny** [mozilla/testpilot-containers#312]
This UI should make it easy to delete google.com cookies from Personal but not Work for example.

**Comment by kjozwiak** [comment]
@mrdokenny thanks for the feedback/feature request. However, I'm going to close this off as it's going to be very difficult to actually implement into the test pilot and I doubt we'll have time to finish everything before the experiment is eventually retired. We actually already have [Bug#1199470](https://bugzilla.mozilla.org/show_bug.cgi?id=1199470) which discusses giving users the ability to remove the history/cookies of particular containers.

I would recommend adding your feedback into that bug as it will show developers that users are actually interested in having that type of control.
