### ISSUE TITLE
How does Unhide behave?

### ISSUE THREAD

**Issue by TanviHacks** [mozilla/testpilot-containers#32]
Do all closed/hidden tabs get open at:
* the end of the current window
* in a new window

**Comment by groovecoder** [comment]
Currently, unhide opens the tabs at the end of the current window.

**Comment by TanviHacks** [comment]
@johngruen - How should it behave?

**Comment by TanviHacks** [comment]
John says end of current window is fine.

**Comment by johngruen** [comment]
I do say that
