### ISSUE TITLE
Automatically open a hostname in the previously selected container (rather than Default)

### ISSUE THREAD

**Issue by option-greek** [mozilla/testpilot-containers#322]
Automatically open a hostname in the previously selected container (rather than Default). This can be provided as an option. Advantage is that user doesn't have to make a conscious decision on which container to select for every new tab he opens. So once they open google.com in a user selected container, it will always open in that container alone (lets call it search) and next time user opens a new tab and types in google.com, it will go to this search container instead of the default one. This way users can just do Ctrl+T and follow their normal workflow after making a conscious decision earlier on where a certain host should open.

**Comment by groovecoder** [comment]
This is convenient, but it can nullify some of the security protection of containers.

E.g., if Firefox always opens onlinebanking.com in your Finance container, then any click-baiting attack against that site could succeed, assuming you're signed into onlinebanking.com in the Finance container. When Firefox opens onlinebanking.com links into the default container, it isn't signed in.

I'd prefer something like https://github.com/mozilla/testpilot-containers/issues/306 where the user has to make a more explicit action to assign domains to containers.

**Comment by option-greek** [comment]
Agreed. #306 solves this use case as well! (upvoted).

**Comment by kjozwiak** [comment]
As mentioned above, #306 and #386 will solve this use case.
