### ISSUE TITLE
Handle external links that should not be opened in Default context

### ISSUE THREAD

**Issue by attis** [mozilla/testpilot-containers#325]
Currently links coming from external applications open in Default context which poses some problems. I have a "Work" container and it is the only container where I am logged into company GApps account. When following a link from desktop e-mail client or desktop Slack application it opens in a context where I am not logged in so I have to manually copy&paste URL into a new tab that's in Work container.

I realize that the solution will not be simple since external apps typically cannot pass any custom flag when opening a link (like `--container Work`) and even if it could user usually don't want all links from Slack or all links from e-mail client to open in the same context but it varies from link to link. Example: Link to an internal document should be opened in "Work" container but a funny YouTube video that someone posted on #offtop channel - not.

Maybe an easy (one-click) way to appoint certain Container as a default target for external links (+ clear visual feedback on what is current default target container) would help here? Unfortunately there are security implications if someone forgets that "Work" is currently his/hers default target container and clicks on a malicious link... :(

**Comment by groovecoder** [comment]
Closing in favor of #311. Please upvote & comment there.
