### ISSUE TITLE
Show only tabs from the current container

### ISSUE THREAD

**Issue by maverick74** [mozilla/testpilot-containers#328]
Would be good to have an option that would allow one to be able to get into the "shop" container (for example) and see only the tabs from that container (Instead of having them all mixed up)

**Comment by groovecoder** [comment]
Can you effectively do this by moving the chop container tabs into a new window?

**Comment by maverick74** [comment]
Well, i believe it can be done that way and that many people won't mind using multiple windows... but honestly i do!!! I hate to have more that one instance of anything open.

Having 3 or 4 FF windows open in an already crowded taskbar is a nightmare. Pretty much like having a lot of tabs open (which i usually do because of my job... - usually more than 100 - but don't tell this to anyone, they'll think i'm crazy). 

So, having one window, with only the tabs of the current container shown would be gold :)

**Comment by groovecoder** [comment]
I personally use the Tab Groups add-on to accomplish this. I.e., I tend to put all my "Personal" container tabs in 1 tab group, "Work" container tabs in another, etc.

https://addons.mozilla.org/en-US/firefox/addon/tab-groups-panorama/

**Comment by maverick74** [comment]
Yes, i use that as well since Mozilla "killed" the feature in Firefox.

But Tab Groups, Search Bar Tweak and other addons from Luis are going down the drain with recent changes in the addon tech ( see: http://fasezero.com/lastnotice.html )... so, unless somethings change, in November, TabGroups is no more :(

(and this is one of those BIG things that keeps me on FF)

Also, i think this makes a lot of sense for containers

**Comment by groovecoder** [comment]
Can this issue be merged into https://github.com/mozilla/testpilot-containers/issues/336 as a comment? It seems like many people have tab-management feature requests for Containers, and we should consolidate them into a single issue for UX consideration.

**Comment by maverick74** [comment]
Sure it can!!! Go ahead! No problem from my part :)

**Comment by groovecoder** [comment]
Closing this in favor of https://github.com/mozilla/testpilot-containers/issues/336 with a link-back here.

**Comment by maverick74** [comment]
@groovecoder 

As #336 is already closed and this was not implemented, i would like this issue to be reopened...

**Comment by maverick74** [comment]
@groovecoder 
should i create a new bug report or is there an intention to reopen this one???
