### ISSUE TITLE
Container options flashes up when hovering + (new tab) button, I'd prefer Long Press

### ISSUE THREAD

**Issue by jnachtigall** [mozilla/testpilot-containers#331]
As reported at [discourse](https://discourse.mozilla-community.org/t/setting-to-show-container-options-only-when-long-pressing-new-tab-button/14130). I find it find annoying that the Containers always flash up when hovering the `+` (new tab) button. I'd prefer long press for it to show up. 

![container](https://cloud.githubusercontent.com/assets/3307404/23554765/b5559046-0026-11e7-8341-cc40e7f6be6f.gif)

I do not want anybody looking over my shoulder to see "Personal", "Shopping" options, especially at work. Because people might go: Whoo, what's this? And might think I'm doing private stuff at work. I found this so essential that I disabled it again. 

It's like somebody seeing in Private Mode at work, then people also always ask: What is she/he doing? Delicate privacy issues.

**Comment by jnachtigall** [comment]
@smichel17 My concern was not about block-shape, icons or horizontal vs. vertical. I was about the falshing up *immediately*. I'd prefered if it did not *always* turn up, but only on long press. Please reread my above post and also what I've written at discourse.

**Comment by smichel17** [comment]
I think you misread mine. I probably should have emphasized this part:

>I use the new tab button because I like the pop-up.

**Comment by jnachtigall** [comment]
@smichel17 Sorry if I've misread. I had little time when I wrote the first reply and it might come over a bit harsh. Sorry about that.

Anyway, maybe there could be a setting for this, say, radio button with two options:
(o) Show options on hover
(o) Show options on long press

Just an idea, sure it is hard to please everybody.

To answer your question:
> Would it be a reasonable compromise, if there were a pop-up, but it only showed the icons (like what appears to the left when you hover over a category in the containers menu)? 

Not really, this would only be a minor improvement from my point of view as it is still visible (privacy concerns - I'd like to able to hide this). 

Of course, once Containers are well known, this current concerns would diminish because they would not be that suspicious any more.

**Comment by smichel17** [comment]
>Not really, this would only be a minor improvement from my point of view as it is still visible (privacy concerns - I'd like to able to hide this).

I don't quite follow this. If you make all your icons circles, then the pop-up would only be a bunch of colored circles. And, if someone also sees your colored tabs (which they would, since, there's no way to hide it), it's pretty quickly obvious that the colors in the pop-up are related to those on the tabs.

So to me, that seems roughly equal in suspicion level to the tabs being highlighted in different colors in the first place. If I saw someone's tabs highlighted in different colors without knowing what it was, I'd assume it's just a way to organize tabs -- not very suspicious, in my opinion. (maybe you disagree?)

**Comment by jnachtigall** [comment]
> I don't quite follow this. If you make all your icons circles, then the pop-up would only be a bunch of colored circles. 

They would not see at all if it would not flash up immediately on hover, but only on looong left-mouse press. There's a distinction between seeing not at all and seeing just some icons. But I agree that showing only the icons – without "Personal", "Work", "Shopping" – would also be less suspicious 

> And, if someone also sees your colored tabs (which they would, since, there's no way to hide it)

I would hide them and only unhide if it is save to do so (alone in a room) with:
![auswahl_071](https://cloud.githubusercontent.com/assets/3307404/23586401/3bb160c0-0194-11e7-870e-0ab26fb9f519.png)

Eventually, there should be a shortcut for hide/unhide. I'll open a ticket for this for discussion.

But again: My concerns would diminish when Containers are more popular and other people know about the popup flashing up. So maybe just take this feedback and let's see what other users think.

**Comment by jnachtigall** [comment]
I've found an easy solution to my problem. It's so easy it is strange that I did not think of it earlier: I just renamed, changed the icon or deleted the inappropriate "Personal", "Shopping", "Work" things to something more appropriate and less suspicious or "misguiding". 

So I think the flashing popup is not a bad UX actually (Facebook has the same for its like buttons). Long press would probably have discoverability problems.

Mozilla devs: You can close if you want. I'll leave it open for now in case you want to consider this use case / feedback.

Maybe a better approach would be to offer the users different sets of predefined container definitions. For me, the default did not work. A simple "Container 1" and "Container 2" and an easy guided tour to change them at the beginning would have been better. Just some ideas ;)

**Comment by groovecoder** [comment]
I'm going to close this for now since we don't plan to actively work on it.

If we get many more 👍 and/or comments on this issue, we may re-open it.

Thanks for the feedback.

**Comment by jjnilton** [comment]
I think the way it works on Nightly (54.0a2) is better and less intrusive, not exactly for the same reason as @jnachtigall, but I just don't think I need to see the containers list every time I'm hovering the new tab button. It's annoying to see the container list every time I'm going to open a new tab or I hover cursor, maybe going to close the last tab or clicking on a button in the toolbar.

I don't use the Containers feature very much when I'm not working, so I don't see the need to see the list of my containers all the time but when I'm working and I may use containers a bit more, I can see that hovering  the "+" button to show it can be handy, even then I'd like to trigger it manually.

An option to choose if the container list will show up by hovering/long pressing or different key bind (maybe something that would show the list with the keyboard and allow selecting the container with the keyboard) could solve this.

This is my use case, maybe it could come with the option to trigger by hovering by default, but having the option to set it to show only by long pressing or pressing some key combination.

**Comment by deimidis** [comment]
I just notice that you implent this. I begun to search because I was so used to have the option when I hover new tab, that was annpying not find that option with the change.

Is there any way to find news about updates like this? I was hoping it was a problem with nightly, not a new way to open tabs in containers

**Comment by jonathanKingston** [comment]
You should have received a new icon on containers and that should have
shown a screen about the change. Was that not the case?

**Comment by smichel17** [comment]
The message only shows the first time you click the icon. I've missed messages before because I accidentally double clicked and closed the message before I could read it, or because the drop down happened not to render prpoerly that time. Suggestion: show the message each time until the user clicks 'ok'.

**Comment by jonathanKingston** [comment]
This is also the case too. The new icon hides automatically but the message
requires you to click ok. Unless something is broken this should have been
the case.

**Comment by deimidis** [comment]
@jonathanKingston sorry, I just read your comment. In my case, I think it was my fault, just thought that you were implementing a new onboard process, but not read it. 

Is there a way to add this as an option? (and by adding this I mean the option to chose the old behavior)
