### ISSUE TITLE
Make a Feature Prioritization Backlog

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot-containers#332]

**Comment by groovecoder** [comment]
Possibly the dumbest feature prioritization backlog ever:

https://github.com/mozilla/testpilot-containers/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement+sort%3Areactions-%2B1-desc

**Comment by jgmize** [comment]
> Possibly the dumbest feature prioritization backlog ever

For the record, I think sorting by 👍 reactions is quite clever and useful for feature prioritization, and I plan on using that trick myself in the future :)

**Comment by johngruen** [comment]
Since we already did this IRL in our triage meeting today, i'mm gonna mark this as solved
