### ISSUE TITLE
Containers testpilot not showing despite being enabled

### ISSUE THREAD

**Issue by bunnybooboo** [mozilla/testpilot-containers#334]
I installed the Container Test Pilot yesterday. I have Nightly as an app that autostarts each time I login to Arch Linux. Got 5 test pilot experiments running (snooze tabs, containers, pulse, min vid, tab center).

I've started my laptop around 5 times since installing, and I noticed last night and again this morning that the containers testpilot is not displaying on a hover. Clicking the 'Test Pilot' browser icon shows it's enabled.

Disabling then re-enabling has got the experiment to return.

All other test pilot experiments were fully operational without this issue. 

EDIT: Just done a couple of restarts and this bug is not, so far, reproducing
EDIT 2: After several restarts testing [this bug](https://github.com/mozilla/testpilot-containers/issues/335) I've not yet been able to reproduce. Suspicious that degrading performance experienced via that bug potentially had affect on this one.

**Comment by jonathanKingston** [comment]
Hey @bunnybooboo, I'm guessing you haven't seen this again have you?

I'm going to mark this closed, on regard that I think it is down to you having allll of the test pilots.

Feel free to reopen if you see this again. Our QA and ourselves haven't seen it either though.

Thanks for filing both issues!

**Comment by bunnybooboo** [comment]
Short term bug. Now seems fixed. Even with allll of the test pilots ftw.
