### ISSUE TITLE
Embrace the use of containers for tab management

### ISSUE THREAD

**Issue by aleth** [mozilla/testpilot-containers#336]
While not its primary purpose, the fact that the containers implementation provides

- a pretty way to group tabs by colour-coding
- a way to temporarily hide containers

means that a lot of people will probably use it to manage their tabs. While the separation of cookies etc will be less important for them in that case, there's no contradiction, quite the opposite: users may end up using contextual identities when context separation would be appropriate without fully understanding what it is. 

The main stumbling block for using containers in this way is probably #311 or #317, as otherwise the presumption is that the user has decided she will need a container before opening the first tab, which seems likely for banking but not so much for other use cases. The workflow I have in mind is, for example, "let me just mark this bunch of tabs under 'travel' so I can hide them for now, but get back to them later".

Maybe this has been obvious from the start of the design process, in which case I apologize for filing this issue. But if not, I just wanted to point out that with a couple of additional features added, containers make a good replacement for e.g. tab groups (the addon version of which will no longer work after gecko 57).

**Comment by dcaravana** [comment]
+1

**Comment by nol13** [comment]
Can I add, a change to go along with the one mentioned above, to more conveniently be able to only see tabs from one container, and have new tabs open in that container by default. (opening in current container by default maybe not as important if you could easily to move tabs between container though, as long as I don't have to stop and think which container to open into every time I open a tab) As is it takes 3 clicks to hide a group.

**Comment by escapewindow** [comment]
I'm going to miss [tab groups](https://addons.mozilla.org/en-US/firefox/addon/tab-groups-panorama/) when it dies... it'll be a productivity hit.  Adding tab management to container tabs would help mitigate that loss.

**Comment by jxn** [comment]
Yes, Tab Groups and Containers were meant for each other.  It's just a shame that one is coming of age as the other is fading away.

**Comment by groovecoder** [comment]
See also https://github.com/mozilla/testpilot-containers/issues/328, which should count for an additional +5 on this issue.

**Comment by JohnLGalt** [comment]
This actually fits rather well into what I wrote up as a RFF on the discourse site.

**Comment by klint** [comment]
I totally agree with this request and also with this statement above:
> Yes, Tab Groups and Containers were meant for each other. It's just a shame that one is coming of age as the other is fading away.

See my own entry in the discussion about that: [https://discourse.mozilla-community.org/t/could-panorama-feature-be-brought-back-to-firefox/14672](url)

And thanks for containers as they are already :) one of the greatest enhancement of Firefox lately. Hope it will be built-in soon.

**Comment by rastapopougros** [comment]
I have **always** almost 200 tabs, permanently. So the abandoning of TabGroups is really an horrible thing to me. :cry: 

If anything can help me manage and group all my tabs (I have one group per work project, one group for news, one group for home things, etc), I take, I take, I take!

**Comment by dgutov** [comment]
I'm going to join the sentiment, but I worry that Containers might not be the best match with my habits of using Tab Groups. Say, I have two groups: "work" and "play". We'd translate "play" to a "default" container, or all non-container tabs.

One:

As I go about my day, I switch between "work" and "play", and open "unaffiliated" tabs in both. Say, Hacker News links. This step might be addressed if tabs open links in the same container by default.

But then, I'd have to log into Hacker News twice.

I also move tabs between groups, like when I decide when I'm going to read something later at home. Is moving tabs between containers supported at all? Ideally, without reloading the page.

Two:

The bookmarks are going to be separated by Containers (right?); I frequently access some of the same bookmarks from the "play" and "work" groups. Although maybe that's not 100% essential.

**Comment by mirh** [comment]
Very nice point. 
Albeit.. Would it really be all that difficult to ask for a new ***private***(/separate) or ***common***(/normal) container at creation time?

**Comment by dgutov** [comment]
Common meaning "actually just a tab group"? :)

I would like that, of course.

**Comment by escapewindow** [comment]
I'm thinking of them as containers and views.

A container could have multiple views; this would allow for any of your work projects to be part of the work container, but have its own separate view.  Views at this point would be a subset of a single container's tabs, and it would make a lot of sense for containers to support this.

I would also like a view to able to show tabs from multiple containers, at which point views and containers are no longer tied together.  I'm not sure if views would continue to be a containers feature at that point, or its own feature.  But just getting to the above point, where a container can have multiple views, would be very handy in managing tabs.

**Comment by smichel17** [comment]
@dgutov 

> The bookmarks are going to be separated by Containers (right?); I frequently access some of the same bookmarks from the "play" and "work" groups. Although maybe that's not 100% essential.

I'm not sure I understand. Bookmarks separated by container? Unless you're bookmarking a URL with identifiable information in it, you can open a bookmark into whatever container you'd like...

**Comment by dgutov** [comment]
> Check out https://addons.mozilla.org/en-US/firefox/addon/context-plus/

Does it interact well with single page applications, video playback status, existing form input, etc?

> Unless you're bookmarking a URL with identifiable information in it, you can open a bookmark into whatever container you'd like

For now, yes. But see https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers#What_is_.28and_isn.27t.29_separated_between_Containers and https://bugzilla.mozilla.org/show_bug.cgi?id=1213290

**Comment by smichel17** [comment]
Opinion: I would de-prioritize this issue for now, but prioritize its addition in time for the firefox 56 release, one release before xul support is dropped and the [tab groups addon](https://addons.mozilla.org/en-US/firefox/addon/tab-groups-panorama/) stops working.

**Comment by SXZ1** [comment]
@aleth 
> a pretty way to group tabs by colour-coding

This. IE-like tab coloring when parent tab and all child tabs have the same color is a great feature. It would be great to see it in vanilla Firefox.

**Comment by pshem** [comment]
I actually installed Test Pilot&Containers thinking Mozilla finally decided to re-implement Tab Groups(https://addons.mozilla.org/en-US/firefox/addon/tab-groups-panorama/). The idea of having:
a) /common
b) /private  
containers sounds tailored for me, as I currently have:
a) functional Tab Groups(ie. work, to read, code, games etc.) 
b) ICE instances for profile isolation for horrible trackers like Facebook

ICE(https://github.com/peppermintos/ice) was meant for webapps and opening outside links(for example from email) in ICE instances is near on impossible. This is something containers solve and I'll be indefinitely grateful for.

One more integration I'd love to see is per container no-script policies. It's unlikely in the short run, as no-scrip is going through a rapid Web Extension rewrite, but I'd love to see it in the long run. This is especially important for Facebook/Twitter/<non-Diaspora social media> whose ~hounds~ _trackers_ use the same script sources as the website it's self.

Doing the /private and /common modes would require clear visual distinctions, maybe with transparent stripes(think [https://images.duckduckgo.com/iu/?u=https%3A%2F%2Frazzledazzleme.files.wordpress.com%2F2009%2F01%2Fstripe1.png&f=1](url) on the common tabs?

**Comment by mikhoul** [comment]
> Common meaning "actually just a tab group"? :)  

> I would like that, of course.

I agree 200% :octocat:

**Comment by grahamperrin** [comment]
Partly in response to https://github.com/mozilla/testpilot-containers/issues/336#issuecomment-289425819 (I'm in the discussion that @klint began)

I'd love to continue and broaden my embrace of Firefox, but I can not yet see how things such as Firefox containers will work with each other without breaking my workflows. Here: 

[The window is the container – the user groups things within a container – those things are tabs](https://discourse.mozilla-community.org/t/the-window-is-the-container-the-user-groups-things-within-a-container-those-things-are-tabs/15451?u=grahamperrin)

**Comment by jonathanKingston** [comment]
As mentioned in @grahamperrin's thread on discourse I made an extension which does many of the tab management tasks users are wanting.

https://github.com/jonathanKingston/containers-sidebar

This solves:

-  Easy access to opening all of your containers
-  Quick visibility of tab numbers
-  Quick access to jump, sort and close tabs
-  Moving tabs, opens the container section it belongs in and scrolls the selected tab into view

This doesn't solve:

-  Moving a tab into a different container
-  Tiling of windows, probably out of scope for this addon


Whilst this doesn't solve moving to a different container (mostly as mentioned, we have no real solution for this which doesn't impact privacy). It does however make tab creation always visible to the user which ideally will improve the number of times a user opens the wrong container.

After the initial hump of creating a container, I have rarely found I want to move containers. I'm wondering if both assigning a website and container creation can clear up tabs in the wrong container. However I'm not after the same level of tab management that tab groups provide.

**Comment by grahamperrin** [comment]
## An attempt to summarise a handful of key points

1. Test Pilot Containers synchronisation **might** extend to assignments and containers 
2. Test Pilot Containers synchronisation **will not** extend to cookies, storage, tabs or mobile
3. Container-oriented search **will** be implemented in the Sea Containers extension, the scope of this enhancment is not yet clear
4. Test Pilot Containers **will not** allow a tab to be moved from one container to another
5. we **might** gain Core support for movement of a tab from one container to another. 

Much of the technical content, particularly in Bugzilla@Mozilla, is beyond me so @jonathanKingston and colleagues: please correct any false assumptions. Thanks. 

### References

[RapidRelease/Calendar - MozillaWiki](https://wiki.mozilla.org/RapidRelease/Calendar)

Mozilla bug [1323873 - Allow tabs to change user contexts when navigating](https://bugzilla.mozilla.org/show_bug.cgi?id=1323873) 

- 2016-12-15
- priority 3 (medium) since 2017-02-28
- product: Core
- component: DOM: Security
- new, unassigned.

https://github.com/mozilla/testpilot-containers/issues/339#issuecomment-291969002 (2017-04-05) and other comments under _Containers not synchronised · Issue #339 · mozilla/testpilot-containers_

[Comment 1](https://bugzilla.mozilla.org/show_bug.cgi?id=1344231#c1) (2017-04-19) under Mozilla bug _1344231 - TestPilot: Add a existing tab to a container_, with reference to [Consider a tab context menu option to convert a normal tab to a container · Issue #311 · mozilla/testpilot-containers](https://github.com/mozilla/testpilot-containers/issues/311): 

> … duplicate … Will leave open if we decide to implement in native.

– and if I understand correctly, in that duplicate context 'convert a normal tab to a container' is to an _existing_ container (not a new container). 

[Sea Containers sidebar for managing tabs - Test Pilot / Containers - Mozilla Discourse](https://discourse.mozilla-community.org/t/sea-containers-sidebar-for-managing-tabs/15800?u=grahamperrin) (2017-05-11)

[Implement search · Issue #4 · jonathanKingston/sea-containers](https://github.com/jonathanKingston/sea-containers/issues/4) (2017-05-15)

## Thought

With no-one assigned to 1323873, I doubt that the enhancement will be made before the 2017-11-14 release of Firefox 57.

**Comment by groovecoder** [comment]
Thank you everyone for the comments and up-votes on this early issue from the Test Pilot experiment. Ideas in this issue are now filed as separate issues for focused up-voting and discussion.

Now that Containers is available on AMO, we're going to start sending more add-on developers to this list of issues to give them ideas for additional Containers add-ons they can build.

So, to help focus the issue list they see, I'm going to close this one. Please upvote and comment on the individual tab-management issues that are also filed here:

https://github.com/mozilla/testpilot-containers/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by JPFrancoia** [comment]
Tabmarks: https://addons.mozilla.org/en-US/firefox/addon/tabmarks/

Best alternative to tab groups I've found so far.

**Comment by banhgao** [comment]
https://addons.mozilla.org/en-US/firefox/addon/sync-tab-groups/
Same as Tabmarks, plus allowing drag and drop tab.

**Comment by escapewindow** [comment]
I prefer [tree style tab](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/) at this point. I generally have <10 groups and I generally want the top 2-3 groups to preserve history and state for frequent context switching, so discarding tabs and putting them in bookmarks doesn't work for that case. The grouped tabs are collapsible to a single row, and can be dragged and dropped on top of each other to group them.

**Comment by Deledrius** [comment]
Same here.  Any replacement which discards a tab's state and history is a non-starter.

**Comment by klint** [comment]
Just wait for the hide/show tabs API bug to be resolved, and you'll get what you want.

**Comment by CamJN** [comment]
@klint That's pretty unlikely at this point, the API as it currently stands will discard tabs not just hide them, and there is at least one person in a position of power trying to sabotage that API.

**Comment by mirh** [comment]
The api as it currently stands isn't doing anything because it's blocked in a review/whiteboard hell. 
And the mozilla developer isn't more "sabotaging" the api, than whatever other non-development-related message from a random guy is. 
So please, just leave them make whatever even basic api they want, then adding a whatever "do/don't do this" option is prolly going to be a cakewalk.

**Comment by grahamperrin** [comment]
On topic, please: 

> # Embrace the use of containers for tab management 

Closure of this **Firefox _Multi Account Containers_** extension issue is not a reason to go off. 

----

Off-topic, for alternatives to Tab Groups, you can – with GitHub-based authentication – join either/both of the following discussions: 

- [Concern about WebExtensions exclusive strategy from add-on authors and users - Mozillians - Mozilla Discourse](https://discourse.mozilla.org/t/-/13310?u=grahamperrin), which began with focus on Tab Groups
- [Favorite WebExtensions? - Add-ons / Contribute - Mozilla Discourse](https://discourse.mozilla.org/t/favorite-webextensions/17087?u=grahamperrin)

Thanks.

**Comment by stephen304** [comment]
I've been using 57 for a week and I think tab containers is almost perfect for tab groups for those who don't mind giving up tab mobility between groups. You can already create your groups and hide ones you're not working with, there's just no way to make it automatically hide other groups other than the one you are currently working with.

If there were a way to automate hiding containers and providing a menu to "switch" by showing a new container and hiding all the other containers automatically, I would be completely satisfied.

**Comment by stephen304** [comment]
@Deledrius Care to provide context to your thumbs down?

**Comment by maverick74** [comment]
@groovecoder 
I'm sorry for bringing this old issue up again but after giving the addon another try i have to ask: 

am i missing something or we still don't have a preference for 
"**Show only tabs from the current container**" as in issue #328 ?

I mean, we can hide groups, but there is no way of set the behavior of having just the tabs of the current container visible...

**Comment by klint** [comment]
@maverick74 you should give a try to the "Simple Tab Group" addon which provides tabs group management, panorama view and allows to link tab groups and containers (in both directions). You can achieve what you are looking for with it (all tabs in a given group automatically open in a given container, and a tab opened in a given container can be moved automatically to a given group). And of course, only tabs within a group are displayed at a same time (that is the purpose of groups).

**Comment by maverick74** [comment]
@klint it's not the same thing ;)

**Comment by bkRodrigo** [comment]
I use Conex exclusively because of this missing feature
