### ISSUE TITLE
Source view opening in no container

### ISSUE THREAD

**Issue by astoria-software** [mozilla/testpilot-containers#345]
Steps:
1. Open page with form in any container tab
2. Submit form
3. Open "source view" (from context menu or shortcut Ctrl+U)

Source view is opening in tab without container, so POST data, cookies etc is not available.

**Comment by bakulf** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1347604\
This is a platform bug.

**Comment by groovecoder** [comment]
Closing in favor of platform-level bug. Please add votes and comments there.

**Comment by nkestrel** [comment]
This is already fixed in FF53 by [Bug 1325014](https://bugzilla.mozilla.org/show_bug.cgi?id=1325014).
