### ISSUE TITLE
List Container as experiment on testpilot.firefox.com

### ISSUE THREAD

**Issue by D219** [mozilla/testpilot-containers#347]
Actually, the only way to know that Containers exist is with a direct link to its testpilot page, or looking carefully in one of the non main page and noticing there is one link that is not listed on the front page.

Maybe it would be useful to list it on the frontpage along Page Shot, Min Vid, Activity Stream and Tab Center

**Comment by groovecoder** [comment]
I see the Containers experiment listed right between Snooze Tabs and Pulse on the home testpilot.firefox.com ...

![testpilot firefox com-containers](https://cloud.githubusercontent.com/assets/71928/23714052/85d48fa0-03ed-11e7-9eee-644bf2783bd1.png)

**Comment by D219** [comment]
Ah, specific to the french version of the page, and there is no easy way to switch language.

**Comment by rikkit** [comment]
It's also hidden if you don't have the right Firefox version.

**Comment by groovecoder** [comment]
@D219 - what Firefox version are you running?

**Comment by D219** [comment]
@groovecoder : 51.0.1, compilation id 20170125094131.
@rikkit : Using the direct link to the test pilot page allow me to install it, just a warning that no french traduction is available. That may be the reason.

I think the question is closed then, the module didn't appear by lack of french traduction. It work well anyway :).
I ll see if I can find how to make a new traduction, and if I have the time to do it and make a pull request ;)
