### ISSUE TITLE
User created containers lost after firefox update

### ISSUE THREAD

**Issue by src-101** [mozilla/testpilot-containers#349]
I had created a container called "Other" which was lost after firefox updated to 52.0. The other containers that came with the installation are still there.

**Comment by groovecoder** [comment]
Were they lost when you updated to Firefox 52, or were they lost when you enabled the Containers experiment from Test Pilot? Is this a dupe of https://github.com/mozilla/testpilot-containers/issues/346 ?

**Comment by src-101** [comment]
It was lost after the update to 52. I had the old version last night and the extra container I had added was present.

**Comment by groovecoder** [comment]
Thanks for the bug report. We'll triage at our Containers meeting tomorrow.

**Comment by groovecoder** [comment]
Closing as duplicate of https://github.com/mozilla/testpilot-containers/issues/346. Please add 👍 's there.
