### ISSUE TITLE
container colors missing from treestyle tabs' pinned tabs

### ISSUE THREAD

**Issue by escapewindow** [mozilla/testpilot-containers#353]
When I enable testpilot-containers instead of Nightly's containers, [treestyle-tabs](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/)' container colors show up at the bottom of normal container tabs, but disappear from pinned tabs.

When I disable testpilot-containers and use Nightly's containers, treestyle-tabs' container colors show up at the top of both normal (unpinned) and pinned container tabs.

55.0a1 (2017-03-08) (64-bit) osx nightly; tree style tab 0.18.2016111701.  I use tree style tab instead of tab center because tab groups are so central to my browsing workflow.

testpilot containers:
![testpilot-containers](https://cloud.githubusercontent.com/assets/826343/23740722/ba7c03d4-0459-11e7-8d6c-b3b1a53974ee.png)

nightly containers:
![nightly-containers](https://cloud.githubusercontent.com/assets/826343/23740721/ba59d5fc-0459-11e7-9e98-2d1b426f2902.png)

**Comment by groovecoder** [comment]
Thanks for the bug report. I updated your issue to include a link to the incompatible add-on.

**Comment by escapewindow** [comment]
This appears to be working!

55.0a1 (2017-03-13) (64-bit) osx
treestyle tab 0.19.2017031101
containers testpilot last updated march 1

due to those versions, I'm guessing treestyle tab's update fixed it.

**Comment by escapewindow** [comment]
Ah.  It was the default appearance -> compact light theme that "fixed" it.  I suppose we can reopen to fix the default theme, or leave closed since the original reporter (me) is satisfied.
