### ISSUE TITLE
Tab Center integration

### ISSUE THREAD

**Issue by fvsch** [mozilla/testpilot-containers#354]
The current code related to Tab Center is not compatible with recent changes in that extension:

CSS code in Containers extension:
https://github.com/mozilla/testpilot-containers/blob/e90e264beb1740cd47e286ce945101b946460d2e/data/usercontext.css#L193-L203

Issue in Tab Center:
https://github.com/bwinton/TabCenter/issues/405#issuecomment-283765152

The good news is that fixing it in Tab Center should be easy enough:
https://github.com/bwinton/TabCenter/issues/405#issuecomment-283834946

What I suggest is removing Tab Center-related code in this extension, only exposing the container color as a CSS variable (already working). If the container icon URL could be exposed as a variable (like it is on Nightly in the URL bar), that would be ace too, but not a requirement.

In Tab Center I'll try to land a small CSS fix to enable container colors in the left indicator. Do you have any design recommendation for that? Currently Tab Center tabs have a 6px "selected" indicator (always blue). The plan would be to make it take the Container color, and make it 2-3px and always visible for tabs in Containers. So that we have two scenarios:

1. Tab outside of a Container: no color border when not selected, 6px blue border slides in when selected.
2. Tab in a Container: 2-3px border using the container's color when not selected, slides in to take 6px when selected.

On top of that, there might be an opportunity to show the container's icon (perhaps in "large tabs" mode), but it's currently not exposed to the tab element, as far as I know. So I'd leave it out for now.

**Comment by fvsch** [comment]
To be clear, actions in `mozilla/testpilot-containers` would be:
- remove CSS code related to Tab Center, to avoid conflicts
- provide design feedback, if any
- ideally sync with a related Tab Center release, but that's not critical IMO

**Comment by abaez** [comment]
Hey @fvsch, 

I went ahead and did the requirements you listed on getting Tab Center integration working. Hopefully this helps the process along.

**Comment by jonathanKingston** [comment]
Pretty sure this got resolved, please reopen if that isn't the case.

**Comment by fvsch** [comment]
Yup, it's good. :)
