### ISSUE TITLE
Upgrading firefox (51 to 52) resets containers to defaults

### ISSUE THREAD

**Issue by smichel17** [mozilla/testpilot-containers#361]
I updated to ff52 and lost most of my containers, in the following fashion:

- Containers I had added were removed, and tabs that were in them during my previous session were moved into the default container
- Containers I had renamed were reset back to the default name and icon, but tabs in those containers remained

Fedora 25 (gnome 3.22.3, if that matters)

**Comment by Myer** [comment]
Duplicate of #346

**Comment by smichel17** [comment]
ack, mb.
