### ISSUE TITLE
Sometimes 'New tab' button doesn't focus the window

### ISSUE THREAD

**Issue by Aljullu** [mozilla/testpilot-containers#362]
**Steps to reproduce:**
Open Firefox (window A) and another application (window B). Like this:
![image](https://cloud.githubusercontent.com/assets/3616980/23809467/1d3b9fd2-05ce-11e7-8854-2bda0c31fcf4.png)
_In this example, Firefox is window A and Terminal is window B._

Hover the 'New tab' (+ button) in window A. When the list of possible containers appears, click on the + icon or on any container name.

**Expected results:**
The window A gets the focus and goes in front of window B.

**Actual results:**
Window A stays in the background with no focus and window B stays on top of A with focus.

**Notes:**

- This only happens when the list of Containers appeared. If you have the tab bar full and you open two tabs in a row so when you open the second one the Containers list is not there, it works as expected.
- This only happens if window B is not Firefox.

**Environment:**

- Fedora Workstation 25 Gnome.
- Tested with Firefox Nightly 55 and Firefox Stable 51.

**Comment by jonathanKingston** [comment]
I think this might actually be a platform issue with these panels that we are using for this menu. It just so happens it doesn't appear that often in firefox. If in nightly you checkout http://permission.site it should do the same for our "new look" persistent permission prompts. This behaves the same for me there @bakulf do you know if this is something we can fix?

**Comment by shavounet** [comment]
FYI, I still reproduce it on Firefox 53 with Linux Mint 18 (Cinnamon).

**Comment by mprasil** [comment]
@jonathanKingston, it doesn't look like platform issue, this behaviour isn't limited to the container buttons, it also behaves this way when I'm using the "+" button, which doesn't look like part of the menu. (unless some trickery is involved, but I wouldn't call that platform issue either) When I disable containers addon, "+" button works as expected.

**Comment by dkadioglu** [comment]
For me the same happens in Firefox 53 on Arch Linux and KDE Plasma. For me this happens in any case when I hover on the plus button, the container menu is shown and Firefox does not have focus. If I can do anything to help in debugging/fixing this, please ask.

**Comment by chemnic** [comment]
This problem also happens with Firefox 53.0.2, in Ubuntu 14.04 with Unity. It is very frustrating. Is there some progress on this?

**Comment by Aljullu** [comment]
This bug seems to have been fixed thanks to an update of some days ago that made the dropdown appear on click instead of on hover.
