### ISSUE TITLE
Confusing interaction with Tab Center

### ISSUE THREAD

**Issue by jramnani** [mozilla/testpilot-containers#364]
When using Containers, along with the Test Pilot project, Tab Center, there is a confusing interaction when combining the container's tab color and the active tab.

An example will help illustrate:  By default, Containers comes with a "Personal" container that uses a blue tab coloring, and a "Work" container that uses an orange tab coloring.

The Tab Center feature uses a blue vertical bar to highlight the active tab.  This can cause confusing interaction with Containers.  When the active tab is orange, but Tab Center adds a blue highlight, is that tab's container the Work container, or the Personal container?

Personal Container tabs with an active tab:
![blue profile and active tab](https://cloud.githubusercontent.com/assets/68455/23818587/69d654a8-05b1-11e7-9a54-21c863e1d1dd.png)

Work Container tabs with an active tab:
![orange profile and enabled tab](https://cloud.githubusercontent.com/assets/68455/23818599/7b5a5d14-05b1-11e7-977a-c5d3941f9793.png)

I file this bug, not because I think Containers need to change, necessarily. But I figured it would be useful information if both Containers and Tab Center are integrated together.

**Comment by D219** [comment]
This seems to have been fixed, what was the blue selector bar is now of the same color as the container bar.

**Comment by groovecoder** [comment]
Thanks for verifying the loop is closed on this.
