### ISSUE TITLE
Allow container tabs to be "locked" to a domain

### ISSUE THREAD

**Issue by dullroar** [mozilla/testpilot-containers#366]
The visual cues are too subtle. Currently they are a colored underline on the tab plus the icon and name in the address box omnibox (but I almost never look at the omnibox any more, which in modern browsers is becoming the junk drawer that the system tray has turned into for most OS desktops).

I find the visual cues too underwhelming, and constantly open the "wrong" sites in the "wrong" tabs (say, the banking tab, after I am done with banking and then go check the weather). This defeats the whole purpose.

Instead of visual cues already cluttering up a very busy UI, why not an option for the more "restrictive" containers (work, banking) that didn't let you navigate off the domain which you opened them with? Or a way to "pin" domains to specific containers so they (and only they) are opened in that container? As always with security, it is better to prevent the user from doing the wrong thing accidentally rather than counting on them to always use it right, 100% of the time.

**Comment by groovecoder** [comment]
This sounds like a comment that could be added to https://github.com/mozilla/testpilot-containers/issues/306? If so, can you add +1 and comment there and close this?
