### ISSUE TITLE
[1.0.4] video playback not fully supported in a container 

### ISSUE THREAD

**Issue by Jan02** [mozilla/testpilot-containers#367]
on playing video

Application Basics
------------------

Name: Firefox
Version: 52.0
Build ID: 20170302120751
Update Channel: release
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:52.0) Gecko/20100101 Firefox/52.0
OS: Windows_NT 10.0
Multiprocess Windows: 1/1 (Enabled by default)
Safe Mode: false

Crash Reports for the Last 3 Days
---------------------------------

Report ID: bp-006c70ea-b460-484c-b528-742042170312
Submitted: 11 hours ago

Report ID: bp-5bef1e94-f196-49e0-8d63-1a2f72170311
Submitted: 1 day ago

Report ID: bp-3d186b22-d794-496b-a322-ec1132170310
Submitted: 2 days ago

Report ID: bp-a4aafb18-6c86-4d7b-b898-e5ad72170310
Submitted: 2 days ago

Report ID: bp-e787dbae-a0f9-4571-928f-4eb102170310
Submitted: 2 days ago

Report ID: bp-c9984248-febc-4de3-b616-d16d02170310
Submitted: 2 days ago

Report ID: bp-a15198b6-43dd-4a89-aeea-9b4322170310
Submitted: 2 days ago

Report ID: bp-5131c192-cc17-4eb2-ac4c-fbb0e2170310
Submitted: 2 days ago

Report ID: bp-dc1e586f-3b99-4d8b-99b7-31ce02170310
Submitted: 2 days ago

All Crash Reports

Extensions
----------

Name: Add-on Compatibility Reporter
Version: 2.2.3
Enabled: true
ID: compatibility@addons.mozilla.org

Name: Application Update Service Helper
Version: 1.5
Enabled: true
ID: aushelper@mozilla.org

Name: Configuration Mania
Version: 25.2.1
Enabled: true
ID: {c4d362ec-1cff-4ca0-9031-99a8fad7995a}

Name: Containers Experiment
Version: 1.0.4
Enabled: true
ID: @testpilot-containers

Name: Diagnostics
Version: 1.0
Enabled: true
ID: diagnostics@mozilla.org

Name: DownThemAll!
Version: 3.0.8
Enabled: true
ID: {DDC359D1-844A-42a7-9AA1-88A850A938A8}

Name: Fast Image Research
Version: 1.46
Enabled: true
ID: fastimageresearch@usacyborg.com

Name: Greasemonkey
Version: 3.10
Enabled: true
ID: {e4a8a97b-f2ed-450b-b12d-ee082ba24781}

Name: Multi-process staged rollout
Version: 1.9
Enabled: true
ID: e10srollout@mozilla.org

Name: Pocket
Version: 1.0.5
Enabled: true
ID: firefox@getpocket.com

Name: Print Edit
Version: 17.10
Enabled: true
ID: printedit@DW-dev

Name: Reddit Enhancement Suite
Version: 5.4.3
Enabled: true
ID: jid1-xUfzOsOFlzSOXg@jetpack

Name: Rehost Image
Version: 1.5.20
Enabled: true
ID: rehostimage@engy.us

Name: Send HSTS Priming Requests
Version: 1.0
Enabled: true
ID: hsts-priming@mozilla.org

Name: SHA-1 deprecation staged rollout
Version: 1.3
Enabled: true
ID: disableSHA1rollout@mozilla.org

Name: Simple Add-on Manager
Version: 1.1.3
Enabled: true
ID: @simple-addon-manager

Name: Stylish
Version: 2.0.7
Enabled: true
ID: {46551EC9-40F0-4e47-8E18-8E5CF550CFB8}

Name: Tab Unloader
Version: 2016.12.17
Enabled: true
ID: tab-unloader@afnankhan

Name: Test Pilot
Version: 1.1.1-dev-97fd716
Enabled: true
ID: @testpilot-addon

Name: Tile Tabs
Version: 14.9
Enabled: true
ID: tiletabs@DW-dev

Name: uBlock Origin
Version: 1.11.2
Enabled: true
ID: uBlock0@raymondhill.net

Name: Web Compat
Version: 1.0
Enabled: true
ID: webcompat@mozilla.org

Name: Auto Unload Tab
Version: 0.9.1.5
Enabled: false
ID: {d3c46ca0-999d-11da-a72b-0800200c9a66}

Name: Autofill
Version: 3.6.1-signed.1-signed
Enabled: false
ID: firefox-autofill@googlegroups.com

Name: Autofill Forms
Version: 1.1.6
Enabled: false
ID: autofillForms@blueimp.net

Name: Awesome Screenshot - Capture, Annotate & More
Version: 3.0.14
Enabled: false
ID: jid0-GXjLLfbCoAx0LcltEdFrEkQdQPI@jetpack

Name: Complete YouTube Saver
Version: 5.7.34
Enabled: false
ID: {AF445D67-154C-4c69-A17B-7F392BCC36A3}

Name: Coupons at Checkout
Version: 2.0.6
Enabled: false
ID: jid0-5R3LLpyrG0a1kPDXAA8ZKmM0bgM@jetpack

Name: Dark Background and Light Text
Version: 0.5.9
Enabled: false
ID: jid1-QoFqdK4qzUfGWQ@jetpack

Name: Dummy Form Filler
Version: 1.1.1
Enabled: false
ID: 3c3c58b1-7398-4256-9c0d-e57322904c2a@jetpack

Name: Easy Copy
Version: 2.7.0
Enabled: false
ID: easycopy@smokyink.com

Name: Flagfox
Version: 5.1.20
Enabled: false
ID: {1018e4d6-728f-4b20-ad56-37578a4de76b}

Name: FoxClocks
Version: 4.2.3
Enabled: false
ID: {d37dc5d0-431d-44e5-8c91-49419370caa1}

Name: Free Download Manager extension
Version: 2.1.13
Enabled: false
ID: fdm_ffext@freedownloadmanager.org

Name: Go Parent Folder
Version: 2.9.1.1-signed.1-signed
Enabled: false
ID: goParentFolder@alice

Name: gui:config
Version: 1.10.2
Enabled: false
ID: guiconfig@slosd.net

Name: Image Picker
Version: 1.9.5
Enabled: false
ID: ImagePicker@topolog.org

Name: Pencil Prototyping
Version: 2.0.21.20161120
Enabled: false
ID: pencil@prikhi.github.io

Name: Pin It button
Version: 1.37.9
Enabled: false
ID: jid1-YcMV6ngYmQRA2w@jetpack

Name: ReloadEvery
Version: 45.0.0
Enabled: false
ID: {888d99e7-e8b5-46a3-851e-1ec45da1e644}

Name: ReviewMeta.com Review Analyzer
Version: 2.2
Enabled: false
ID: FirefoxExtension@ReviewMeta.com

Name: Save Image in Folder
Version: 1.3.18
Enabled: false
ID: {5e594888-3e8e-47da-b2c6-b0b545112f84}

Name: Session Manager
Version: 0.8.1.13
Enabled: false
ID: {1280606b-2510-4fe0-97ef-9b5a22eafe30}

Name: Tab Scope
Version: 1.6.3
Enabled: false
ID: tabscope@xuldev.org

Name: TableTools2
Version: 1.17.1-signed.1-signed
Enabled: false
ID: tabletools2@mingyi.org

Name: The Addon Bar (restored)
Version: 3.2.9-compat-fixed-4
Enabled: false
ID: the-addon-bar@GeekInTraining-GiT

Name: uMatrix
Version: 0.9.3.6
Enabled: false
ID: uMatrix@raymondhill.net

Name: VTzilla
Version: 1.5.1-signed.1-signed
Enabled: false
ID: info@virustotal.com

Name: Yet Another RSVP Reader
Version: 1.7.4.1-signed.1-signed
Enabled: false
ID: jid1-R4ydAACQ6yqOdw@jetpack

Graphics
--------

Features
Compositing: Direct3D 11
Asynchronous Pan/Zoom: wheel input enabled; touch input enabled
WebGL Renderer: Google Inc. -- ANGLE (NVIDIA GeForce GTX 460 Direct3D11 vs_5_0 ps_5_0)
WebGL2 Renderer: Google Inc. -- ANGLE (NVIDIA GeForce GTX 460 Direct3D11 vs_5_0 ps_5_0)
Hardware H264 Decoding: Yes; Using D3D11 API
Audio Backend: wasapi
Direct2D: true
DirectWrite: true (10.0.14393.351)
GPU #1
Active: Yes
Description: NVIDIA GeForce GTX 460
Vendor ID: 0x10de
Device ID: 0x0e22
Driver Version: 21.21.13.7654
Driver Date: 12-29-2016
Drivers: C:\WINDOWS\System32\DriverStore\FileRepository\nvakwu.inf_amd64_0b3c1a15295d17ee\nvd3dumx,C:\WINDOWS\System32\DriverStore\FileRepository\nvakwu.inf_amd64_0b3c1a15295d17ee\nvwgf2umx,C:\WINDOWS\System32\DriverStore\FileRepository\nvakwu.inf_amd64_0b3c1a15295d17ee\nvwgf2umx,C:\WINDOWS\System32\DriverStore\FileRepository\nvakwu.inf_amd64_0b3c1a15295d17ee\nvwgf2umx C:\WINDOWS\System32\DriverStore\FileRepository\nvakwu.inf_amd64_0b3c1a15295d17ee\nvd3dum,C:\WINDOWS\System32\DriverStore\FileRepository\nvakwu.inf_amd64_0b3c1a15295d17ee\nvwgf2um,C:\WINDOWS\System32\DriverStore\FileRepository\nvakwu.inf_amd64_0b3c1a15295d17ee\nvwgf2um,C:\WINDOWS\System32\DriverStore\FileRepository\nvakwu.inf_amd64_0b3c1a15295d17ee\nvwgf2um
Subsys ID: 00000000
RAM: 1024

Diagnostics
AzureCanvasAccelerated: 0
AzureCanvasBackend: direct2d 1.1
AzureContentBackend: direct2d 1.1
AzureFallbackCanvasBackend: cairo
Decision Log
D3D9_COMPOSITING:
disabled by default: Disabled by default

Important Modified Preferences
------------------------------

accessibility.typeaheadfind.flashBar: 0
browser.cache.directory: E:\
browser.cache.disk.capacity: 204800
browser.cache.disk.directory: E:\
browser.cache.disk.filesystem_reported: 1
browser.cache.disk.hashstats_reported: 1
browser.cache.disk.parent directory: E:\
browser.cache.disk.smart_size.first_run: false
browser.cache.disk.smart_size.use_old_max: false
browser.cache.frecency_experiment: 4
browser.cache.memory.capacity: -1
browser.cache.memory.max_entry_size: 10240
browser.download.folderList: 2
browser.download.importedFromSqlite: true
browser.download.manager.alertOnEXEOpen: true
browser.places.smartBookmarksVersion: 8
browser.search.context.loadInBackground: true
browser.search.useDBForOrder: true
browser.sessionstore.upgradeBackup.latestBuildID: 20170302120751
browser.startup.homepage_override.buildID: 20170302120751
browser.startup.homepage_override.mstone: 52.0
browser.tabs.loadBookmarksInBackground: true
browser.tabs.remote.autostart.2: true
browser.tabs.remote.disabled-for-a11y: true
browser.tabs.warnOnClose: false
browser.urlbar.maxRichResults: 12
browser.urlbar.userMadeSearchSuggestionsChoice: true
dom.apps.lastUpdate.buildID: 20161019084923
dom.apps.lastUpdate.mstone: 49.0.2
dom.apps.reset-permissions: true
dom.disable_window_open_feature.menubar: true
dom.disable_window_open_feature.scrollbars: true
dom.disable_window_open_feature.toolbar: true
dom.mozApps.used: true
dom.push.userAgentID: e845eb9f67c0425db5b126fc5b38c0e6
extensions.lastAppVersion: 52.0
font.default.x-western: sans-serif
font.internaluseonly.changed: true
font.name.monospace.x-western: DejaVu Sans Mono
font.name.sans-serif.x-western: Open Sans
font.name.serif.x-western: Droid Serif
gfx.crash-guard.d3d11layers.appVersion: 52.0
gfx.crash-guard.d3d11layers.deviceID: 0x0e22
gfx.crash-guard.d3d11layers.driverVersion: 21.21.13.7654
gfx.crash-guard.d3d11layers.feature-d2d: true
gfx.crash-guard.d3d11layers.feature-d3d11: true
gfx.crash-guard.glcontext.gfx.driver-init.direct3d11-angle: true
gfx.crash-guard.glcontext.gfx.driver-init.webgl-angle: true
gfx.crash-guard.glcontext.gfx.driver-init.webgl-angle-force-d3d11: false
gfx.crash-guard.glcontext.gfx.driver-init.webgl-angle-force-warp: false
gfx.crash-guard.glcontext.gfx.driver-init.webgl-angle-try-d3d11: true
gfx.crash-guard.status.: 2
gfx.crash-guard.status.d3d11layers: 2
gfx.crash-guard.status.d3d11video: 2
gfx.crash-guard.status.d3d9video: 2
gfx.crash-guard.status.glcontext: 2
gfx.direct3d.last_used_feature_level_idx: 0
image.cache.size: 41943040
media.benchmark.vp9.fps: 166
media.benchmark.vp9.versioncheck: 1
media.gmp-eme-adobe.abi: x86_64-msvc-x64
media.gmp-eme-adobe.lastUpdate: 1461685193
media.gmp-eme-adobe.version: 17
media.gmp-gmpopenh264.abi: x86_64-msvc-x64
media.gmp-gmpopenh264.lastUpdate: 1471555256
media.gmp-gmpopenh264.version: 1.6
media.gmp-manager.buildID: 20170302120751
media.gmp-manager.lastCheck: 1489212732
media.gmp-widevinecdm.abi: x86_64-msvc-x64
media.gmp-widevinecdm.lastUpdate: 1474374020
media.gmp-widevinecdm.version: 1.4.8.903
media.gmp.storage.version.observed: 1
media.hardware-video-decoding.failed: false
media.webrtc.debug.aec_log_dir: C:\Users\Jan\AppData\Local\Temp\CubicExplorerPortableTemp
media.webrtc.debug.log_file: C:\Users\Jan\AppData\Local\Temp\CubicExplorerPortableTemp\WebRTC.log
network.cookie.prefsMigrated: true
network.dns.disablePrefetch: true
network.http.pipelining: true
network.http.proxy.pipelining: true
network.http.speculative-parallel-limit: 0
network.predictor.cleaned-up: true
network.prefetch-next: false
places.database.lastMaintenance: 1488955188
places.history.expiration.transient_current_max_pages: 110377
plugin.disable_full_page_plugin_for_types: application/pdf
plugin.importedState: true
plugin.state.npctrl: 1
print.printer_Microsoft_Print_to_PDF.print_bgcolor: false
print.printer_Microsoft_Print_to_PDF.print_bgimages: false
print.printer_Microsoft_Print_to_PDF.print_duplex: -437918235
print.printer_Microsoft_Print_to_PDF.print_edge_bottom: 0
print.printer_Microsoft_Print_to_PDF.print_edge_left: 0
print.printer_Microsoft_Print_to_PDF.print_edge_right: 0
print.printer_Microsoft_Print_to_PDF.print_edge_top: 0
print.printer_Microsoft_Print_to_PDF.print_evenpages: true
print.printer_Microsoft_Print_to_PDF.print_footercenter:
print.printer_Microsoft_Print_to_PDF.print_footerleft: &PT
print.printer_Microsoft_Print_to_PDF.print_footerright: &D
print.printer_Microsoft_Print_to_PDF.print_headercenter:
print.printer_Microsoft_Print_to_PDF.print_headerleft: &T
print.printer_Microsoft_Print_to_PDF.print_headerright: &U
print.printer_Microsoft_Print_to_PDF.print_in_color: true
print.printer_Microsoft_Print_to_PDF.print_margin_bottom: 0.5
print.printer_Microsoft_Print_to_PDF.print_margin_left: 0.5
print.printer_Microsoft_Print_to_PDF.print_margin_right: 0.5
print.printer_Microsoft_Print_to_PDF.print_margin_top: 0.5
print.printer_Microsoft_Print_to_PDF.print_oddpages: true
print.printer_Microsoft_Print_to_PDF.print_orientation: 0
print.printer_Microsoft_Print_to_PDF.print_page_delay: 50
print.printer_Microsoft_Print_to_PDF.print_paper_data: 1
print.printer_Microsoft_Print_to_PDF.print_paper_height: -1.00
print.printer_Microsoft_Print_to_PDF.print_paper_name:
print.printer_Microsoft_Print_to_PDF.print_paper_size_unit: 0
print.printer_Microsoft_Print_to_PDF.print_paper_width: -1.00
print.printer_Microsoft_Print_to_PDF.print_resolution: 600
print.printer_Microsoft_Print_to_PDF.print_reversed: false
print.printer_Microsoft_Print_to_PDF.print_scaling: 1.00
print.printer_Microsoft_Print_to_PDF.print_shrink_to_fit: true
print.printer_Microsoft_Print_to_PDF.print_to_file: false
print.printer_Microsoft_Print_to_PDF.print_unwriteable_margin_bottom: 0
print.printer_Microsoft_Print_to_PDF.print_unwriteable_margin_left: 0
print.printer_Microsoft_Print_to_PDF.print_unwriteable_margin_right: 0
print.printer_Microsoft_Print_to_PDF.print_unwriteable_margin_top: 0
print.printer_PDFCreator.print_bgcolor: false
print.printer_PDFCreator.print_bgimages: false
print.printer_PDFCreator.print_duplex: -437918235
print.printer_PDFCreator.print_edge_bottom: 0
print.printer_PDFCreator.print_edge_left: 0
print.printer_PDFCreator.print_edge_right: 0
print.printer_PDFCreator.print_edge_top: 0
print.printer_PDFCreator.print_evenpages: true
print.printer_PDFCreator.print_footercenter:
print.printer_PDFCreator.print_footerleft: &PT
print.printer_PDFCreator.print_footerright: &D
print.printer_PDFCreator.print_headercenter:
print.printer_PDFCreator.print_headerleft: &T
print.printer_PDFCreator.print_headerright: &U
print.printer_PDFCreator.print_in_color: true
print.printer_PDFCreator.print_margin_bottom: 0.5
print.printer_PDFCreator.print_margin_left: 0.5
print.printer_PDFCreator.print_margin_right: 0.5
print.printer_PDFCreator.print_margin_top: 0.5
print.printer_PDFCreator.print_oddpages: true
print.printer_PDFCreator.print_orientation: 0
print.printer_PDFCreator.print_page_delay: 50
print.printer_PDFCreator.print_paper_data: 1
print.printer_PDFCreator.print_paper_height: -1.00
print.printer_PDFCreator.print_paper_name:
print.printer_PDFCreator.print_paper_size_type: 0
print.printer_PDFCreator.print_paper_size_unit: 0
print.printer_PDFCreator.print_paper_width: -1.00
print.printer_PDFCreator.print_resolution: 600
print.printer_PDFCreator.print_reversed: false
print.printer_PDFCreator.print_scaling: 1.00
print.printer_PDFCreator.print_shrink_to_fit: true
print.printer_PDFCreator.print_to_file: false
print.printer_PDFCreator.print_unwriteable_margin_bottom: 0
print.printer_PDFCreator.print_unwriteable_margin_left: 0
print.printer_PDFCreator.print_unwriteable_margin_right: 0
print.printer_PDFCreator.print_unwriteable_margin_top: 0
print.printer_Print_Edit_PDF.print_bgcolor: false
print.printer_Print_Edit_PDF.print_bgimages: false
print.printer_Print_Edit_PDF.print_evenpages: true
print.printer_Print_Edit_PDF.print_footercenter:
print.printer_Print_Edit_PDF.print_footerleft: &PT
print.printer_Print_Edit_PDF.print_footerright: &D
print.printer_Print_Edit_PDF.print_headercenter:
print.printer_Print_Edit_PDF.print_headerleft: &T
print.printer_Print_Edit_PDF.print_headerright: &U
print.printer_Print_Edit_PDF.print_in_color: true
print.printer_Print_Edit_PDF.print_margin_bottom: 0.5
print.printer_Print_Edit_PDF.print_margin_left: 0.5
print.printer_Print_Edit_PDF.print_margin_right: 0.5
print.printer_Print_Edit_PDF.print_margin_top: 0.5
print.printer_Print_Edit_PDF.print_oddpages: true
print.printer_Print_Edit_PDF.print_orientation: 0
print.printer_Print_Edit_PDF.print_paper_height: 11.00
print.printer_Print_Edit_PDF.print_paper_name:
print.printer_Print_Edit_PDF.print_paper_size_unit: 0
print.printer_Print_Edit_PDF.print_paper_width: 8.50
print.printer_Print_Edit_PDF.print_reversed: false
print.printer_Print_Edit_PDF.print_scaling: 1.00
print.printer_Print_Edit_PDF.print_shrink_to_fit: true
privacy.clearOnShutdown.downloads: false
privacy.clearOnShutdown.formdata: false
privacy.clearOnShutdown.history: false
privacy.clearOnShutdown.sessions: false
privacy.cpd.downloads: false
privacy.cpd.extensions-sessionmanager: false
privacy.cpd.formdata: false
privacy.cpd.history: false
privacy.cpd.offlineApps: true
privacy.donottrackheader.enabled: true
privacy.popups.showBrowserMessage: false
privacy.sanitize.migrateClearSavedPwdsOnExit: true
privacy.sanitize.migrateFx3Prefs: true
privacy.sanitize.timeSpan: 0
privacy.usercontext.about_newtab_segregation.enabled: true
privacy.userContext.enabled: true
security.sandbox.content.tempDirSuffix: {13e16687-c3af-4be8-8e43-0e563fab055f}
services.sync.declinedEngines: tabs,forms,history
services.sync.engine.greasemonkey: true
services.sync.engine.history: false
services.sync.engine.prefs.modified: false
services.sync.engine.tabs: false
services.sync.lastPing: 1489311441
services.sync.lastSync: Sun Mar 12 2017 09:57:58 GMT-0400 (Eastern Standard Time)
services.sync.numClients: 2
storage.vacuum.last.index: 1
storage.vacuum.last.places.sqlite: 1487054816
storage.vacuum.last.queue.sqlite: 1481840453
ui.osk.debug.keyboardDisplayReason: IKPOS: Touch screen not found.

Important Locked Preferences
----------------------------

Places Database
---------------

JavaScript
----------

Incremental GC: true

Accessibility
-------------

Activated: false
Prevent Accessibility: 0

Library Versions
----------------

NSPR
Expected minimum version: 4.13.1
Version in use: 4.13.1

NSS
Expected minimum version: 3.28.3
Version in use: 3.28.3

NSSSMIME
Expected minimum version: 3.28.3
Version in use: 3.28.3

NSSSSL
Expected minimum version: 3.28.3
Version in use: 3.28.3

NSSUTIL
Expected minimum version: 3.28.3
Version in use: 3.28.3

Experimental Features
---------------------

Sandbox
-------

Content Process Sandbox Level: 1

**Comment by groovecoder** [comment]
Can you be more specific - does this happen on every video playback, or only on some videos?

**Comment by Jan02** [comment]
youtube works

**Comment by jonathanKingston** [comment]
@Jan02 hey would you be willing to provide a URL for us to test with? or other steps for us to reproduce?

**Comment by jonathanKingston** [comment]
Closing as we were unable to replicate and had no further issues. Please reopen and provide a URL if you could. Thanks.
