### ISSUE TITLE
updating to 1.1.1 removes custom containers including all associated cookies

### ISSUE THREAD

**Issue by kjozwiak** [mozilla/testpilot-containers#373]
Updating to 1.1.1 removes all the custom containers and their associated cookies. The default containers that come with the experiment (Personal, Banking, Shopping, Work) don't seem to be affected. Users who are heavy container users and have several custom containers will lose all their data and will have to re-create their custom containers once they're updated..

@groovecoder already found and instance where a user ran into this issues:
* https://discourse.mozilla-community.org/t/containers-update-closed-all-container-tabs/14367

We need to either revert back to 1.0.4 which I believe was the last version or quickly get a fix updated into production to try mitigating the damage.

STR:

* install test pilot via https://testpilot.firefox.com/
* install containers_experi...-1.0.4-fx.xpi manually
* open a personal, work and banking container and visit several websites within each of those containers
* create two custom containers and visit several websites
* wait around 3-5 minutes till FX pings the test pilot and Containers is updated to 1.1.1 (check via about:support)
* once the Container experiment is updated to 1.1.1, all the custom containers will be removed
* if you take a look at the cookies.sqlite database, all the associated cookies with those containers have also been removed

**Comment by groovecoder** [comment]
2.0.0 released and published today. Users should start seeing it update now. It will destroy the custom 1.x.x containers, but we'll follow up quickly with a 2.0.1 release that should verify we preserve custom containers in future updates.
