### ISSUE TITLE
Containers disappeared while I was using them

### ISSUE THREAD

**Issue by ruihildt** [mozilla/testpilot-containers#374]
I'm using `Firefox 54.0a2 (2017-03-13) (64-bit)` on `Ubuntu 16.04 (ElementaryOS)`.

I had a bug where from time to time, all services connected in a container would disappear, and I would have to reconnect at some point in time again.

Right now, a whole container disappeared while I was using it: I was in a container where I had assigned the orange color, and I could see 4 tabs in orange, but when i clicked on the "+" button to add a tab, there was only the purple container left out of the 3 I had setup.

So 2 containers disappeared without warning, one of those being in use when it happened. Restarted Firefox and I was left with the same purple container only.

**Comment by groovecoder** [comment]
We are working on this ASAP.

**Comment by groovecoder** [comment]
This is in the `upgrade` code for `1.0.4` and `1.1.1`, so everyone is going to hit this at least once while upgrading. 😢 Working on a `2.0.0` branch & fix - it will still destroy custom containers when people upgrade, but it should preserve them for future updates after that.

**Comment by ctorgalson** [comment]
@groovecoder: to clarify, are you saying this will affect users upgrading _from_ 1.1.1 to newer versions?

(Just trying to determine if I should continue to use the feature in the medium term: I lost many tabs I wanted to keep track of the last time this happened.)

**Comment by groovecoder** [comment]
Sadly, yes. 😢 The bug is in the `onUnload` code, which is triggered with each update. So even when the fix is in `2.0.0`, the `1.1.1` `onUnload` code will execute when upgrading to `2.0.0`.

But, upgrading from `2.0.0` to future versions will NOT be affected. 😐

**Comment by ruihildt** [comment]
Can you give us an expected date for `2.0.0` ? 
I didn't't get any notification when Containers updated previously.

**Comment by groovecoder** [comment]
Sorry, yeah we expect to release 2.0.0 today or tomorrow. All custom 1.x.x containers will be destroyed in the upgrade 😢 ... but 2.0+ upgrades should be good.

**Comment by groovecoder** [comment]
2.0.0 released and published today. Users should start seeing it update now. It will destroy the custom 1.x.x containers, but we'll follow up quickly with a 2.0.1 release that should verify we preserve custom containers in future updates.
