### ISSUE TITLE
Permanently deletes all container tabs with no remorse when disabled

### ISSUE THREAD

**Issue by nkestrel** [mozilla/testpilot-containers#380]
**STR:**
1. Create a container tab.
2. Disable Containers Experiment extension.
3. Set `privacy.userContext.enabled = false`.
4. Enable extension.
5. Disable extension.

**Result:**
 
All open container tabs are immediately deleted with no possibility of recovery. This behavior persists across sessions whenever the extension is disabled. Can be fixed by disabling extension and setting `privacy.userContext.enabled = true` before enabling extension.

**Update:**

Just had a look at the source and this is **by design** which is quite shocking.

```
if (!this._containerWasEnabled) {
  for (let tab of window.tabs) { // eslint-disable-line prefer-const
    if (this._getUserContextIdFromTab(tab)) {
      tab.close();
      try {
        SessionStore.forgetClosedTab(viewFor(window), 0);
      } catch(e) {} // eslint-disable-line no-empty
    }
  }
}
```
I can understand wanting to clean up the containers for privacy reasons but this kind of surprise data loss is totally unacceptable. If you must do this at the very least you should warn the user and save the current tabs as bookmarks.

**Comment by groovecoder** [comment]
We saw this during testing: https://github.com/mozilla/testpilot-containers/issues/243.

You're right that we clean up the containers for privacy reasons. We tried to find a way to warn the user, but for security reasons, add-ons cannot preempt or pevent their own disable/uninstall.

So I'm sorry to say we don't have a way to prevent this. 😢 If we get more reports and/or 👍 on this, we'll try to make it clear to users that their experiment containers and tabs are destroyed when they disable the experiment.
