### ISSUE TITLE
Switch containers by clicking on container in awesome bar

### ISSUE THREAD

**Issue by mozfreddyb** [mozilla/testpilot-containers#387]
Enhancement suggestion:

I sometimes open a website in the wrong container, i..e., a work related website in no container at all or in the personal container.
To "fix" this have to go through a lot of steps:
1) go to the address bar
2) copy the address
3) open a new work container 
4) paste the address
5) close the old tab

It would be nice if I could just click on the container icon (or right-click on the tab) and reload in a different container.

**Comment by groovecoder** [comment]
This sounds like an alternative UX to https://github.com/mozilla/testpilot-containers/issues/311 ?

**Comment by mozfreddyb** [comment]
Could be, yeah. use case seems similar :)

**Comment by MichelZ** [comment]
This is a great UX enhancement, and would be extremly intuitive to use. Actually, the first thing I did when I saw the bar is clicking on it, and I was surprised that NOTHING happened at all :)

**Comment by lmorchard** [comment]
> This sounds like an alternative UX to #311 ?

Almost, except a normal tab doesn't have a container label at all in the awesome bar. So, there's nothing to click on to convert. Could add one? Otherwise, this issue's UX suggestion only works for tabs already in a container.

**Comment by jonathanKingston** [comment]
Gonna close this due to the privacy impact.

See more explanation here:
https://github.com/mozilla/testpilot-containers/wiki/Moving-between-containers

Feel free to argue comment or suggest etc @mozfreddyb (we would love to solve this case without increasing container leakage)
