### ISSUE TITLE
Permanent cookies set on same site in different containers lost after second browser restart

### ISSUE THREAD

**Issue by nkestrel** [mozilla/testpilot-containers#397]
* Firefox 54
* Containers Experiment 2.0.0

I was using containers previously with `privacy.userContext.enabled` and often lost cookies after a restart due to [Bug 1283709](https://bugzilla.mozilla.org/show_bug.cgi?id=1283709) which was later fixed. ~~This extension appears to have brought this problem back, if I disable it the problem goes away and cookies are retained across sessions like normal.~~

**Update:**

STR
1. Create a container tab, go to http://winware.org/en/cookie-permanent.php and set a permanent cookie with a name.
2. Create a different container tab and do the same.
3. Shutdown and restart Firefox.
4. Go back to the site in each container, note that both cookies still exist.
5. Shutdown and restart Firefox a second time.
6. Go back to the site in each container and note that now only one of the container tabs has remembered its permanent cookie.

Tested Firefox 52 and Nightly 55 with `privacy.userContext.enabled = true`.

Note that this doesn't happen with session cookies that are successfully retained in each container by session restore.

Upstream [Bug 1334587](https://bugzilla.mozilla.org/show_bug.cgi?id=1334587).

**Comment by groovecoder** [comment]
Thanks for the bug-report. Can you add the minimum/exact steps to reproduce?

**Comment by kjozwiak** [comment]
I couldn't reproduce this using the latest fx54.0a2. I logged into several different websites using a variation of default containers (Personal, Work etc..) and several custom containers and went through:

* restoring sessions using about:home
* restoring sessions using "Show your windows and tabs from last time" via about:preferences
* completely closing FX and manually reopening all the containers one by one
* checking and making sure cookies aren't being removed from cookies.sqlite

@nkestrel, it could it be possible that you ran into #374 when the container experiment was updated to 2.0.0? When you noticed this happen, were all your custom containers destroyed as well? #374 would have destroyed all the custom containers but would have left the default containers (Personal, Work, Banking, Shopping) intact. Have you noticed this happening on a regular basis? Or did it just happen the one time?

If this is a regular occurrence, could you provide a bit more detail? Are you being logged out of all your sessions across all containers on a regular basis? Does this happen when restoring sessions or after restarting FX? Is it only particular websites that you're noticing sessions being logged out?

**Comment by jonathanKingston** [comment]
Was this the bug we mentioned in the last triage, where we mentioned using session restore?

/cc @bakulf @groovecoder @kjozwiak

**Comment by nkestrel** [comment]
Added STR. I was mistaken this was caused by the Experiment and is actually caused by `privacy.userContext.enabled`.

**Comment by nkestrel** [comment]
Upstream [Bug 1334587](https://bugzilla.mozilla.org/show_bug.cgi?id=1334587).

**Comment by openjck** [comment]
Has this been fixed now that [bug 1334587](https://bugzilla.mozilla.org/show_bug.cgi?id=1334587) is fixed?

**Comment by nkestrel** [comment]
@openjck yes, thanks for the reminder.
