### ISSUE TITLE
show/hide tabs algorithm is broken

### ISSUE THREAD

**Issue by bakulf** [mozilla/testpilot-containers#40]
STR:

1. open a personal container tab
2. open a second personal container tab.
3. hide them
4. open a third personal container tab

Now, what should I see? only 1 personal container tab o 3 ?
What should happen when I click on hide/show icon?
Should the icon be "hide" or "show"?

**Comment by ChenMorpheus** [comment]
We had the same discussion in #11. You can check more details there.

**Comment by bakulf** [comment]
Duplicate of #11
