### ISSUE TITLE
Some about: protocol urls can assign to a container

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/testpilot-containers#413]
It doesn't actually assign etc however it's confusing
![selection_555](https://cloud.githubusercontent.com/assets/338988/24662006/cfeeba5c-194b-11e7-9ae1-d05309c86e9f.png)

**Comment by kjozwiak** [comment]
STR:

* install the latest version of the containers experiment (2.1.1 being used in this instance)
* visit about:about and right click on the page, you'll notice that "Always Open in This Container" isn't available which is the correct behaviour
* under about:about, right click on about:about and select "Open Link in New Container Tab" and select any random container
* right click on the about:about page that's opened within the container and you'll notice Open Link in New Container Tab" is available

As @jonathanKingston mentioned above, it won't actually assign about: to that specific container, but it could confuse users.
