### ISSUE TITLE
opening origins that belong to specific containers via right click on certain engines opens an extra tab

### ISSUE THREAD

**Issue by kjozwiak** [mozilla/testpilot-containers#421]
When opening an origin from google.com that's already assigned to a specific container in a different container using  "Open Link in New Container Tab" via the right click context menu, another tab is opened in the second container which is blank and never closed.

Reproduced using: Google, Yahoo
Couldn't reproduce using: DDG, Bing

STR:

* install the latest containers experiment (2.1.1 used in this case)
* open a new personal container and visit reddit.com
* right click on reddit and select "Always Open in This Container"
* open a default contianer tab and visit google.com
* search for reddit
* on the main search result, right click on reddit -> Open Link in New Container Tab -> Work

You'll get a new tab that's opened in the Work container that's completely blank with the following URL which doesn't get removed:

https://www.google.ca/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiYo6jar4vTAhXs6oMKHTt3CMcQFggaMAA&url=https%3A%2F%2Fwww.reddit.com%2F&usg=AFQjCNFTmzNOTpLfW33wey8AIySJgUmv_g&bvm=bv.151426398,d.amc

<img width="1106" alt="screen shot 2017-04-04 at 1 56 12 pm" src="https://cloud.githubusercontent.com/assets/2602313/24671278/f53eb620-193e-11e7-910b-5f6694ab9e5c.png">

<img width="1109" alt="screen shot 2017-04-04 at 1 56 25 pm" src="https://cloud.githubusercontent.com/assets/2602313/24671284/f8478374-193e-11e7-9a40-aada46390a0f.png">

**Comment by jonathanKingston** [comment]
For my own sanity:

1. User is in "container A" for web requestId: 2, tabId: 1
2. User right clicks open in "container B" to mozilla.com
3. User has already assigned website to "container C"
4. Browser creates a new tabId: 2 for google.com/redirectmenow.... requestId: 3 in "Container B" timestamp: 1491484646519
5. Browser then redirects to Mozilla.com creating requestId: 4 timestamp: 1491484646801
6. Browser then creates a new tab with permission screen in tabId 3

**Comment by jonathanKingston** [comment]
I can solve the above case using webRequest as the first tab as an undefined originUrl however if the redirect comes from a ctrl+click link click to the same container the originUrl is Google and we can't know that it's not a normal link click that way.

Looking into combining this with webNavigation, not convinced it will work.

It looks like I can't grab the history object for those tabs either as they don't have URLs.

The alternative is change the flow to what I was hoping to do post **53** release:
1. User navigates to google.com
2. Clicks link to Mozilla (Mozilla is assigned)
3. Tab changes to warning screen (same container, if the user requested a new tab then it exists there instead)
4. User clicks confirm
5. New tab is created in the correct container
6. Previous tab is navigated backwards with history removed
