### ISSUE TITLE
add assignment menu on the tab contextual menu

### ISSUE THREAD

**Issue by CircleCode** [mozilla/testpilot-containers#424]
to ease discover of the menu (and ease its use), I would suggest to add the `always open in this container` menu in the tab contextual menu additionally to the page menu

**Comment by jonathanKingston** [comment]
Sorry be to a fool, which menu are you mentioning.

Do you mean this menu (New tab hover)?
![selection_559](https://cloud.githubusercontent.com/assets/338988/24702261/e440b834-19f5-11e7-9ee0-8a7daecca202.png)
Or this one (Browser action menu):
![selection_560](https://cloud.githubusercontent.com/assets/338988/24702300/0dc6f3a8-19f6-11e7-8157-07e8cc511e7e.png)

In my opinion the new tab menu can't have any more items with it's current UI.

**Comment by CircleCode** [comment]
I may not have been clear enough: I was mentioning this menu (none of the two you thought about ;-) ):
![capture d ecran de 2017-04-05 13-38-19](https://cloud.githubusercontent.com/assets/668738/24703803/2903111a-1a05-11e7-81f1-597ceb8f577f.png)

**Comment by jonathanKingston** [comment]
Yeah extensions can't control this currently, which is why it wasn't added.

I will look into if we can add support for that in extensions / add it back into platform.

**Comment by jonathanKingston** [comment]
This is added in 53, so we can add this in the next 2 weeks when 53 becomes stable:
https://blog.mozilla.org/addons/2017/01/25/webextensions-in-firefox-53/

**Comment by jonathanKingston** [comment]
This is blocked on this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1353781

**Comment by jonathanKingston** [comment]
@CircleCode unfortunately this is going away again after testing:
https://github.com/mozilla/testpilot-containers/pull/530

See issue #520 which explains that it isn't contextual to the tab itself nor can it work currently without changes to Firefox.

The issue to follow is: https://bugzilla.mozilla.org/show_bug.cgi?id=1215376 and I don't think we can do anything else to make this work.
