### ISSUE TITLE
add a way to view / edit site assignments

### ISSUE THREAD

**Issue by CircleCode** [mozilla/testpilot-containers#425]
after using assignments several times, I do not remember which I did, and which I did not.
Moreover, I may want to remove some of them without having to open the site in wrong container to uncheck the option.
It would be useful to have a place where all assignments are listed, and it would even be more useful to be able to add / remove / edit them from this place.

--
edited : splited in 2 features request

**Comment by jonathanKingston** [comment]
Agreed, I'm not sure where we would place this in the current UI though so I left this to wait for people to ask for the features as you have 👍

@ChenMorpheus another one that we should have a think about for UX/UI.

**Comment by groovecoder** [comment]
This is now possible in the latest test pilot release.

![image](https://user-images.githubusercontent.com/71928/28444910-eccaf6be-6daf-11e7-9820-76a4ef02eb86.png)

**Comment by tonglil** [comment]
For anyone looking at this now, look at this: https://github.com/mozilla/multi-account-containers/issues/1996#issuecomment-804204494
