### ISSUE TITLE
Icon for dark themes

### ISSUE THREAD

**Issue by abderraouf-adjal** [mozilla/testpilot-containers#439]
Hello,
I notice containers icon on my Firefox (KDE-5 Breeze Dark) doesn't match the dark theme.
[Screenshot](https://i.imgur.com/jotMacV.png).

**Comment by jonathanKingston** [comment]
Hey @abderraouf-adjal are you using the OS default theme or the "compact dark" theme when you go to customise and check your theme? It looks different from dev edition?

If this is an OS level change I'm not sure if we can hook into that.

Also what version of Firefox are you using, you can check by visiting about:support.

**Comment by abderraouf-adjal** [comment]
Hi,
I'm Firefox 52 user, Firefox theme is the default, The OS theme is mentioned.
I "guess" the problem is there is no white icon for dark themes.

**Comment by jonathanKingston** [comment]
We do have a dark theme icon, but only for 'compact dark' which I think is still only available for Dev edition and Nightly. I suspect the Breeze Dark theme from your OS is setting it's own theme for Firefox, which currently we won't be able to do anything about as they are likely changing the icons themselves.

There is an upcoming theme management change for extensions which should hopefully make this no longer an issue... when the OS picks a background the extension will be able to do the right thing.

Unfortunately until then, I don't think we can fix this. When 53 comes out I think you will be able to click ☰ > "Customize" then pick "Compact Dark" theme in the selector which should then change the extension icon to white.
