### ISSUE TITLE
Add Telemetry to learn if users have long-living tabs

### ISSUE THREAD

**Issue by groovecoder** [mozilla/testpilot-containers#446]
https://github.com/mozilla/testpilot-containers/pull/435#discussion_r110716791 for context.

**Comment by ArchangeGabriel** [comment]
Not sure what you mean by long-living, but as a one data point user, I do have tab remaining open for months. ;)

**Comment by groovecoder** [comment]
Oh, I've added Telemetry now. We are seeing # of users who leave container tabs open.
