### ISSUE TITLE
Facebook logged in status not kept in every container

### ISSUE THREAD

**Issue by ruihildt** [mozilla/testpilot-containers#449]
I'm using facebook account A in container 1 and Facebook account B in container 2.

I've noticed for weeks every time I restart Firefox :  
- FB A in container 1 keep me logged in
- FB B in container 2 log me out : I have to reenter my password each time

Since 2 days, it has been the other way round.

Does that happen to someone else? what can I do?

**Comment by jonathanKingston** [comment]
I have session cookies to expire each day for my own browsing.

However this is something that has been reported before I believe, is that the case @kjozwiak?

I don't think it has ever been proven though.

**Comment by nkestrel** [comment]
I can reliably reproduce this with STR in #397.

**Comment by jonathanKingston** [comment]
Making as a duplicate then for now. Reopen if this isn't the case.
