### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by rayman89** [mozilla/testpilot-containers#457]
I don't know if I did understand incorrectly but I thought this experiment allowed you to put tabs into groups but the only thing I notice is a colored line below the tab. I haven't seen a way to put existing tabs on those groups or showing only 1 group or more and hide the rest or anything other than opening new tabs with colored lines below.

**Comment by pshem** [comment]
It's a work in progress. To put existing tabs into containers you can either manually copy the addresses to new tabs created in a container, or use https://addons.mozilla.org/en-US/firefox/addon/context-plus/ 
I don't know what the status on hiding certain containers is.

**Comment by rayman89** [comment]
So those features are going to be implemented later? What about sending a whole window to a container?

**Comment by pshem** [comment]
Disclaimer: I'm not a developer working on this, and I can't speak for them, only from my limited understanding of the project.
Test-pilot features _might_ be implemented. There are no guarantees. That said, even after test pilot shuts down, people will be able to fork the repository and carry the torch is there is a desire to do so.

If https://github.com/mozilla/testpilot-containers/issues/336 happens, hiding containers will be a thing. Passing windows between containers will probably make it into the project, because multiple people want it and the extension I linked previously already contains the majority of the code under a free license. Unfortunately, doing that securely requires sanitizing, ie. reloading the page with no cookies, no cache, etc.

There should probably be a wiki explaining this, but things are changing quite quickly and the project is behind schedule, at least according to Milestones: [https://github.com/mozilla/testpilot-containers/milestones](url)

The strange thing is that there were no updates to the repository in the past 10 days, so the project might be heading to a close. As it's also the second least popular test pilot project, it might not get too far. That said, it's pretty young, so that is likely to change

**Comment by jonathanKingston** [comment]
> put existing tabs on those groups

> Passing windows between containers will probably make it into the project, because multiple people want it and the extension I linked previously already contains the majority of the code under a free license. Unfortunately, doing that securely requires sanitizing, ie. reloading the page with no cookies, no cache, etc.

We are mostly wanting to push users into thinking about tab management as this is a privacy feature. Users can download the context-plus extension however it mostly defeats the benefits we are providing.

> I don't know what the status on hiding certain containers is.

This is already possible in the extension action. Click container icon > click the container name > "Hide this container"

> What about sending a whole window to a container?

Already possible in the extension browser action. You can click the container icon> click the container name > "Move tabs to a new window".

> Test-pilot features might be implemented. There are no guarantees. That said, even after test pilot shuts down, people will be able to fork the repository and carry the torch is there is a desire to do so.

Test pilot is a chance for us to see how people use the extension, so it's not like this will certainly be how we will move forward. Forking **may** be possible, currently we rely on SDK features which won't be able to be used post 57 Firefox. However we are working out what that might mean. I personally don't want this to go away so will be trying to reduce the dependency on these.
Containers has been a very long term project, we are continuing to experiment however that might look.

> The strange thing is that there were no updates to the repository in the past 10 days, so the project might be heading to a close.

I don't think that is strange, it's a small team working on this experiment some have been on holiday and we have other work also. The other decision we made was to relax making lots of changes so we could see how people use the latest changes.

> As it's also the second least popular test pilot project, it might not get too far. That said, it's pretty young, so that is likely to change

We missed the marketing push that other experiments got and we are a little harder to explain than other experiments.

I'm going to close this issue, if there are actionable items we should be looking into let me know, or raise other issues. It looks like both #336 and #311 cover the issues mentioned in this bug, please add any additional comments here.
Thank you for your continued interest in containers.

**Comment by rayman89** [comment]
@jonathanKingston 

> We are mostly wanting to push users into thinking about tab management as this is a privacy feature. Users can download the context-plus extension however it mostly defeats the benefits we are providing.

I'm not quite sure what you wanted to say but all the features we mentioned were for tab managing sake not privacy. We want to be able to organize the tabs into containers to be able to focus into one container to make the browser more tidy and make tabs we looking for easier to find.

> This is already possible in the extension action. Click container icon > click the container name > "Hide this container"

We want all the tabs that are in a window to be all sent to a container. Which is not the same feature that you mentioned. (Aka a way to send multiple tabs at once to a container.  We have sessions with a lots of tabs that we need to organize and if we have to do it 1 by 1 it's going to take a lot of time)

**Comment by simonwiles** [comment]
@rayman89 -- this is what a lot of people (myself included) really want, but I don't think it's really what this experiment is about, sadly.  It would make a lot of sense to address these two concerns (tab management and privacy) together, to my mind.  Perhaps the most unfortunate thing is that an excellent solution to the tab management problem already exists (https://addons.mozilla.org/en-US/firefox/addon/tab-groups-panorama/), and it would make a great base to build privacy separation features on top of, but it will die in November with the release of Firefox 57 and the removal of the APIs it depends on. :(

**Comment by jonathanKingston** [comment]
Work continues to make this something that will be fork-able. Probably in a month you could fork, rename, rebrand etc and go ahead and make this purely a tab management extension.

I and the others working on this extension are part of the Privacy and Security team here at Mozilla and Containers really was designed to "contain" trackers from one tab to the next. I really can understand the frustration at extensions being shut down as part of the 57 push. I really hope you can find alternatives that get what you are after. The problem we have with containers is that we implemented as many features as possible for tab management without deisolating the web traffic and breaking the privacy advantages, which for your use-cases would be frustrating I am sure.

If you have ideas on how we can keep the isolation whilst shipping these features we are all ears but unfortunately we have thought long and hard and have not been able to get anywhere on merging containers and moving tabs from one container to the next.

If any developers want help shipping a fork of this I and others will likely be on hand to help that process, I don't think however it makes sense to make it part of containers or called containers either. For those interested in the migration process to being a standard web extension see: https://github.com/mozilla/testpilot-containers/issues/486

For another extension I worked on that helps with tab management see: https://addons.mozilla.org/en-US/firefox/addon/sea-containers/

Again I am sorry that our use cases don't meet as it would make a lot of sense to ship these features if the isolation was still possible.
