### ISSUE TITLE
Can't install Containers extension in Firefox 53 on Ubuntu 16.04

### ISSUE THREAD

**Issue by MurzNN** [mozilla/testpilot-containers#461]
I have Firefox in Russian language, but understand English too. But I can't install Containers extension from page https://testpilot.firefox.com/experiments/containers - there are no buttons or links to install extension. How can I install it without changing language?

**Comment by MurzNN** [comment]
Seems there are another problem - Containers experiment don't support Firefox 53 version: http://i.imgur.com/PXCSxEu.png - where can be the problem?

**Comment by kjozwiak** [comment]
I couldn't reproduce the issue with my Ubuntu 16.04.2 LTS x64 VM using both the [ru](https://archive.mozilla.org/pub/firefox/releases/53.0/linux-x86_64/ru/) and [en-US](https://archive.mozilla.org/pub/firefox/releases/53.0/linux-x86_64/en-US/) locales for fx53.0. Using the [ru](https://archive.mozilla.org/pub/firefox/releases/53.0/linux-x86_64/ru/) locale, I did get the following error message under https://testpilot.firefox.com/experiments/containers:

```
Этот эксперимент не поддерживат ваш язык (⁨ru⁩).
Вы всё ещё можете включить его, если хотите.
```
Which translates to the following:

```
This experiment does not support your language (⁩ru⁩).
You can still turn it on if you want.
```

However, I managed to download the Containers experiment without any issues.

<img width="638" alt="screen shot 2017-04-24 at 6 04 01 pm" src="https://cloud.githubusercontent.com/assets/2602313/25360794/addc712a-2918-11e7-856d-dd2d1e10d3bf.png">

If fx53.0 wasn't compatible with the container experiment, we would've heard something by now as there's a good percentage of users that are already using fx53.0.

@MurzNN, are you using any extensions that might be changing your UA string? Could paste all the extensions that are listed under `about:support`?

**Comment by MurzNN** [comment]
Oh, sorry, I have install extension that send wrong user-agent. I disable it and all works now!
