### ISSUE TITLE
container functionality lost when FX crashes in the same session that the experiment has been installed in

### ISSUE THREAD

**Issue by kjozwiak** [mozilla/testpilot-containers#463]
Whenever FX crashes and a user has the Containers experiment installed, they'll lose all the functionality that test pilot has installed. Examples:

* Containers button under the toolbar completely disappears
* Always Open in This Container disappears from the context menu
* The containers drop down from the new tab "+" button disappears

You'll also get the following error message in the browser console:

> TypeError: ss.storage.savedConfiguration is undefined - runner.js:1663
> Stack trace:
> init@resource://gre/modules/commonjs/toolkit/loader.js -> resource://testpilot-containers/index.js:171:1
> exports.main@resource://gre/modules/commonjs/toolkit/loader.js -> resource://testpilot-containers/index.js:1590:3
> run@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/addon/runner.js:153:7
> startup/</<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/addon/runner.js:87:9
> process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:917:23
> walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:801:7
> scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:737:11
> 
> TypeError: ss.storage.savedConfiguration is undefined - Promise-backend.js:920
> Stack trace:
> init@resource://gre/modules/commonjs/toolkit/loader.js -> resource://testpilot-containers/index.js:171:1
> exports.main@resource://gre/modules/commonjs/toolkit/loader.js -> resource://testpilot-containers/index.js:1590:3
> run@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/addon/runner.js:153:7
> startup/</<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/addon/runner.js:87:9
> process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:917:23
> walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:801:7
> scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:737:11

@jonathanKingston, this could be one of the reasons that we're seeing a drop off in users throughout the week.. If a user experiences a crash, it looks like all the Container experiment features are removed from FX. However, the strange part is that it's still being listed as installed under `about:support` and the test pilot page.

STR:

* install any version of FX and install the containers experiment via test pilot
* once installed, install https://addons.mozilla.org/en-US/firefox/addon/crash-me-now-simple/
* crash fx and restart the browser

Once FX crashes, you'll notice the error message in the browser console and all the container functionality missing.

**Comment by kjozwiak** [comment]
It looks like this is only happening when FX crashes in the same exact session that the containers experiment has been installed in. Example:

**_100% Reproducible:_**

* install any version of FX
* install CrashMeNow
* install containers experiment via test pilot
* once everything is installed, crash FX using CrashMeNow (same initial session)

_**Not Reproducible:**_

* install any version of FX
* install CrashMeNow
* install containers experiment via test pilot
* once everything is installed, restart FX
* crash FX using CrashMeNow

**Comment by groovecoder** [comment]
Fixed by 1de3f42
