### ISSUE TITLE
"always open in this container" icon really hard to see under the Unity theme (Ubuntu)

### ISSUE THREAD

**Issue by kjozwiak** [mozilla/testpilot-containers#464]
When viewing the right click context menu in a container within Ubuntu, you'll notice that the "Container" icon next to "Always Open In This Container" is really hard to see due to the theming that Unity uses.

<img width="417" alt="screen shot 2017-04-24 at 5 11 14 pm" src="https://cloud.githubusercontent.com/assets/2602313/25407041/d4606d4c-29d6-11e7-967f-433e9ae1bf0e.png">

**Comment by jonathanKingston** [comment]
This is kind of a web extension issue actually, it's probably not going to be fixable without theme detection or something.

**Comment by jonathanKingston** [comment]
@andymckay is there anything we can do for this in WebExtension land? I assume if the extension provided a layer mask like what apple is pushing for webpages this might solve a lot of the iconography issues?

**Comment by jonathanKingston** [comment]
Closing as I raised: https://bugzilla.mozilla.org/show_bug.cgi?id=1367042 I don't think we can fix this here without even more SDK code or resorting to having white icons for the browser action.
