### ISSUE TITLE
External links opened from a Container-ed website open in the same Container.

### ISSUE THREAD

**Issue by smartfonreddit** [mozilla/testpilot-containers#472]
1. Assign www.bing.com to always open in a Container called "Microsoft".
2. Bing search "reddit" and click to open the reddit.com from the search result.
3. Reddit is now in "Microsoft" Container. Anything you click within Reddit will be in "Microsoft" Container.
4. Right click on a link in Reddit and it says "Open Link in New Microsoft Tab" instead of "Open Link in New Tab".

Only www.bing.com should be opened in Microsoft Container by default, not the links that originate from it.

**Comment by anewuser** [comment]
That's the intended default behavior. However, your idea has already been suggested as an option. Please close this issue and follow https://github.com/mozilla/testpilot-containers/issues/437.
