### ISSUE TITLE
Long press  or right click 'new tab button' to show containers instead of hovering

### ISSUE THREAD

**Issue by jjnilton** [mozilla/testpilot-containers#483]
An option to long press the new tab button to show the container list instead of showing on hover would be really appreciated. For my use case, the way it works on Nightly it less intrusive, as I don't always need to see the containers list when I'm opening a new tab, but I can see that's something others could use, so an option to toggle this behavior would be good.

Also, when hovering the "new tab" button, the address bar loses focus, maybe because the big container button/list that appears?

**Comment by hobarrera** [comment]
If users have configured containers (eg: they're actively using them), I'd even opt to show this menu when normal-clicking, rather than long-clicking. The UI lack discoverability right now, since I didn't really think of hovering and mostly discovered this "by coincidence".

**Comment by Stis** [comment]
I prefered on hovering. But it seems I have no choice, I have to longpress now...
And just tested on 3 fresh profiles : FF last version, 52.0.2 and DevEd last version : the panel on longpress is ugly after blinking.

**Comment by jonathanKingston** [comment]
The design isn't the final yet. This is a standard panel so different OSs
look worse. For example Ubuntu looks pretty bsd. But Mac looks like how we
want to make it eventually.
Not sure what you mean about blinking though.
We may make the hover an option in the future however we had very few
reports about people liking that and many more about accidentally
triggering it issues.

**Comment by Stis** [comment]
By blinking, I mean it's like the old panel tries to appear then switch to the standard Windows model.

And I was not totally happy with the on hover, I admit it. But now I could test on hover and long press, I know I prefer the on hover with his cons.

**Comment by smichel17** [comment]
I'll +1 to "I didn't like hover but I now know I dislike long-press even more." I'm using a laptop trackpad, and long press is painfully clunky, to the point where I'm opening 25-30% of my new tabs in the default container, up from ~5% previously.

**Comment by rubcap** [comment]
+1 for long-press feeling clunky. 
Those who _aren't_ using Containers shouldn't be bothered by an on hover menu though.

**Comment by hoelzro** [comment]
I prefer long press, but that's because I *really* didn't like hover (it got in my way too much), so I'm open to other solutions (just my 2¢)

**Comment by jjnilton** [comment]
[**@rubcap**](https://github.com/rubcap) commented on [Aug 4, 2017, 2:03 PM GMT-3](https://github.com/mozilla/testpilot-containers/issues/483#issuecomment-320301203 "2017-08-04T17:03:20Z - Replied by Github Reply Comments"):
> 
> Those who _aren't_ using Containers shouldn't be bothered by an on hover menu though.

That's the problem for me. While I like the feature I don't use all the time, and I don't need to see all my profiles every time I hover the New Tab Button. I can only talk for myself, so it does bother me. I believe there's a better way to interact with this feature and hopefully in a way that can be sustainable by the developers.

One idea would be giving the option to choose between the hover menu and the long-press click. 

But I also think that for laptop users the hover was more convenient because of the trackpad. A suggestion would be using a key combination to trigger the profile list menu or maybe a visual indicator:
- Hold a key while hovering 
- Ctrl + New Tab Button
- Mouse Middle Click + New Tab Button
- A visual indicator alongside the "+" alongside the New Tab Button (or the add-on button itself)

But would be good if the automatic hover behavior could be disabled for those who don't use the feature that much or don't use it at all.

[**@jonathanKingston**](https://github.com/jonathanKingston) commented on [Jul 15, 2017, 8:57 AM GMT-3](https://github.com/mozilla/testpilot-containers/issues/483#issuecomment-315529424 "2017-07-15T11:57:00Z - Replied by Github Reply Comments"):
> Not sure what you mean about blinking though.

Maybe is this the blinking that @Stis means?

![screencast_07-08-2017_16 30 32 webm](https://user-images.githubusercontent.com/228200/29042570-cd648dbc-7b8d-11e7-8c27-e6f8c830c375.gif)

**Comment by Stis** [comment]
> One idea would be giving the option to choose between the hover menu and the long-press click.
Yes, my bad. I thought it was enough implicit I was asking for this option when I said "But it seems I have no choice" 24 days ago.

And yes, it is the blink I was talking about.

**Comment by jonathanKingston** [comment]
The blink was due to the removal of the manage option, which we since removed anyway. Closing this as there is a style change bug still open.

**Comment by Stis** [comment]
The blink was just a little issue explained well and already noted to be fixed.

The OP was about having the choice to longpress OR hover, and we are still many, at least me, to want the hover option.

If there is another thread about it, I missed it and I'm sorry.
