### ISSUE TITLE
“Always Open in This Container” doesn’t work in Firefox Nightly

### ISSUE THREAD

**Issue by geeknik** [mozilla/testpilot-containers#484]
STR:

1) Install Firefox Nightly
2) Install Test Pilot and Containers
3) Open container tab
4) Open some link in this container tab
5) Select always open in this container
6) Close container tab
7) Open new non-container tab
8) Try to visit site marked in step 5
9) Doesn't open container tab, defeating the purpose 

Browser Console shows this message during step 5:
```
TypeError: WeakMap key must be an object, got undefined  ext-utils.js:181:5
```

**Comment by jonathanKingston** [comment]
@geeknik can you paste the extensions you have installed in about:support, OS info and Firefox version?
If you have an example site too that would be great.

**Comment by geeknik** [comment]
Windows 10 Pro x64

Firefox Nightly x64 v55.0a1 (Build ID 20170507030205)

```
Test Pilot	1.1.2-dev-f3fe9bf	true	@testpilot-addon
Containers Experiment	2.2.0	true	@testpilot-containers
```

**Comment by geeknik** [comment]
If you can't repro with my original STR, here is an alternate based on a dirty profile I found that works:

1) add a site to the "always open in this container" (let's use `https://www.facebook.com`)
2) verify that it opens in a container
3) Remove Test Pilot extension (doing this will also remove the containers experiment)
4) Restart Nightly
5) Reinstall Test Pilot and re-enable the containers experiment
6) Can't add any sites to "always open in this container"

Extensions installed in this dirty profile:

```
Buffer	3.0.4	true	firefox@buffer
CanvasBlocker	0.3.7-Release	true	CanvasBlocker@kkapsner.de
Containers Experiment	2.2.0	true	@testpilot-containers
Disable WebRTC	1.0.16	true	jid1-5Fs7iTLscUaZBgwr@jetpack
Greasemonkey	3.11	true	{e4a8a97b-f2ed-450b-b12d-ee082ba24781}
HTTPS Everywhere	5.2.15	true	https-everywhere@eff.org
In My Pocket	0.2.1	true	{cd7e22de-2e34-40f0-aeff-cec824cbccac}
LastPass: Free Password Manager	4.1.49a	true	support@lastpass.com
Mailvelope	1.7.2	true	jid1-AQqSMBYb0a8ADg@jetpack
Privacy Badger	2017.4.19.1	true	jid1-MnnxcxisBPnSXQ@jetpack
Test Pilot	1.1.2-dev-f3fe9bf	true	@testpilot-addon
uBlock Origin/webext	1.12.3b1	true	uBlock0-webext@raymondhill.net
```

Latest x64 Nightly on Windows 10 Pro x64.

**Comment by jonathanKingston** [comment]
Can't replicate with either STR on clean or dirty profile on Linux. Will check windows tomorrow. Didn't check with all extensions installed either.

**Comment by kjozwiak** [comment]
I couldn't reproduce the issue on two different Win 10 Pro x64 machines. I also tried installing all of the extensions that were listed by @geeknik but I couldn't reproduce the problem after a few hours of attempts. Installed the following extensions on both Win 10 Pro x64 machines:

```
Buffer	3.0.7	true	jid1-zUyU7TGKwejAyA@jetpack
CanvasBlocker	0.3.7-Release	true	CanvasBlocker@kkapsner.de
Containers Experiment	2.2.0	true	@testpilot-containers
Disable WebRTC	1.0.16	true	jid1-5Fs7iTLscUaZBgwr@jetpack
Greasemonkey	3.11	true	{e4a8a97b-f2ed-450b-b12d-ee082ba24781}
HTTPS Everywhere	5.2.15	true	https-everywhere@eff.org
In My Pocket	0.2.1	true	{cd7e22de-2e34-40f0-aeff-cec824cbccac}
LastPass: Free Password Manager	4.1.49	true	support@lastpass.com
Mailvelope	1.7.2	true	jid1-AQqSMBYb0a8ADg@jetpack
Privacy Badger	2017.4.19.1	true	jid1-MnnxcxisBPnSXQ@jetpack
Test Pilot	1.1.2-dev-c4639a2	true	@testpilot-addon
uBlock Origin/webext	1.12.3rc2	true	uBlock0-webext@raymondhill.net
```
@geeknik, would you be able to provide us with a video of the issue occurring? Perhaps a gif? This would help us understand what you're exactly seeing. I'm really surprised you're seeing that behaviour and a brand new clean profile. I imagine we would have received a lot more reports if this was happening reliably. Do you maybe have any toolbars installed?

@geeknik, Regarding the case with the "dirty profile", could it be that you're running into #423. Mind taking a look at the attached video [here](https://www.youtube.com/watch?v=246jXN2O0KI) and letting me know if this was what you were seeing.

Thanks @geeknik, really appreciate the help!

**Comment by geeknik** [comment]
I don't have time to devote to this issue. I've already uninstalled the extension and moved on to something else.
