### ISSUE TITLE
Create on-boarding variations

### ISSUE THREAD

**Issue by groovecoder** [mozilla/testpilot-containers#498]
From [the PHD](https://docs.google.com/document/d/1vMD-fH_5hGDDqNvpRZk12_RhCN2WAe4_yaBamaNdtik/edit)

* Existing on-boarding in Test Pilot
* [Privacy-emphasized on-boarding](https://drive.google.com/open?id=0B_NalwdgcXpqTTlnWXZmSXJzVUU)
* Control

@ChenMorpheus - how is the existing on-boarding different from the Control?

**Comment by johngruen** [comment]
I'll chase down @ChenMorpheus for details

**Comment by johngruen** [comment]
@ChenMorpheus has these ready; getting string review now

**Comment by ChenMorpheus** [comment]
I just copy and paste my comment for Luke's question from the PHD to here for record.

Control group here is to collect data "without" Containers which are then compared to determine the changes that may occur due to the experimental treatment.

**Comment by johngruen** [comment]
Strings being reviewed here: https://docs.google.com/document/d/1PgTjCvagjy3un64GfbIShvJBgi3FCe-YBd0XMdnm-Dc/edit?userstoinvite=mheubusch@mozilla.com&ts=593acfb8&actionButton=1

**Comment by hobarrera** [comment]
Looks like the linked docs are private I need permissions to see it.

**Comment by johngruen** [comment]
@hobarrera sorry about that; should be open now

**Comment by hobarrera** [comment]
Yup thanks (though only the first link is public still).

**Comment by ChenMorpheus** [comment]
@groovecoder 
Here is the asset for the last onboarding. Sorry that I thought we had provided it already.

https://www.dropbox.com/sh/bfyks23ncp46yuu/AAC4HCMRYwvqA1IA1xFHwq-7a?dl=0

**Comment by jonathanKingston** [comment]
Hey @groovecoder could you make the command the following:

```
    "package-shield": "./node_modules/json/lib/json.js -I -f package.json -e 'this.name=\"shield-study-containers\"' && jpm xpi && ./node_modules/json/lib/json.js -I -f package.json -e 'this.name=\"testpilot-containers\"'",
```

That way the dependency comes from the installed version rather than global. I didn't have the global version so it silently failed etc.

Thanks
