### ISSUE TITLE
Implement containers management UI in toolbar widget

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot-containers#5]
<img width="444" alt="screen shot 2016-12-15 at 1 39 31 pm" src="https://cloud.githubusercontent.com/assets/3323249/21237198/f547f4fc-c2cb-11e6-91e9-105f474f569a.png">

- [x] it should register a toolbar icon for containers experiment
- [x] on click, it should show a menu panel with the following:
 - [x] The experiment icon and title
 - [x] A sort button
 - [x] A list of current containers
 - [x] A button to toggle to the container editor UI

**Comment by groovecoder** [comment]
https://github.com/mozilla/testpilot-containers/pull/15 starts a lot of this.

**Comment by groovecoder** [comment]
All this display is done. The sort button implementation is #9. We still need mock-ups converted to issues for the container editor UI.
