### ISSUE TITLE
Pop-up: manage site assignments from container

### ISSUE THREAD

**Issue by groovecoder** [mozilla/testpilot-containers#501]
See https://docs.google.com/document/d/1zrk_M8Adqc05jMlgPFc0fyUdEysApCY3SO1QPpgT3gM/edit ...

<img width="398" alt="image" src="https://cloud.githubusercontent.com/assets/71928/25915876/703d480e-3588-11e7-9472-c209fae3b6f4.png">

**Comment by jonathanKingston** [comment]
I can work on at least making the MVP code appear here. May need style after etc.
