### ISSUE TITLE
Disabling and re-enabling Containers extension while browser.photon.structure.enabled = true crashes the browser

### ISSUE THREAD

**Issue by emmyemi** [mozilla/testpilot-containers#507]
**Version**: Nightly 55.0a1 (2017-05-13)

**Steps to reproduce**:
- Set `browser.photon.structure.enabled` to `true` in about:config
- Disable Containers
- Re-enable Containers

This probably isn't a huge issue, since Photon likely won't be hitting Nightly in full until 57, but I did manage to catch this and thought it'd be best to report it sooner rather than later.

**Comment by jonathanKingston** [comment]
Probs one for you Baku when you get time.

**Comment by bakulf** [comment]
I'm not able to reproduce it. Could it be that it is already fixed?

**Comment by emmyemi** [comment]
Following the same steps I provided, I'm unable to reproduce it now either. It may be that it was just an issue with that particular build—in which case, sorry for the not-too-helpful report!

**Comment by jonathanKingston** [comment]
I'm going to mark this as closed, mostly because I suspect it was related to photon and not containers specific. Please reopen if you spot it again.
Thanks for the report!
