### ISSUE TITLE
TypeError: ss.storage.savedConfiguration is undefined

### ISSUE THREAD

**Issue by past** [mozilla/testpilot-containers#508]
I get a failure to start the add-on on Windows and the console contains this stack:

testpilot-containers:TypeError: ss.storage.savedConfiguration is undefined
Stack trace:
init@resource://gre/modules/commonjs/toolkit/loader.js -> resource://testpilot-containers/index.js:171:1
exports.main@resource://gre/modules/commonjs/toolkit/loader.js -> resource://testpilot-containers/index.js:1590:3
run@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/addon/runner.js:149:7
startup/</<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/addon/runner.js:83:9
process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:922:23
walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:806:7
scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:742:11
  runner.js:162
testpilot-containers:TypeError: ss.storage.savedConfiguration is undefined
Stack trace:
init@resource://gre/modules/commonjs/toolkit/loader.js -> resource://testpilot-containers/index.js:171:1
exports.main@resource://gre/modules/commonjs/toolkit/loader.js -> resource://testpilot-containers/index.js:1590:3
run@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/addon/runner.js:149:7
startup/</<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/addon/runner.js:83:9
process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:922:23
walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:806:7
scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:742:11
  Promise-backend.js:925

**Comment by jonathanKingston** [comment]
I couldn't actually replicate this error, we even have code above populating it if it doesn't exist. Unless you had an older version of the addon that just upgraded perhaps.

I have made the code a little more paranoide @groovecoder any idea?
