### ISSUE TITLE
File shield study bugs

### ISSUE THREAD

**Issue by groovecoder** [mozilla/testpilot-containers#511]
Follow the process here:

https://mozilla.github.io/shield-studies-docs/study-process/

**Comment by jonathanKingston** [comment]
@johngruen I'm working on #501 which is nearly complete, every other part is in a PR so might have follow ups but we are about ready for this. There are a fair few bugs for shield we are blocked on you for. Do you know what is happening with those?

Thanks

**Comment by johngruen** [comment]
Meta Bug Here: https://bugzilla.mozilla.org/show_bug.cgi?id=1371384

Other tree bugs to be filed pending confirmation of documentation in today's check in

**Comment by johngruen** [comment]
@groovecoder can you confirm that the metrics.md doc is up to date for the shield study?

**Comment by groovecoder** [comment]
The `metrics.md` file is accurate with 1 exception:

> The user clicks "Open in Current container" to reload a site into a container after the user picked "Always Open in this Container".

This is new functionality in the shield study (or next version of Test Pilot add-on - however you want to look at it). So we need to add this probe. I'll do that now.

**Comment by groovecoder** [comment]
Filed https://github.com/mozilla/testpilot-containers/pull/577

**Comment by groovecoder** [comment]
https://github.com/mozilla/testpilot-containers/pull/582 merged, so I'm removing myself from this task now. `metrics.md` is up-to-date for the pings sent by both the test pilot add-on and the shield study add-on.

**Comment by groovecoder** [comment]
Closing issue, please follow https://bugzilla.mozilla.org/show_bug.cgi?id=1371384
