### ISSUE TITLE
Follow up new tab/plus button fixes

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/testpilot-containers#52]
After #51 we need:
- new tab css fix for down arrow
- icon fixes
- other changes to make it match the mockup

**Comment by johngruen** [comment]
@jonathanKingston lets talk about this when we get back

**Comment by jonathanKingston** [comment]
@johngruen the initial work has been uploaded as part of @bakulf's patch however there are some things to fix certainly.

Namely:

- [ ] alignment of the menu when it reaches tab overflow on the right
- [ ] width of the menu
- [ ] timeout of the menu should probably be shortened
  - [ ] part of the plus button also appears to be inactive which shortening this timeout would make more noticeable
- [ ] Style and sizing of the menu
