### ISSUE TITLE
"Always Open in This Container" not always displaying the correct state

### ISSUE THREAD

**Issue by kjozwiak** [mozilla/testpilot-containers#520]
When assigning a particular website to a container using "Always Open in This Container", right clicking on other container tabs that are currently opened will display the incorrect state for "Always Open in This Container".

STR: (example: [https://youtu.be/8RBx9-xta4w](https://youtu.be/8RBx9-xta4w))

* install the latest [unbranded version of fx53.0.2](https://wiki.mozilla.org/Add-ons/Extension_Signing#Unbranded_Builds)
* install Containers 2.3.0 via the `bump-version-2.3.0` branch
* open a personal container and load any website (used reddit.com)
* open a work container and load a website (used linkedin.com)
* open a banking container and load a website (used paypal.com)
* once you have all the tabs opened, switch back into the personal container
* right click on the page and select "Always Open in This Container"

Once you've assigned that website to the personal container, right clicking on either the work or banking container will show `Always Open in This Container` as enabled even though those websites are not associated with a particular container. It seems like the states in the context menu are incorrectly being displayed.

I created a video that I've added above that shows how `Always Open in This Container` jumps around into different states that don't necessarily match the actual state of each tab.

**Comment by jonathanKingston** [comment]
I think this is the same as the assignment issue regarding not updating always.

It also is made worse by opening the context menu on the tab... this doesn't check the tab the user has clicked on currently (not sure if we can either, will check).

If we can't do this, then likely we should disable context on the tab itself.

**Comment by kjozwiak** [comment]
> It also is made worse by opening the context menu on the tab... this doesn't check the tab the user has clicked on currently (not sure if we can either, will check).

Yup, that's my main worry with this bug.. Having the ability to see the `Always Open in This Container` when right clicking on non-active tabs might compound the confusion when they notice that websites are selected as `Always Open in This Container` even though the user hasn't made that decision. Also vise versa for websites that have been selected to open in a particular container but the `Always Open in This Container` doesn't appear selected when right clicking on tabs.

> If we can't do this, then likely we should disable context on the tab itself.

Agreed! If we can't fix this, I think we should remove `Always Open in This Container` from the context menu when a user right clicks on non-active tabs.

If we don't fix/remove this, I think it's going to cause a lot of confusion which I don't think we want as we're trying to push more users to use this feature in 2.3.0. We've even added a new onboarding tile that highlights this feature.

**Comment by groovecoder** [comment]
Okay, I was able to reproduce this, but it's fixed in https://github.com/mozilla/testpilot-containers/pull/521 for some reason.
