### ISSUE TITLE
Where to get earlier versions of the extension?

### ISSUE THREAD

**Issue by UserNaem** [mozilla/testpilot-containers#524]
https://testpilot.firefox.com will only provide the latest version, which now seems to behave like the "containers" feature built into Nightly, but I want to stick to the old version, it worked without issues and I customized its appearance to some extent. Is it available anywhere?

**Comment by jonathanKingston** [comment]
What version of Firefox are you using, it might be if you are using Nightly
the extension has been disabled erroneously as part of the legacy extension
deprecation.

Check about:addons for what you have enabled.

We currently don't have old builds of the extension as they need to be
signed by test pilot. I can double check on this however we have not
removed any features just added.

If you could screenshot or explain more of the issue you are seeing that
would be super helpful.

**Comment by UserNaem** [comment]
Firefox Developer Edition 54.0a2 (2017-04-18, 64-bit), Containers Experiment 2.2.0.
After Firefox's add-on updater has updated the Containers experiment a few times, everything went wrong. Upon hovering the new tab button, nothing shows up anymore (it used to be the list of containers to open the new tab with), one of the containers changed colours (from green to light blue), the toolbar button changed itself to the same as the one I've seen in Nightly. It also broke a custom style sheet (CSS) I've made a while ago.

![image](https://cloud.githubusercontent.com/assets/21028464/26283498/70912870-3e43-11e7-879a-c727daa0af93.png)
CSS: 
```
  .tabbrowser-tab[usercontextid] {
    background-image: linear-gradient(to right, transparent 20%, var(--identity-tab-color) 30%, var(--identity-tab-color) 70%, transparent 80%);
    background-size: auto 1px;
    background-repeat: no-repeat;
}
```
I don't know what was changed exactly between versions of the Containers experiment, but in this screenshot you can see a 1px orange line above the active tab, and a 1px light blue line above another inactive tab. And after some update to the Containers experiment, the underline is not visible when the Firefox window is maximized. I know this is caused by this:
```
#TabsToolbar:not([inFullscreen=true]), #tabbrowser-tabs {
margin-top:-1px!important;
}
```

But previously everything worked fine and I'd really prefer sticking to what works than "updating for the sake of updating" and then solving issues rising out of nowhere.

**Comment by jonathanKingston** [comment]
@UserNaem I'm not sure what would have messed up the tabs other than the experiment has been disabled. In about:addons is it still enabled? The colours in Firefox without an enabled addon are likely the difference you mention.
The Firefox version is likely more stable if you don't want our panel that drops down to manage containers.

Unfortunately being bleeding edge software we haven't really expected people to customise like you are doing 👍. Out of interest what were you changing the CSS for?

**Comment by jonathanKingston** [comment]
@groovecoder do we have the old built versions at all?

**Comment by UserNaem** [comment]
@jonathanKingston 

> In about:addons is it still enabled?

Yes, shows as enabled in the add-ons manager and on testpilot.firefox.com.

> The colours in Firefox without an enabled addon are likely the difference you mention.

No, I don't have any custom themes interfering with the appearance of tabs (other than the "Compact Dark" theme), and the inbuilt Containers feature is not available in Firefox Dev Edition.

> Out of interest what were you changing the CSS for?

I wanted the color labels (CSS value `--identity-tab-color`) to be shown above the tab (current default behavior) rather than below the tab (old default behavior). I made it by copy-pasting the many `[data-identity-color="(some color)"]` rules from the stylesheet from the .xpi and adding these rules:
```

  .tabbrowser-tab[usercontextid] .tab-background-middle::after,
#main-window[style*='compact'] .tabbrowser-tab[usercontextid] .tab-content::after {
  bottom: unset!important;
  top:2px;
    background-image:linear-gradient(90deg,#272b35,var(--identity-tab-color) 15%, var(--identity-tab-color) 85%, #272b35 100%)!important;
}
  .tabbrowser-tab[usercontextid] {
    background-image: linear-gradient(to right, transparent 20%, var(--identity-tab-color) 30%, var(--identity-tab-color) 70%, transparent 80%);
    background-size: auto 3px; /*This used to be 1px before Containers Experiment 2.2.0*/
    background-repeat: no-repeat;
}
```

**Comment by groovecoder** [comment]
We haven't kept the older builds. The Test Pilot CI server builds and uploads the `.xpi`s to Test Pilot. It should be possible to build any version by checking out the old commit and running `jpm xpi`.

**Comment by UserNaem** [comment]
For reasons beyond my understanding, after I removed @testpilot-containers.xpi from my profile's extensions folder, the containers feature did not go away (but the addon itself did disappear from about:addons). Was the containers feature included in Firefox Dev Edition 54.0a2 (2017-04-18)? Either way, I reinstalled the extension from https://testpilot.firefox.com and everything fixed itself, I only had to change the container colour to green.

Still, it would be great if older XPI builds were available the same way older versions of extensions are available on addons.mozilla.org, not everyone is a developer and is able to build and sign XPIs themselves if the latest version doesn't work for them for any reason. Can't you just, like, host these experiments on addons.mozilla.org, too? I see no harm in that.

**Comment by jonathanKingston** [comment]
@UserNaem sounds like something got corrupt as I mentioned before. What you were seeing was the native version, this is available in all releases of Firefox right now with the preference `privacy.userContext.enabled` in about:config. Our extension uses this and turns it on.

> not everyone is a developer and is able to build and sign XPIs themselves if the latest version doesn't work for them for any reason

This is also not an option unless you are on an unbranded version or self built version of Firefox.

> Can't you just, like, host these experiments on addons.mozilla.org, too? I see no harm in that.

This is a decision made by Test Pilot itself I would suspect this is to do with not wanting general users access to potentially very experimental features.

> No, I don't have any custom themes interfering with the appearance of tabs (other than the "Compact Dark" theme), and the inbuilt Containers feature is not available in Firefox Dev Edition.

It is, just not enabled by default. If the extension got broken somehow you likely returned to the native version which is enabled by the addon and then modified. This is enabled by `privacy.userContext.enabled` in about:config.

> I wanted the color labels (CSS value --identity-tab-color) to be shown above the tab (current default behavior) rather than below the tab (old default behavior)

Other way around, the default in stable is the highlight and we are changing that to how Test Pilot has it to be an underline. You are the first mention of wanting the above highlight. We had many complaints about the top highlight being very hard to see, especially on certain operating systems. Perhaps it is worth creating a bug for this to discuss?

@johngruen is there any plans to make older XPIs available on AMO? The security hat in me says this is a very bad idea for all addons, but I wanted to ask.

I'm going to close this for now as it's not something in our control here (@johngruen can answer if test pilot will do this)

**Comment by UserNaem** [comment]
> What you were seeing was the native version, this is available in all releases of Firefox right now with the preference `privacy.userContext.enabled` in about:config. Our extension uses this and turns it on.

Oh, okay. Good to know.

> We had many complaints about the top highlight being very hard to see, especially on certain operating systems. Perhaps it is worth creating a bug for this to discuss?

The same colors have different visibility on differently colored tabs, different monitors and different eyes. Can't provide any input on this potential issue, it works for me, maybe someone else who knows more.
