### ISSUE TITLE
Consider alternative ways to add site to 'Always Open in This Container'

### ISSUE THREAD

**Issue by ben914** [mozilla/testpilot-containers#543]
When I go to Google Drive, or Google Docs, etc. there is no right click context menu to access the 'Always Open in This Container' option. There might be other sites that also have no context menu. It would be helpful to have other ways to do this. Perhaps by right clicking the tab itself, or on the URL bar, or by manually adding a URL in a preferences setting or something like that.

**Comment by jonathanKingston** [comment]
Currently the context menu doesn't show up when:
- just loading into a site (what has been released sometimes shows the wrong menu item #539)
- for default tabs that are not containerised #503
- for about:... urls that make no sense to be containerised

Right clicking the tab was something we just removed as the web extension APIs don't permit enough flexibility to do this and provide the correct info.

However coming in our next release:
![selection_648](https://cloud.githubusercontent.com/assets/338988/26528004/54d2ad2a-4398-11e7-8c66-af64c1c9e806.png)

As mentioned you still can't assign to a non container but we are considering this, however it will require us to have interface to manage "default".

**Comment by jonathanKingston** [comment]
I'm going to close this as I think we have added what you were asking for. Please let me know if that isn't the case.

Feel free to create or comment on other bugs too.
