### ISSUE TITLE
Implement "Edit Containers" UI

### ISSUE THREAD

**Issue by groovecoder** [mozilla/testpilot-containers#55]
![1-all panels](https://cloud.githubusercontent.com/assets/4862573/21802512/03fd8b84-d761-11e6-9c89-3825416643ae.png)

And you can find the visual spec for the panels from here:
https://www.dropbox.com/sh/jczak1kfm80q334/AAAvoNwz5lrcPZn1rreRD1E_a?dl=0

**Comment by fangshih** [comment]
@groovecoder 
I've updated the panel with more details 
Here are all the panels 
![1-all panels](https://cloud.githubusercontent.com/assets/4862573/21802512/03fd8b84-d761-11e6-9c89-3825416643ae.png)

And you can find the visual spec for the panels from here:
https://www.dropbox.com/sh/jczak1kfm80q334/AAAvoNwz5lrcPZn1rreRD1E_a?dl=0

Thanks! Let me know if you have any questions.

**Comment by groovecoder** [comment]
Cool, thanks. Updated the main description with your image and link.

**Comment by fangshih** [comment]
Hey @groovecoder, I updated the description image with one more panel view ( open a new tab ) screen. The spec has included in the same dropbox folder. Thanks!

**Comment by fangshih** [comment]
@groovecoder Just updated the icon SVG set to plain SVG
And I'll update the mock up to plain icon later on, but here are the icon assets you can use 
https://www.dropbox.com/sh/tosicjt1n19v0pb/AACYu4j7K6JBkaki0EyJqDmda?dl=0

Thanks!

**Comment by TanviHacks** [comment]
Closing this; individual issues for individual items that are still left.
