### ISSUE TITLE
Long container name for current page breaks layout

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/testpilot-containers#552]
![selection_652](https://cloud.githubusercontent.com/assets/338988/26562662/3be24b80-44c0-11e7-8a1e-fcfce3afee8a.png)

**Comment by jonathanKingston** [comment]
I have changed all the truncation we use to match how tabs are now in nightly using a fade out at the end.

This however may have side effects where not used correctly. So to test this we need to make sure any previous "ellipses" truncation works correctly. You may notice the truncation apply when the text isn't actually wrong, this is actually a bug.

I took this technique because ellipses never match in alignment.

![selection_655](https://cloud.githubusercontent.com/assets/338988/26581784/30799192-4536-11e7-8cc2-3289d1468376.png)


![selection_657](https://cloud.githubusercontent.com/assets/338988/26581712/d59a6b8e-4535-11e7-9e66-eafb3c405520.png)

This would be an example of a truncation bug (notice the Finance label is faded when it shouldn't) this happens when the element isn't full width:
![selection_658](https://cloud.githubusercontent.com/assets/338988/26581754/05acf3fa-4536-11e7-945a-f109e9fb6e70.png)


@kjozwiak FYI if you are testing this bug.

**Comment by kjozwiak** [comment]
> @kjozwiak FYI if you are testing this bug.

When is this merging into master? Or is this strickly for the Shield study?

**Comment by jonathanKingston** [comment]
@kjozwiak sorry missed this, merging into master.
