### ISSUE TITLE
Don't open shield on-boarding tab in Test Pilot mode

### ISSUE THREAD

**Issue by groovecoder** [mozilla/testpilot-containers#555]
STR:

1. Create an `.xpi` with `package.json` `name` of `testpilot-containers` (i.e., `npm run build`)
2. Install the `.xpi`

Expected results:
Add-on is installed without an on-boarding tab

Actual results:
The add-on opens the on-boarding tab that is meant only for the shield study.

**Comment by jonathanKingston** [comment]
This is resolved now @groovecoder yeah?

**Comment by groovecoder** [comment]
Oh, yeah.
