### ISSUE TITLE
Cleanup shield UI polish

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/testpilot-containers#561]
We need to make sure the current UI matches the following:
<img width="626" alt="e5391f4e-3587-11e7-814b-cc77471802b4" src="https://cloud.githubusercontent.com/assets/338988/26611735/12f0658e-45a8-11e7-8c26-a57d99645e99.png">
<img width="632" alt="151244f2-3588-11e7-9547-7a07ba24498b" src="https://cloud.githubusercontent.com/assets/338988/26611734/12efcf7a-45a8-11e7-88d5-e8d5eb4dfaaa.png">
<img width="398" alt="703d480e-3588-11e7-9472-c209fae3b6f4" src="https://cloud.githubusercontent.com/assets/338988/26611736/12f58500-45a8-11e7-87ec-3f55427a693a.png">

Current UI:
![selection_661](https://cloud.githubusercontent.com/assets/338988/26611785/76d6e15e-45a8-11e7-80fb-7d1574297db1.png)
![selection_662](https://cloud.githubusercontent.com/assets/338988/26611823/c27a8ef8-45a8-11e7-958c-470c046fbf27.png)
![selection_663](https://cloud.githubusercontent.com/assets/338988/26611838/e0db7466-45a8-11e7-9ba1-4c908a9a236e.png)

**Comment by jonathanKingston** [comment]
I'm a little lost why we still use tables, they don't appear to do anything but hinder layout and don't really add much semantic meaning either.

Notable changes:

- [ ] Delete icon doesn't always hover as the name part isn't full width
- [ ] Resizing of icons on edit screen
- [ ] Reducing container icon size on current tab panel
- [ ] Change color of icons selection
- [ ] Change selection shape for icons selection
- [ ] Remove icon and color selection indent
- [ ] Change color of heading on edit screen
- [ ] Sort tabs link isn't indented (has been fixed before, will check)
- [ ] Change alignment of current assignments

**Comment by fangshih** [comment]
After the review process, now we have the final updated screens for shield UI 
![8 0 default container](https://cloud.githubusercontent.com/assets/4862573/26669510/bcf1de08-46e0-11e7-9e52-66022a092573.png)
![8 1 2 edit current tab](https://cloud.githubusercontent.com/assets/4862573/26669513/bf415c74-46e0-11e7-9583-6c5ddcfb61d3.png)
![8 4 remove default](https://cloud.githubusercontent.com/assets/4862573/26669515/c3a4f078-46e0-11e7-9259-1c4be6d52a3e.png)
![8 5 confirmation dialogue](https://cloud.githubusercontent.com/assets/4862573/26669523/d106f716-46e0-11e7-922b-94cd0dfb794c.png)



And here are the specs
https://www.dropbox.com/sh/9pwi7xyknwko7at/AACx1jTgAqy3XtPPrBaeS5SNa?dl=0
![8-defualt container panel spec](https://cloud.githubusercontent.com/assets/4862573/26669640/3585b330-46e1-11e7-9d44-3b187195b1ec.png)

![9-confirmation page spec](https://cloud.githubusercontent.com/assets/4862573/26669536/e003b4fc-46e0-11e7-9d9a-780931c77b90.png)


Image assets
https://www.dropbox.com/sh/rifke8mef52kvrw/AADKsXH_TUE6jjpeFDL3v1Aba?dl=0


Thanks! Let me know if you need any other assets.

**Comment by jonathanKingston** [comment]
@fangshih thanks!

I'm not sure what the second panel is for labelled "Edit Current Tab Panel". The edit panel is actually "Remove Default Panel" and the assigning is actually in the first panel.

**Comment by fangshih** [comment]
@jonathanKingston Yes, you are right. I've removed that panel. It was from the older version spec. Thanks for reminding.  : )

**Comment by groovecoder** [comment]
Just ran the latest code and I can't see the button to create a new container anymore? 😢 

![image](https://user-images.githubusercontent.com/71928/27098917-ba5a79b8-503e-11e7-859a-5519dcc3d96e.png)

**Comment by jonathanKingston** [comment]
You have to click back. This was half agreed on with the changes to the
edit screen. @groovecoder were you expecting save and cancel here as
before? In a way that makes edit more confusing.

**Comment by groovecoder** [comment]
Oh yes, I was expecting Save/Cancel buttons. But if the changes take effect on the `<` click, that seems fine if we somehow indicate that? @ChenMorpheus - what do you think?

**Comment by ChenMorpheus** [comment]
@groovecoder That was discussed before. There are several reasons we decided to remove Save/Cancel:
1. All changes take effect on the < and won't cause irreversible effect, especially name/color/icon.
2. Deleting assigned sites might confuse users if we keep Save/Cancel buttons.
3. Simplify the panel since it has provided too much information 

Besides, I noticed the layout is different from the current measurement, could you update the layout to make it more intense? 
![2017-06-15 12 02 01](https://user-images.githubusercontent.com/18019946/27164858-cdcea62e-51c2-11e7-826a-08f1b821a555.png)
Measurements: https://www.dropbox.com/sh/cr4om5vcz7iachs/AACO07uR7FEWVjM7kdADV1nga?dl=0

**Comment by jonathanKingston** [comment]
@ChenMorpheus yeah agreed that tightening of the layout hasn't been completed. It might have to be post release because of timescales.

I can add a "Back and Save" title on the arrow. I suspect we will get complaints, especially on the new version however we can always refactor.

**Comment by groovecoder** [comment]
Which PR(s) finish this issue?

**Comment by jonathanKingston** [comment]
This was done in #602 sorry I missed your comment. However I'm going to file a follow up as @fangshih pointed out that we needed some tweaks to match this design.
