### ISSUE TITLE
Move tab to container

### ISSUE THREAD

**Issue by paven** [mozilla/testpilot-containers#562]
I think it would be nice to be able to add a tab to a container. 
If you might have opened it by a link or was just lazy.

**Comment by jonathanKingston** [comment]
This is a duplicate of #311. We really don't want to do this at the moment as it breaks containerisation  leaking information from one container to another.
Feel free to join the discussion on #311 though.

**Comment by jonathanKingston** [comment]
Just to follow up here, https://github.com/mozilla/testpilot-containers/wiki/Moving-between-containers is a page explaining our current thinking in one place. Still happy to take suggestions etc.
