### ISSUE TITLE
Hide container

### ISSUE THREAD

**Issue by paven** [mozilla/testpilot-containers#563]
I think it would be awesome to close, everything in a container, stash it so it easily can be opened again.
 ie. leaving/returning to work.

**Comment by jonathanKingston** [comment]
Hey,

This is already an option that we have.

Click arrow:
![selection_665](https://cloud.githubusercontent.com/assets/338988/26625028/cbf976c8-45ea-11e7-8bd4-c2630ff92d0e.png)

Click "Hide this container":
![selection_664](https://cloud.githubusercontent.com/assets/338988/26625016/bc6187c8-45ea-11e7-8af0-47ebc59d5e32.png)

You can then show using the same button later.

Let me know if this isn't what you meant or need further info.

Thanks
