### ISSUE TITLE
Need to scroll twice in container widget

### ISSUE THREAD

**Issue by falolaf** [mozilla/testpilot-containers#564]
For the moment I have 19 different containers. This implies that, in the container widget, I have scroll to see most of the containers. 
Now if I would like to e.g. open a new tab in one container in the bottom of the list I scroll down and click on the container name. After the latest update, I believe, I need to scroll twice in the container widget before the click to open a new tab is handled. What happens on the first click is that the scroll position is reset to the top. Scrolling a second time works though.

Anyone else seen this behaviour? Rather annoying. (But not a stopper...)

Windows 7
FF 53.0.3 (64 bit)
Containers Experiment 2.3.0

**Comment by jonathanKingston** [comment]
@falolaf hmm so you are expecting the previously created container to be the first item selected?

**Comment by falolaf** [comment]
Just tested with a fresh FF profile. Installed test-pilot and containsers addons. Added a number of new containers until the list needs scrolling. Same behaviour.

I believe that it is the actuall scrolling that triggers this to happen. If I only scroll oh so little and then click on the second container in the list, automatic scroll to the top of the list.

It does not happen if I drag the list with the mouse. (Just discovered that...)

**Comment by jonathanKingston** [comment]
> Is that a widget...

I knew what you meant, we use two names for these. Web extensions call them "browser actions" but the platform itself calls them "customizable widgets" ha.

No need to test, I know what you mean now. The first click is swallowed by my change to autofocus the first element... this is a total bug. Sorry.

**Comment by falolaf** [comment]
Brilliant @jonathanKingston !

(Maybe we should come up with a third name, just for the fun of it... :-)

**Comment by jonathanKingston** [comment]
@falolaf well they are also a toolbarbutton widget they also have badged-button as a class, I guess naming things is hard hah.

This will be fixed in the latest update, the issue was the first focus from a keyboard should really select the first item in the list so I caused some other issues for mouse users.
