### ISSUE TITLE
TypeError: browser.contextualIdentities is undefined when trying to open containers popup

### ISSUE THREAD

**Issue by yhager** [mozilla/testpilot-containers#570]
Using firefox-esr (52.1.0) on debian jessie, I can't open the container management popup. Hovering over the icon, I get the following message in the console:
```
TypeError: browser.contextualIdentities is undefined
```

I have privacy.userContext.enabled:True.

It seems that all the rest of the functionality works well - I can use containers, only I can't add or modify the default ones.

**Comment by jonathanKingston** [comment]
@yhager ah 52 will no longer be supported unfortunately as part of the migration to remove legacy code we now need this API. I'm pretty shocked it is working as well as it is unfortunately.

I would suggest downloading stable Firefox or another build for now. The next ESR should be fine for all the APIs we use. I'm really sorry this is a pain.

You can enable that pref in ESR and get the cut down version of Firefox containers instead not part of this experiment. Long press for adding containers and a different container drawer.

@groovecoder we can exclude this version from the manifest, do you know if we can do the same on Test pilot too?

**Comment by jonathanKingston** [comment]
Just to be clear, I think supporting ESR is out of scope of this extension. Maintaining legacy code to keep this working will likely cause many issues in us shipping this to the next ESR release 57 which removes the other interfaces for SDK code and only has web extensions. I would normally suggest we could work on shims or backports here but as we are only an experiment I don't think it is worth our limited resource.

Sorry about this.

**Comment by yhager** [comment]
Thanks for the quick response. I didn't realize esr-52 is not supported. The README.md for this repo specifies firefox 51+ as a requirement - you might want to update that.

But that's fine. I see that the new debian will be released in a couple of weeks, so I'll other wait and install 53 from the repos, or download the tarball directly.

Thanks guys! I love containers! It's an essential feature IMHO.

**Comment by jonathanKingston** [comment]
@yhager good catch about the README, that was the initial version we were supporting yeah however we have been utilising more and more of the new Web Extension APIs.

Gonna close of the bug, please let me know if you need any more support etc :).

**Comment by jimdigriz** [comment]
...maybe pushing the update to unsupported users is the real problem here?

I understand how developers love writing code, refactoring, using the latest and bestest, etc etc but it tends to be considered polite to not knowingly break everyones browsing experience.

So maybe before you jump into another wild and exciting day of refactoring, maybe put some minor effort to flag some constraints on the update so that only supported browsers receive the updates in future?

**Comment by jonathanKingston** [comment]
I think it is probably fair to say we shouldn't have ever allowed 57 to work in the first place.

We are trying to remove **all** SDK code before Firefox 57, any of this code will break releasing then. So all of this code needs to be removed and replaced to keep us working. This isn't a small job to keep the extension going.

I also don't think we have the flexibility with Test Pilot to isolate older users and breakage. Certainly how we have our automated build right now doesn't work like this. (cc @groovecoder)

Keeping stability for ESR is certainly not possible with the timescales of 57, we work very hard in keeping stability across all other releases. Test pilot experiments are expected to be a little more shaky than our normal code in platform and we try and fix things as quick as possible.

> jump into another wild and exciting day of refactoring

I think you might be having different refactoring experiences here
