### ISSUE TITLE
"Cancel/OK" button missing/removed when creating new Containers

### ISSUE THREAD

**Issue by kjozwiak** [mozilla/testpilot-containers#578]
When creating new containers with the latest version from master, I noticed that the "OK" and "Cancel" buttons have been removed form the "Create" panel.. Example:

<img width="309" alt="screen shot 2017-06-13 at 8 41 05 pm" src="https://user-images.githubusercontent.com/2602313/27110652-d6820072-5078-11e7-8f44-545afcaa6b28.png">

I'm not sure if this is a bug or as per the new spec, but it might confuse users who accidently click on the "+" button and decide not to create any new containers. Currently, the only way to cancel the creation is pressing the "ESC" key.

Pressing the "<" button on the side of the panel to create the container isn't very intuitive either.

@jonathanKingston, thoughts? Was this per the new design spec for the shield study?

**Comment by jonathanKingston** [comment]
@kjozwiak this was indeed an artefact pf changing the edit panel as mentioned on the PR itself.

I'm not sure if adding these buttons just for the new screen and not for edit also makes sense either.

I agree it is however confusing I should have mentioned it in the meeting with @johngruen

**Comment by kjozwiak** [comment]
@jonathanKingston we can mention it in today's meeting and see what @johngruen thinks... I don't really mind the "Cancel" case, but I think not having a "OK" button will definitely confuse poeple. I'm not sure that people will understand that the "<" button also means "Save". Not at the beginning at least.

**Comment by johngruen** [comment]
Would prefer current UI; Having an explicit 'OK' button sould help users better understand how to navigate an unfamiliar UI.

**Comment by jonathanKingston** [comment]
@johngruen but we don't really have the space on the edit screen. Is that an issue if they are different?

**Comment by johngruen** [comment]
let's talk in a minute!

**Comment by jonathanKingston** [comment]
I think we decided to close this right @johngruen

**Comment by jonathanKingston** [comment]
This is solved in my latest PR @groovecoder
