### ISSUE TITLE
ERROR - ContextualIdentityService - Unknown version found in .../containers.json

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot-containers#58]
Running this locally w/ Nightly, and saw this show up in my iTerm terminal output:

> ERROR - ContextualIdentityService - Unknown version found in /var/folders/qc/g_f0szh95k1fzph34rhmf5jw0000gp/T/b45b3b02-d19d-4fb4-b019-568e00473122/containers.json

And here's a dump of my containers.json:

```json
$ cat /var/folders/qc/g_f0szh95k1fzph34rhmf5jw0000gp/T/b45b3b02-d19d-4fb4-b019-568e00473122/containers.json | JSON
{
  "version": 2,
  "lastUserContextId": 5,
  "identities": [
    {
      "userContextId": 1,
      "public": true,
      "icon": "fingerprint",
      "color": "blue",
      "l10nID": "userContextPersonal.label",
      "accessKey": "userContextPersonal.accesskey",
      "telemetryId": 1
    },
    {
      "userContextId": 2,
      "public": true,
      "icon": "briefcase",
      "color": "orange",
      "l10nID": "userContextWork.label",
      "accessKey": "userContextWork.accesskey",
      "telemetryId": 2
    },
    {
      "userContextId": 3,
      "public": true,
      "icon": "dollar",
      "color": "green",
      "l10nID": "userContextBanking.label",
      "accessKey": "userContextBanking.accesskey",
      "telemetryId": 3
    },
    {
      "userContextId": 4,
      "public": true,
      "icon": "cart",
      "color": "pink",
      "l10nID": "userContextShopping.label",
      "accessKey": "userContextShopping.accesskey",
      "telemetryId": 4
    },
    {
      "userContextId": 5,
      "public": false,
      "icon": "",
      "color": "",
      "name": "userContextIdInternal.thumbnail",
      "accessKey": ""
    }
  ]
}
```

Not sure what's up with the pseudo-empty `"userContextId": 5` at the end, or if that's the culprit.

![jeff_sessions__a_lifelong_outsider__finds_the_inside_track_-_the_new_york_times](https://cloud.githubusercontent.com/assets/557895/21789174/f3455864-d687-11e6-8764-4db246e3444e.png)

![blank_skitch_document](https://cloud.githubusercontent.com/assets/557895/21789156/d07030ca-d687-11e6-9985-e85a26d7e351.png)

**Comment by bakulf** [comment]
This happens when you use a profile directory created by FF 52, with FF 51.
Nightly has version 2 of containers.json, but beta (FF51) has version 1.
Just delete that file and everything will be fine. I don't think we need to do anything here.
FF doesn't support the downgrading of version.
