### ISSUE TITLE
Removing assigned containers via the "Edit Containers" panel doesn't work

### ISSUE THREAD

**Issue by kjozwiak** [mozilla/testpilot-containers#580]
Removing assigned websites via the `Edit Containers` panel doesn't work. Assigned websites are still opening in their previously assigned containers even though they've been deleted from the `Sites assigned to this container` list.

Example: [https://youtu.be/7SP0KtY6D_I](https://youtu.be/7SP0KtY6D_I)

You'll also receive the following error in the browser console when removing an assigned site from the `Sites assigned to this container` list under` Edit Containers`.

`Error: Could not establish connection. Receiving end does not exist.  undefined`

STR:

* Using fc789a49ace686ed8e748aa660b168f7f4aaf747, build a new XPI and install it via nightly
* once installed, open a `Personal` container and load eff.org
* right click on eff.org and select `Always Open in This Container`
* open a new default container and close the personal container you've opened earlier
* click on the `Container` button under the toolbar and select `Edit Containers`
* click the edit (pencil) button next to the `Personal` container
* remove eff.org from the `Sites assigned to this container`
* you'll get the `Successfully removed site to always open in this container` notification (sometimes you won't even get a notification as demonstrated via the video example)
* load eff.com and you'll notice it's still attempting to load the website within the `Personal` container

**Comment by jonathanKingston** [comment]
Yeah looks like this was me borking a merge.
