### ISSUE TITLE
Configure plugin settings per container

### ISSUE THREAD

**Issue by yoasif** [mozilla/testpilot-containers#585]
This would be a great way to have plugins like Flash installed but only used in places that absolutely need it. 

It would also help reduce the attack surface for plugins, since they are only exposed when within specific containers.

**Comment by jonathanKingston** [comment]
This certainly has been asked for however I can't find a duplicate.

The following bug of isolating flash storage is a dependency to implementing this:
https://bugzilla.mozilla.org/show_bug.cgi?id=1285677

**Comment by jonathanKingston** [comment]
This is out of scope for our experiment though, I think tracking the flash bug is likely your best bet.

**Comment by jonathanKingston** [comment]
Also related to #309
