### ISSUE TITLE
Telemetry reliability

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/testpilot-containers#588]
We should check how reliable telemetry is @groovecoder.

We close extension pages when sending telemetry rather than waiting for promises to finish.

**Comment by kjozwiak** [comment]
@jonathanKingston, @groovecoder, could we add some of those test cases into the [test plan](https://wiki.mozilla.org/QA/ContainersTestPilot)? We can add a section for the Shield Study/Telemetry.

Let me know if there's anything that I can help with.

**Comment by jonathanKingston** [comment]
STR:

1. Create a personal tab
2. Go to mozilla.org
3. Right click and add to "Always open in this container"
4. Open a new default tab
5. Go to mozilla.org
6. Click "open in current container"

about:telemetry should contain `click-to-reload-page-in-same-container`

7. Go to mozilla.org
8. Click "open in Personal container"

about:telemetry should contain `click-to-reload-page-in-container`

9. Open a work tab
10. Go to mozilla.org
11. Click "open in Personal container"

about:telemetry should contain another `click-to-reload-page-in-container`

10. Open a work tab
11. Go to mozilla.org
12. Click "open in Work container"

about:telemetry should contain another `click-to-reload-page-in-same-container`

**Comment by jonathanKingston** [comment]
I think the above is correct however not tested it, perhaps it might need editing a little in wording or whatever.

The idea is that the changing the tab might make these super unreliable. I added a case for default tabs too even thought he code path is similar.

**Comment by jonathanKingston** [comment]
To check the telemetry I was:

1. Visiting about:telemetry
2. Clicking "Archived ping data"
3. In the ping dropdown clicking the most recent item with "testpilottest" in the option.
   Closing and opening tabs should also send "page-requests-completed-per-tab" events, clicking "Older ping" should find other events that happened too.
4. Check "Raw Payload" section for events

**Comment by jonathanKingston** [comment]
Question:
- "page-requests-completed-per-tab" fires in tabs that have the prompt showing, would this skew the results?
- "totalContainersCount" shouldn't this be all the containers they have? I am getting the same number as "shownContainersCount" 2 rather than 4 "work", "personal", "shopping", "finance".
- "page-requests-completed-per-tab" sometimes contains "firefox-default" when I wasn't even using it? Background requests?
- "pageRequestCount": 0, appears to be all my "page-requests-completed-per-tab" telemetry has?!

**Comment by jonathanKingston** [comment]
It looks like the metric doc doesn't account for "alltabs-menu" source.

**Comment by jonathanKingston** [comment]
To answer my initial question anyway... I think closing the tab immediately doesn't seem to impact sending these.

**Comment by groovecoder** [comment]
> 
>     "page-requests-completed-per-tab" fires in tabs that have the prompt showing, would this skew the results? From my testing the first pageload is 0 even after clicking through the screen.

We have `and         pagerequestcount > 0` in the query to filter these out.

>     "totalContainersCount" shouldn't this be all the containers they have? I am getting the same number as "shownContainersCount" 2 rather than 4 "work", "personal", "shopping", "finance".
>         I'm not sure if I broke this however it actually appears to match what the metrics doc states Hidden+shown. When I requested this I expected it to be Hidden+Shown+NotUsed

It's a bad field name. It's really total container *tabs* count.

**Comment by groovecoder** [comment]
> It looks like the metric doc doesn't account for "alltabs-menu" source.

Good catch. We are getting it in the reports, so we should update `metrics.md` to reflect it ...

![image](https://user-images.githubusercontent.com/71928/27192057-861319bc-51bf-11e7-84ba-0decd2e0ff4c.png)

**Comment by jonathanKingston** [comment]
> It's a bad field name. It's really total container tabs count.

Hmm really? I thought that was "totalContainerTabsCount"? Looking at the code it's the number of containers that have 1 or more tab that is either hidden or shown.

**Comment by jonathanKingston** [comment]
Sweet I'm less paranoid now I understand this. Happy for this to be closed when @kjozwiak is happy.

**Comment by groovecoder** [comment]
I'm going to leave this open to remind me to verify the `@shield-study-containers` pings are making it all the way to the new `containers_shield` table.

**Comment by groovecoder** [comment]
I was able to see the new shield study pings via `select * from containers_shield where test = '@shield-study-containers' limit 100` so we should be able to re-create the test pilot dashboard queries for the shield study too.
