### ISSUE TITLE
View source not working

### ISSUE THREAD

**Issue by Alex-Dcat** [mozilla/testpilot-containers#594]
Displays the source code for a window without a container.

**Comment by jonathanKingston** [comment]
Duplicate of: #345 which is a duplicate of the platform bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1347604

**Comment by jonathanKingston** [comment]
This looks like it is fixed in everything but stable also, so should work soon :). Thank you for the report though.

**Comment by Alex-Dcat** [comment]
Not fixed in 53.0.3 and 54. Fixed in 55.0b1. But the tab view-source: does not contain the color line of the container.

**Comment by ftzdomino** [comment]
I'm experiencing this in 59.0.2.  On any site in a container requiring authentication viewing the source appears to open in a different container and show me a login page.
