### ISSUE TITLE
compatibility issue with "tab center"

### ISSUE THREAD

**Issue by dehsar** [mozilla/testpilot-containers#596]
when "tab center" is enabled, switching to "tabs to the top", does not give user the "containers" when opening new tabs (screen shot is attached).

<img width="1178" alt="screen shot 2017-06-15 at 6 49 09 pm" src="https://user-images.githubusercontent.com/24737514/27208697-133fe0cc-51fc-11e7-91dd-12510b0838cc.png">

**Comment by jonathanKingston** [comment]
This is a duplicate to: #229 
Thank you for your report!
