### ISSUE TITLE
Finalize Naming for Test Pilot Experiment

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot-containers#6]
Are we calling this thing containers, spaces, something else?

**Comment by groovecoder** [comment]
Personas, obviously. :trollface:

**Comment by TanviHacks** [comment]
Contexts?

@johngruen maybe you can ask if anyone from the product team has ideas?

**Comment by groovecoder** [comment]
99.9% sure we're set on "Containers". Re-open or just change if that's not the case.
