### ISSUE TITLE
Bottom of the panel has white gap below the buttons

### ISSUE THREAD

**Issue by Keith94** [mozilla/testpilot-containers#600]
![image](https://user-images.githubusercontent.com/5490615/27258069-daa673e8-53a4-11e7-8fac-e31504ec89a1.png)

**Comment by jonathanKingston** [comment]
This is a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1370083 which is an issue in Nightly rather than the experiment itself.

Thanks for raising
