### ISSUE TITLE
Containers Menu does not open

### ISSUE THREAD

**Issue by HyperCriSiS** [mozilla/testpilot-containers#604]
Hi,

Containers Menu does not open. I use Cyberfox 52.2.0.
![ff_containers](https://user-images.githubusercontent.com/11708192/27334306-2d0d2886-55c9-11e7-9020-058f2825052a.png)

Regards,
Hyper

**Comment by jonathanKingston** [comment]
I have never used this but I would suggest it could be addon compatibility.

Are you able to open browser toolbox to get any debug? What do you have when you load about:support?

I would rather not install software I just learned about. @kjozwiak have you heard of this variant before?

**Comment by kjozwiak** [comment]
> I would rather not install software I just learned about. @kjozwiak have you heard of this variant before?

Nope, I've never heard of it either.. I downloaded the x64 version and installed it on a Win 10 x64 VM. It looks like it's using fx52.2.0 as the base with several other things added into the package such as custom search engines and optimizations for specific processors.

Either way, clicking the `Container` icon under the toolbar produces the following error message in the browser console:

```
TypeError: browser.contextualIdentities is undefined[Learn More]  popup.js:126:7
	refreshIdentities moz-extension://ca8b1216-bd47-4120-b4c6-c77629fbb145/js/popup.js:126:7
	init moz-extension://ca8b1216-bd47-4120-b4c6-c77629fbb145/js/popup.js:78:5
	<anonymous> moz-extension://ca8b1216-bd47-4120-b4c6-c77629fbb145/js/popup.js:761:1
```

It looks like most of the container features are generally working, but I'm not really sure if there's anything we can do here as this is a fork and not supported by Mozilla.

@HyperCriSiS, perhaps you can create a bug [here](https://cyberfox.8pecxstudios.com/file-a-bug/).

@jonathanKingston, we can probably close this off... Thoughts?

**Comment by HyperCriSiS** [comment]
I wonder that you never heard of it :) It is the most famous FF fork.
Anyway I moved away now to the Standard FF version as Cyberfox will unfortunatly not longer be active developed.
I will report again if I have issues with the standard FF.

**Comment by kjozwiak** [comment]
Thanks @HyperCriSiS.... As per the above comment, closing this.
