### ISSUE TITLE
Checkbox for "Remember my decision for this site" is not in line with the text

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/testpilot-containers#607]
**[Affected versions]:**
- Firefox 54
- Containers Experiment Build: 2.3.0

**[Affected Platforms]:**
- All Windows
- All Linux
- All Mac

**[Prerequisites]:**
- Containers Experiment is installed on a new browser profile.
- A webpage (www.reddit.com) is saved in a custom container.

**[Steps to reproduce]:**
1. Start the browser with the profile from prerequisites and open a normal New Tab.
2. Write the name of the saved webpage amd press "Enter".
3. Observe the "Remember my decision for this site" area

**[Expected results]:**
- The text "Remember my decision for this site" is in line with the checkbox.

**[Actual results]:**
- The checkbox is positioned slightly upper than the text.

**[Notes]:**
- Attached a screenshot of the issue:
![checkbox is not in line with the text](https://user-images.githubusercontent.com/9248513/27382937-87891e5a-5691-11e7-98e9-3dea73275caa.jpg)

**Comment by kjozwiak** [comment]
Minor UI issue but we should get this fixed before launching the shield study as the `Always Open in This Container` feature is pretty integral to the container experience.

Reproducible on the latest fx54, fx55.0b4 and fx56.0a1 builds.

@jonathanKingston, mind taking a look? Should be trivial to fix.

**Comment by Softvision-VladBacia** [comment]
This issue was verified on Firefox latest release v54.0 with Containers Experiment v2.4.0 and it cannot be reproduced. Thus, marking this issue as Verified-Fixed.
