### ISSUE TITLE
The green "New" badge changes its colour to red in new opened windows

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot-containers#608]
[Affected versions]:
- Firefox 54.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Install the latest Containers version on a new clean profile.
2. Observe the Container icon from browser toolbar.
3. Open a new window (Ctrl+N).
4. Observe the Container icon from browser toolbar.

[Expected result]:
Step 2 & Step 4. The Container icon has a green "New" badge on it.

[Actual results]:
Step 2. The Container icon has a green "New" badge on it.
Step 4. The Container icon has a red "New" badge on it.

[Notes]:
- Here is a screen recording with the issue:
![red badge](https://user-images.githubusercontent.com/19226534/27385935-daf73b0c-569c-11e7-8db0-6aef4d55d7ef.gif)

**Comment by SoftVision-CarmenFat** [comment]
I am able to reproduce this issue by following a different scenario:

STR:
1. Install the latest Containers version on a new clean profile.
2. Resize the Firefox window until overflow button is displayed in the toolbar.
3. Maximize the Firefox window.

The Container icon has a red "New" badge on it.

**Comment by kjozwiak** [comment]
This is pretty easy to reproduce and I'm assuming really easy to fix. There's a few issues that we definitely need to fix before launching the shield study so we might as well get this fixed as it shouldn't take that much effort.

@jonathanKingston, thoughts?

**Comment by jonathanKingston** [comment]
Not 100% on how this is implemented it might be the default colour. It might actually be a web-ext issue.

Will check tomorrow.

**Comment by kjozwiak** [comment]
I've managed to reproduce this using the latest version [1] of the containers experiment that's available to the public via the test pilot page. It appears this was introduced when we added the `New` button in 2.3.0, so it's not a new regression.

[1] containers_experiment-2.3.0-fx.xpi

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue on latest Firefox (54.0.1) release and it still reproducible for the following scenarios:
- When a new window is opened, the green "New" badge flashes red then is correctly changed back into the green color. This behavior is not reproducible on latest Nightly build.
- The described behevior by Carmen, is still reproducible. If you resize the browser until the button is not displayed, then when maximize the browser you can observe that green color changes in a red color. If you focus another tab the green color is correctly re-displayed.
- If you open the "Customize" page, then the green "New" badge changes its color in red. Again, if you focus another tab the green clolor is correctly re-displayed.

Here is a screen recording with all the described scenarios:
![badge color](https://user-images.githubusercontent.com/19226534/27480747-fd81295e-5821-11e7-9a86-d81619d80216.gif)
