### ISSUE TITLE
Disabling Containers from about:addons wrongly removes the add-on 

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/testpilot-containers#614]
[Affected versions]:
- Firefox 54.0.1 and up
- Containers 2.3.0 

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Containers add-on was previously installed on a clean profile.

[Steps to reproduce]:
1. Go to about:addons->Extensions tab.
2. Click the Disable button for the Containers add-on.
3. Observe the behavior.

[Expected result]:
- The add-on is disabled.

[Actual result]:
- The add-on is removed.

[Notes]:
- Attached a screen recording of the issue:
![disable removes the add-on](https://user-images.githubusercontent.com/18304511/27391874-c395fff0-56ad-11e7-9993-d41c7e497028.gif)

**Comment by kjozwiak** [comment]
This is happening on both `@testpilot-containers` and `@shield-study-containers` using 13cd601212dfa76c957a9f2c3cea91799e4ce644:

```
kjozwiak:testpilot-containers kjozwiak$ git log -1
commit 13cd601212dfa76c957a9f2c3cea91799e4ce644 (HEAD -> master, origin/master, origin/HEAD)
Merge: 6533c74 bc847b5
Author: luke crouch <luke.crouch@gmail.com>
Date:   Tue Jun 20 10:18:46 2017 -0500

    Merge pull request #602 from jonathanKingston/edit-restyle
    
    Edit restyle
```

Currently not reproducible using `containers_experiment-2.3.0-fx.xpi` which was retrieved from the [test pilot](https://testpilot.firefox.com/) page so this is definitely a regression that was introduced this version.

I'm not sure how this issue might affect the removal of the shield study once it's complete.

**Comment by groovecoder** [comment]
Pretty sure this is caused by the shield study library code. I'll dig into it.

**Comment by groovecoder** [comment]
Okay, we can fix this for the `@testpilot-containers` version, but the shield library is hard-coded to un-install the add-on completely when the user disables it.

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the Test Pilot version of containers. 
I've also verified that disabling still removes the add-on on the Shield version of containers.
Marking as verified.
