### ISSUE TITLE
'Plus' icon missing from the assets?

### ISSUE THREAD

**Issue by bakulf** [mozilla/testpilot-containers#62]
container-add.svg is different than what invisionapp shows: it should be a gray circle with a the '+' in the center.

**Comment by fangshih** [comment]
Here are the container add icon
https://www.dropbox.com/s/eochj7tebefdr3d/container-newtab.svg?dl=0
Thanks

**Comment by fangshih** [comment]
You can also find the spec here: https://www.dropbox.com/sh/jczak1kfm80q334/AAAvoNwz5lrcPZn1rreRD1E_a?dl=0
![3-open new tab](https://cloud.githubusercontent.com/assets/4862573/21835344/379f725e-d7f7-11e6-89bf-481e8d1b22e0.png)

**Comment by bakulf** [comment]
jkt, can you take this bug?

**Comment by johngruen** [comment]
Poking @fangshih

**Comment by TanviHacks** [comment]
I think it is here https://www.dropbox.com/sh/dy8fupo92slp7kd/AADWHRqfqN6sfKqJ4k22NPv-a?dl=0

**Comment by TanviHacks** [comment]
Leaving open for Jonathan to replace icon in addon with the asset provided.
