### ISSUE TITLE
If you refresh the page after assigning it to a container, "Containers confirm navigation" page is wrongly opened in a new tab

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot-containers#626]
[Affected versions]:
- Firefox 54.0.1 and up	
- Containers 2.3.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the latest Containers (2.3.0) version installed on a new Firefox profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to a website in a container tab (eg: Persoanl). 
2. Click the Containers icon from browser toolbar.
3. Choose the "Always open in this container" option.
4. Refresh the page and observe the behavior.

[Expected result]:
- The page is correctly refreshed.

[Actual result]:
- The page is refreshed and a "Containers confirm navigation" page is opened in a new tab. 

[Notes]:
- This issue is not reproducible if the "Always open in this container" option is set from context menu.
- This is reproducible at every refresh, until the tab is closed.
- Here is a screen recording with the issue: 
![a new tab is opened](https://user-images.githubusercontent.com/19226534/27438646-9dbc32c4-576e-11e7-831e-a86063e70cbf.gif)

**Comment by jonathanKingston** [comment]
Let me check if this is still an issue after the latest fixes.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue using the latest Firefox (54.0.1) release with Containers Experiment v2.4.0 and is no longer reproducible. Marking as verified.
