### ISSUE TITLE
"Always Open in This Container" notification is displayed differently for some websites

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/testpilot-containers#630]
[Affected versions]:
- Firefox 54.0 and up
- Containers Experiment Build: 2.3.0

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Containers Experiment is installed on a new browser profile.

[Steps to reproduce]:
1. Start Firefox with the profile from prerequisites.
2. Open a new tab in a container (e.g. "Personal") and navigate to www.twitch.tv
3. Right click on the page's content.
4. Click on "Always Open in This Container" and observe the notification under the URL bar.
5. Follow steps 2-4 using the following websites:
- https://giphy.com
- https://soundcloud.com
- https://vimeo.com
- https://www.reddit.com
- https://www.britannica.com

[Expected results]:
- The text from the notification has the same font size, format and alignment for all websites.

[Actual results]:
- The text from the notification has different font size, format and alignment depending on the website.

[Notes]:
- Please see the following screenshot of the issue:

![fgaeg](https://user-images.githubusercontent.com/26000308/27440044-36140eea-5772-11e7-9f9a-879f93a4ef83.png)

**Comment by jonathanKingston** [comment]
I expected this might happen, thanks for the example URLs.

**Comment by SoftVision-CarmenFat** [comment]
This issue was verified on Firefox latest release v54.0 with Containers Experiment v2.4.0 and it cannot be reproduced anymore. The text from the notification has the same font size, format and alignment for all tested websites.
