### ISSUE TITLE
Get link for download conversion on AMO page

### ISSUE THREAD

**Issue by groovecoder** [mozilla/testpilot-containers#649]
Talk to folks in #analytics for advice on getting the conversion rate from GA>

**Comment by groovecoder** [comment]
Pinged Gareth.

**Comment by garethcull** [comment]
@groovecoder 

Here's a summary dashboard of AMO website metrics. If you need it filtered down to a specific page, that is pretty easy to add in. Let me know.
https://datastudio.google.com/open/0B6voOaUZL-jwMEVDVE9qQmlFeVk

Happy to walk you through it sometime next week if you want to put some time on my calendar. Thanks.

**Comment by groovecoder** [comment]
1 link here: https://analytics.google.com/analytics/web/?authuser=1#report/visitors-browser/a36116321w65861930p67693596/%3F_.useg%3Duser2UfIJu8ASXquJd7dCx-2Nw%26explorer-table.plotKeys%3D%5B%5D%26_r.drilldown%3Danalytics.browser%3AFirefox%26explorer-graphOptions.compareConcept%3Danalytics.goalConversionRate/

**Comment by groovecoder** [comment]
I added a new goal for AMO specifically for tracking Containers Add-on installs. It's available at the GA report for conversions on AMO:

https://analytics.google.com/analytics/web/?authuser=0#report/conversions-goals-overview/a36116321w65861930p67693596/%3Foverview_goaloption_ALL-graphOptions.primaryConcept%3Danalytics.goal4Completions/
