### ISSUE TITLE
Containers icon does not adjust color for overflow menu

### ISSUE THREAD

**Issue by MikkCZ** [mozilla/testpilot-containers#653]
Using the nightly, Containers toolbar icon adjusts its color for compact dark theme and become white. But the overflow menu is always light, so in the overflow menu the icon color should stay the same as for the default theme. Currently it's white and impossible to see. Not sure, how this can be done in an add-on, but the Firefox built-in tools icons like Bookmark do it.

**Comment by MikkCZ** [comment]
Similar issue in Firefox Screenshots. https://github.com/mozilla-services/screenshots/issues/3078

**Comment by jonathanKingston** [comment]
Closing in favour of: https://github.com/mozilla/testpilot-containers/issues/603
The overflow menu has it's own set of issues too which are unlikely to be addressed soon.
