### ISSUE TITLE
Add Feature: Change container of open tab

### ISSUE THREAD

**Issue by UncleNachoDuh** [mozilla/testpilot-containers#661]
It would be useful to be able to change the container that a tab belongs to after I have already opened it. I notice this most with tabs that do not belong to a container

**Comment by jonathanKingston** [comment]
Hi thanks for the report.

As per the resolution here:
https://github.com/mozilla/testpilot-containers/issues/311#issuecomment-306491003

>> I'm not quite sure why this is such a large hurdle.
>
>Because the web has many features which makes this hard like `window.opener` this would also indeed break OAuth as previously mentioned. If you wanted opener to work across containers it is a privacy issue.
>
>> Well, to me automatic change-on-navigation and manually changing are more or less the same thing, at least as far as the underlying machinery needed is concerned.
>
> If both of these allow back and forward to work yes they are the same. Again this is out of scope and we should be talking on the Bugzilla bug to discuss this being added to the platform.
>
> The original bug here is about just doing exactly what [Context Plus](https://addons.mozilla.org/nn-no/firefox/addon/context-plus/) does and nothing to do with keeping the tab within the same window.
>
> The window change requires a lot more security checking etc that will require additional work, I'm going to update the Bugzilla bug to explain this situation further. This indeed would help with the friction of assignment however it isn't as easy to implement as it seems and probably still a P5 that I can see.
>
> I'm going to close this as I don't think we will ever be implementing this here users not wanting the privacy benefits can use Context Plus. Users wanting clean back and forward and cleaner assignment functionality can wait for the platform [Bugzilla change](https://bugzilla.mozilla.org/show_bug.cgi?id=1323873).


Essentially by changing the tab you will lose the privacy advantages to containers, there is an extension listed above which allows you to do this however we don't have any plans to support this natively.

Thanks
