### ISSUE TITLE
Add Feature: Ability to clean all local storage for given container

### ISSUE THREAD

**Issue by dorfsmay** [mozilla/testpilot-containers#662]
I currently use Firefox profiles to test applications so that I can sign in as different users, cleanup cookies (to test and retest signin behaviour for example) etc...

I have started using Firefox containers instead, and a simple way to clean up all the local storage (cookies etc...) for a given container, is preventing me to completely switch to containers.

**Comment by jonathanKingston** [comment]
Hey,
Yeah we have a few requests for this, this hinges on getting new Web Extension APIs so that we can clear these.
This likely is a duplicate of another bug though. It's probably worth closing this and tracking issue #48 

Thanks
