### ISSUE TITLE
No way to change settings if you asked Firefox to always open a site in a type of container.

### ISSUE THREAD

**Issue by dorfsmay** [mozilla/testpilot-containers#663]
If you asked Firefox to always open a site in a type of container, there seems to be no way to change that setting. When opening a tab for that site, you get the question:

"You asked Firefox to always open www.example.com in this type of container. Would you like to proceed?"

But there is no obvious way to open it in a different type of tab, or change that setting.

**Comment by jonathanKingston** [comment]
Hey,

If you click ok to that prompt and right click again you can remove the assignment in the same way you added it.

Hopefully next week we will be pushing our update which shows a tick box for the assignment in the browser action (when you click on the containers button). Editing the container will also have a delete button for each website too.

Closing as we have improvements in the pipeline and it's also possible.
