### ISSUE TITLE
Unreadable on dark GTK theme

### ISSUE THREAD

**Issue by toastal** [mozilla/testpilot-containers#677]
Could you at least make the background of this extension popup white? I can't read it as is. It's grey on grey. Or, if, possible, just use the default colors provided by the OS so I can see light text on dark.

**Comment by jonathanKingston** [comment]
Hey @toastal do you mind provinding a screenshot please?
Thank you!

**Comment by toastal** [comment]
![2017-07-14-170726_3200x1800_scrot](https://user-images.githubusercontent.com/561087/28233844-0f62216e-68b7-11e7-99e1-c10a495881ad.jpg)

**Comment by ArchangeGabriel** [comment]
Similar report here: https://github.com/horst3180/arc-firefox-theme/issues/126

**Comment by jonathanKingston** [comment]
Yeah I bet changing panel colour breaks loads of things. Either way that latest commit should fix this.

**Comment by jecogeo** [comment]
Is it fixed? I'm using Firefox 58.0.2 (64-bit) in Majaro linux system and I'm experiencing this issue.
