### ISSUE TITLE
Adobe flash plug-in crashes and game graphic issues

### ISSUE THREAD

**Issue by simoncatwell** [mozilla/testpilot-containers#680]
When I load more that 5 containers with separate fb accounts, adobe flash plug-in crashes in all of them after a short period of time.  Also game graphics load in stages for one graphic (one section of it loads and the other part loads a few seconds later)
![container 1 adobe flash plugin crash](https://user-images.githubusercontent.com/30215195/28250331-4496905c-6a2b-11e7-95b2-aa3e8d027cbf.jpg)
![container 2 adobe flash plugin crash](https://user-images.githubusercontent.com/30215195/28250332-449aeeea-6a2b-11e7-8032-38fbffd585f9.png)

I thought this is supposed to be a multi- account login browser like the multi-fox extension but it's not working nearly as well.

**Comment by jonathanKingston** [comment]
Flash cookies are not isolated, which may be the reason you are seeing this issue. As flash is going in the direction of deprecation I don't think it makes sense investigating this issue. (I'm not sure on the timescale of deprecation however we have known containers don't isolate on flash storage for a long time and haven't decided to make it a priority for a while). If you want to track the bug that is part of the platform see: https://bugzilla.mozilla.org/show_bug.cgi?id=1285677 I'm not entierely sure how multi-fox worked however being a legacy addon it would have been impacting multi process performance, containers are still going to work in 57.

However flash is known to crash like this and there is only one instance for the whole browser. It might just be this version of flash that is the issue.

If this game were HTML5 they would be truely isolated.

**Comment by simoncatwell** [comment]
I wanted to test this browser for the game that I play using multiple
accounts.  The issues were the frequent flash crashes across all of the
containers at the same time and the game graphics not displaying properly
and lagging no matter if I was using multiple containers or just one.

The game requires the latest version of adobe flash, which is installed, so
I guess Firefox Nightly/containers won't be for me.  It has so many great
features though and I hoped it would work for my purposes.  I'm going back
to the older version of waterfox that still works with the multi-fox
extension...which is set up with containers as well and works just fine.
Unfortunately you can only use one version of firefox at a time so I'm
going to have to uninstall the test browser.  I would keep it if I
could...I really like it.

It's just hard to believe this isn't a bigger problem than it is except
maybe other games don't require the use of adobe flash.  I'm hoping this
game discontinues using it as well so I can continue on with the test
version.

Thank you for taking the time to respond to my issue though.   I appreciate
it.

On Mon, Jul 17, 2017 at 9:22 AM, Jonathan Kingston <notifications@github.com
