### ISSUE TITLE
Containers doesn't work on my GNU/Linux (OpenSuSE Tumbleweed) desktop

### ISSUE THREAD

**Issue by nintyfan** [mozilla/testpilot-containers#683]
Like in title. When I click on containers button, empty panel is displayed.
https://user-images.githubusercontent.com/28184387/28330901-8ce172c6-6bef-11e7-93c1-79a5c27428cd.png

**Comment by jonathanKingston** [comment]
Are you using Firefox 52?

**Comment by nintyfan** [comment]
Yes.

**Comment by jonathanKingston** [comment]
This is a duplicate of the issues listed in #686 we stopped support for ESR. That issue is worth following for a migration plan (you can enable platform containers instead) and we might consider shipping a ESR only fix.
