### ISSUE TITLE
Create content for AMO page

### ISSUE THREAD

**Issue by groovecoder** [mozilla/testpilot-containers#684]
* [x] "About this Add-on" content
* [x] Screenshots
* [x] Graphic

**Comment by groovecoder** [comment]
Another one for @fabiorios

**Comment by groovecoder** [comment]
Happening here: https://docs.google.com/document/d/1acGeN0g05Es2c0izYsHORBlGIfFb10G1AM4wX61q1G8/edit?ts=599c7f5f

**Comment by hoosteeno** [comment]
This is resolved and the content has been added to the AMO page: https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/
