### ISSUE TITLE
Container selection not shown when hovering on the "+" button to open a new tab

### ISSUE THREAD

**Issue by jessi3py** [mozilla/testpilot-containers#685]
This is happening to me since yesterday's Nightly (2017-07-17), on MacOS.
I can only open a new tab in a specific container using the Container button, but not from the "+" button.

**Comment by ArchangeGabriel** [comment]
Did you try a long press on the `+` button? I think the behaviour was changed to that (which I prefer btw) in latest release.

**Comment by groovecoder** [comment]
This is the new expected behavior. You should have seen a "NEW" notification on the Containers browser icon with a pop-up panel explaining the new UI. Was that missing?

**Comment by ArchangeGabriel** [comment]
@groovecoder Well, I had remove the container icon from my toolbar, so… But indeed, after adding it again, there was a NEW icon, and a notification. Which was unreadable (Dark theme here).

**Comment by ArchangeGabriel** [comment]
Yes, I’ve seen that. ;) But not having the icon in toolbar and/or using dark theme are currently two good reasons to have missed the notification. ;)

**Comment by groovecoder** [comment]
Good point. We'll have to consider some new or better ways to improve notification visibility. Maybe even notification API!

**Comment by jessi3py** [comment]
Oh, long pressing on "+" does show the selection. I might have missed the notification. Sorry for the noise.

(One thing I notice is that the panel flickers before the selection is shown)

**Comment by gluons** [comment]
Oh! I prefer old behavior. 🙁
