### ISSUE TITLE
Probleas con el menu de containers

### ISSUE THREAD

**Issue by serobalino** [mozilla/testpilot-containers#687]
Al pasar el cursor por el botón para agregar una pestaña no aparece el menú para elegir el tipo de pestaña, tengo que mantener presionado el botón de agregar pestaña para que aparezca el menú y elegir un tipo de pestaña.
Esto paso posterior a una actualización del mismo, lo desinstale y volví a instalar y sigue igual, Excelente complemento

**Comment by jonathanKingston** [comment]
I think this is a duplicate of #689 so going to close. Unfortunately none of the team speak Spanish so we aren't 100% certain.

Please let me know if it isn't a duplicate.

Thanks!
