### ISSUE TITLE
Signed addon release

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/testpilot-containers#693]
Hey @groovecoder,

@clouserw alerted me to the fact that we need a release before August 8th of the addon that is signed with our special key.

We could do this already and ship the 2 bugs that we patched, the assignment bug is really irritating me for tab orders anyway.

So worst case scenario we can keep working without shipping the huge SDK patch and just bump the version number.

Just wanted to file this for traceability.

**Comment by groovecoder** [comment]
Does it matter *when* before August 8th? I thought Aug 8 was just a self-imposed deadline for ourselves?

Totally agree we can sign & release without SDK removal - it should all be invisible to users anyway.

**Comment by wresuolc** [comment]
It doesn't matter when, and if you want to wait until the SDK stuff is done, that's fine too.

Aug 8th is when Nightly stops running non-webextensions that aren't signed with this pipeline.

**Comment by groovecoder** [comment]
@wresuolc - So we can just make a new 2.5.0 release and put it thru the current automated pipeline? Or we need to use the new internal signing service?

**Comment by wresuolc** [comment]
Use the current automated pipeline.  Everything is hooked up already.

**Comment by jonathanKingston** [comment]
@groovecoder as the chemical brothers once said. Push the buttonnnnnn.

**Comment by groovecoder** [comment]
@jonathanKingston and as the great Yogi Bear said - "Never on a Friday!"

**Comment by jonathanKingston** [comment]
Sorry the release schedule set out by Sting was implied, next time I'll be
more explicit @groovecoder.

(I could release on) "Monday, I could wait till Tuesday
If I make up my mind
Wednesday would be fine, Thursday's on my mind
Friday'd give me time, Saturday could wait
But Sunday'd be too late"

I'll be around Monday to firefight bugs and serenade the release process.
