### ISSUE TITLE
After turning off containers, "Open Link in New Container Tab" persists

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot-containers#697]
In https://github.com/mozilla/testpilot/issues/2686, @kballard reported:

> I turned on containers for a few minutes the other day, then turned them off. Just now I noticed that if I right click on a link, I'm still given the option "Open Link in New Container Tab", which looks like a submenu except it doesn't actually have any submenu items (hovering over it does nothing).

**Comment by groovecoder** [comment]
Are you using Nightly? The built-in Containers are still/always enabled in Nightly.

**Comment by kballard** [comment]
Yes, I'm using Nightly. If they're always enabled, where's the UI for it? The UI for containers didn't show up until I enabled the Containers Test Pilot, and it went away once I disabled it again.

**Comment by kballard** [comment]
Oh also, if containers are always enabled in nightly, then why does "Open Link in New Container Tab" not actually have any submenu items? I had one container configured before I disabled containers in Test Pilot, so if containers are always enabled I should have still had that container.

**Comment by jonathanKingston** [comment]
Maybe this got deleted in the removal process. Anyway the management of
containers in central should be on the home page of Nightly preferences
under tabs. Or about:preferences#containers to go directly.

Thanks.

**Comment by kballard** [comment]
Ah hah, you're right, it is there. And it simply had no containers.

Still, given this, I'm surprised I could "enable" it in Test Pilot, and then "disable" it again.

**Comment by jonathanKingston** [comment]
In Nightly removing the addon keeps it enabled, I'm not sure why your containers were removed though. Anyway we have migration plans to solve this and the removal will be handled by Firefox itself so I'm going to close this as https://bugzilla.mozilla.org/show_bug.cgi?id=1354602 should resolve.

Thanks for the bug. Let me know if you have further issues.
