### ISSUE TITLE
Default Containers: change "Banking" to "Finance"

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot-containers#7]
The ones we have are probably good, but I'd like to touch base our UR team to determine what these should be.

**Comment by TanviHacks** [comment]
I think we are missing "Social".  Its hard to determine whether that shoudl replace Shopping or Banking, or if Social is less important than those.  baku has some telemetry around which containers are opened at which frequency, so perhaps he can chime in.

**Comment by groovecoder** [comment]
[Nightly has the highest metric & sample count of number of times a built-in container is opened](https://telemetry.mozilla.org/new-pipeline/dist.html#!cumulative=0&end_date=2016-12-19&keys=__none__!__none__!__none__&max_channel_version=nightly%252F53&measure=CONTAINER_USED&min_channel_version=null&product=Firefox&sanitize=1&sort_keys=submissions&start_date=2016-11-14&table=0&trim=1&use_submission_date=0) ...

* 54% Personal
* 30% Work
* 6% Banking
* 10% Shopping

On [Aurora](https://telemetry.mozilla.org/new-pipeline/dist.html#!cumulative=0&end_date=2016-12-19&keys=__none__!__none__!__none__&max_channel_version=aurora%252F52&measure=CONTAINER_USED&min_channel_version=null&product=Firefox&sanitize=1&sort_keys=submissions&start_date=2016-12-02&table=0&trim=1&use_submission_date=0) and [Beta](https://telemetry.mozilla.org/new-pipeline/dist.html#!cumulative=0&end_date=2016-12-19&keys=__none__!__none__!__none__&max_channel_version=aurora%252F52&measure=CONTAINER_USED&min_channel_version=null&product=Firefox&sanitize=1&sort_keys=submissions&start_date=2016-12-02&table=0&trim=1&use_submission_date=0), Banking jumps above shopping. But on [Release](https://telemetry.mozilla.org/new-pipeline/dist.html#!cumulative=0&end_date=2016-11-04&keys=__none__!__none__!__none__&max_channel_version=release%252F50&measure=CONTAINER_USED&min_channel_version=null&product=Firefox&sanitize=1&sort_keys=submissions&start_date=2016-11-04&table=0&trim=1&use_submission_date=0) (with a very tiny sample size), Shopping jumps back above banking.

**Comment by TanviHacks** [comment]
Adding Social would be really nice.

**Comment by bakulf** [comment]
I assigne this bug to myself for the implementation of adding/renaming containers.

**Comment by pdehaan** [comment]
Ref: #131 where we discuss adding additional colors for new containers.

**Comment by TanviHacks** [comment]
Change "Banking" to "Finance"
