### ISSUE TITLE
Do not seek confirmation of deletion of a container that is empty

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/testpilot-containers#701]
With Containers Experiment 2.4.1: 

![2017-08-01 05 12 33 deletion of an empty container](https://user-images.githubusercontent.com/192271/28810364-4ba1aeb0-7681-11e7-8aef-c558b34b442e.png)

## Enhancement request

If a container either (a) is empty; or (b) comprises empty tabs, then deletion of the container should not require confirmation. 

(There's nothing to lose.)

**Comment by jonathanKingston** [comment]
Cookies still exist for this container, this is why the prompt exists.

The extension is unlikely to isolate all the cases where you might lose data so I think this is going to have to stay.
