### ISSUE TITLE
Menu is ugly and text barely readable on dark themes

### ISSUE THREAD

**Issue by vladimiroff** [mozilla/testpilot-containers#702]
I'm using a dark GTK+ theme (Breeze Dark) and the Mozilla's Compact Dark (i.e. Nightly) theme for Firefox. The menu for containers is not very well rendered and it even took me some time to realize there was the option "Always open in `<container>`".

![](http://i.imgur.com/3RNZXdM.png)

**Comment by groovecoder** [comment]
I believe this should have been fixed with yesterday's 2.4.1 release. Can you verify you're running 2.4.1?

**Comment by vladimiroff** [comment]
Oops, @groovecoder you're right. This issue is fixed in 2.4.1.
