### ISSUE TITLE
Custom contain icons and colors reset.

### ISSUE THREAD

**Issue by Uricorn** [mozilla/testpilot-containers#703]
On a few devices and two different Firefox profiles I noticed that all of my custom containers (e.g. not shopping/personal/work etc.) have changed they are now using the fingerprint icon and some of them have a different color than before.

**Comment by jonathanKingston** [comment]
@groovecoder I saw this too and a couple of other people have expressed this issue however in the latest release there wasn't anything that could cause this from what I can see.

**Comment by jonathanKingston** [comment]
So this is a bug that the `_shutdownContainers` code should have not been placed in shutdown mode from what I can see and instead only in a branch when uninstalling. The result is initial colours or icons not in the default containers set will be replaced with blue colour or fingerprint icons.

This code will still actually be run on the next update despite when we make the change from what I can see which is super annoying.

I'll create a patch for this but I don't think we should patch on it's own.
