### ISSUE TITLE
Nightly 57 issues

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/testpilot-containers#708]
I'm currently tracking through all issues that might be caused by 57 changes. This is a meta bug for those.

Known breakage upcoming:
- Indicator in the URL bar isn't the correct colour
- Square tabs break tab highlight
- 57 disables loading this extension with JPM

**Comment by jonathanKingston** [comment]
So the indicator appears to be fixed, the tab highlight is bolder on the selected tabs however I think we can live with this once my patches land for 57 native support for this highlight.

**Comment by jonathanKingston** [comment]
Some users are reporting a tab highlight issue in 57 with Test Pilot.

**Comment by franziskuskiefer** [comment]
I don't see any indicator colour on Linux in Nightly.
![image](https://user-images.githubusercontent.com/890105/28960462-1816e9d6-78ff-11e7-8c8c-6abef426e1db.png)
The left three tabs are in the personal container.

**Comment by groovecoder** [comment]
Thanks @franziskuskiefer - I think that's the "square tabs break tab highlight" bullet point that @jonathanKingston mentioned.

**Comment by jonathanKingston** [comment]
Yeah depends on the OS here I think. Hopefully my patch will land today for
this.

**Comment by tie-rack** [comment]
On macOS, I see the indicators appear for a moment on startup before disappearing:

![container-indicators](https://user-images.githubusercontent.com/3526/28990914-e6e84278-794f-11e7-8d2b-9213263dec84.gif)

Same behavior on full-size tabs, too.

**Comment by jonathanKingston** [comment]
Flagged for landing, if all goes well this should be fixed over the weekend. Please can someone test on macOS though. https://bugzilla.mozilla.org/show_bug.cgi?id=1387117
There is a follow up bug for pinned tabs not being clear either which won't land at the same time: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1387693

**Comment by tie-rack** [comment]
The indicators are back on macOS with Sunday's build:

<img width="244" alt="screen shot 2017-08-06 at 8 40 59 am" src="https://user-images.githubusercontent.com/3526/29003354-29183548-7a83-11e7-9258-c2b57f0a3055.png">

**Comment by jonathanKingston** [comment]
Hmm they shouldn't sit underneath that semi transparent 1px. Either way it
looks like it's working. I can follow up with that.
Thanks for checking back.

**Comment by lakano** [comment]
Hi !
I'm under GNU/Linux Fedora 26 with Firefox 57a1 (build of the 5th August), and all tabs have a line colored in blue on the top. The color never change, even with red/green/etc Containers and even with the default container.
Regards,
![capture d ecran de 2017-08-07 12-04-25](https://user-images.githubusercontent.com/731955/29022216-a948a6e0-7b68-11e7-9a16-a433b0134230.png)

**Comment by ArchangeGabriel** [comment]
@lakano: Not all tabs, only the current active one. This is to indicate which tab you’re on. Containers colour is still on the bottom of tabs.

**Comment by lakano** [comment]
Thanks for the precision @ArchangeGabriel , so the bug is there is no more color indicator of the container on the bottom of tabs with FF 57a1 under GNU/Linux

**Comment by ArchangeGabriel** [comment]
It works for me, with a build from the 4th. I’ll try a newer build later today, I have very limited network access currently and wouldn’t be able to download the tarball.

**Comment by lakano** [comment]
Ok, my exact version used is:

> Installed Packages
> Name         : firefox-nightly
> Version      : 57.0a1
> Release      : 0.1.20170805gite0883c8.fc26
> Arch         : x86_64
> Size         : 253 M
> Source       : firefox-nightly-57.0a1-0.1.20170805gite0883c8.fc26.src.rpm
> Repo         : @System
> From repo    : eclipseo-firefox-nightly

The last nightly builds are failed on the eclipseo copr repository, so I need to wait to upgrade, I'll inform you on next upgrade if it's solved. Just tag me in this ticket if you need I test a new version.
Regards

**Comment by jonathanKingston** [comment]
It should be on the 05 build not sure why it wouldn't however your theme is certainly different to mine. I haven't tried on my Fedora system (mostly because it's Qubes and most things look ugly).

Anyway yeah the issue is that native without this extension has an overline which was broken in Nightly. I switched this to an underline like this experiment (on mac and potentially others the experiment container highlight also can't be seen).

**Comment by ArchangeGabriel** [comment]
Just forgot to comment: I’m still having bars, but… Opening any address doesn’t load it in the assigned containers. I guess this is linked to #725.

**Comment by lakano** [comment]
@jonathanKingston My FF was upgraded to 20170812 on my Fedora and now, the color works again :)

**Comment by jfrederickson** [comment]
"Always open in this container" appears to be broken in FF 57 - the menu item is missing from the right click menu and opening a link that was previously set to always open in a given container no longer does so.

**Comment by jonathanKingston** [comment]
Closing this as it seems like we have addressed all the issues. Position of the url bar indicator will be resolved elsewhere.
