### ISSUE TITLE
Replace "No Container" copy with something else?

### ISSUE THREAD

**Issue by groovecoder** [mozilla/testpilot-containers#71]
When a user right-clicks a link and chooses "Open Link in New Container Tab >", they see a "No Container" option.

![no-container-tab](https://cloud.githubusercontent.com/assets/71928/21827932/679a7cd2-d753-11e6-96c0-57281abffad5.png)

Do we want to keep this copy?

**Comment by TanviHacks** [comment]
This happens when the user right clicks a link while in a non-default container tab.

@johngruen

**Comment by jonathanKingston** [comment]
Can we hide the "no container" and the `<hr/>` and have a "None" or "Default" container. The URL bar could reflect that too.

As a separate idea I would like "Default" to show the same doorhanger for forms as if they are http forms. The idea being trying to persuade users never to share PII (Personally identifiable information) with sites unless they pick a container.

**Comment by bakulf** [comment]
I use this feature more or less daily: I just segregate gmail. But when I open a bugzilla link, I want it in the 'default' container.

**Comment by TanviHacks** [comment]
If we can't think of the right copy, we could in the worst case add back "Open Link in New Tab"

**Comment by bakulf** [comment]
Note that the context menu (as the file->new container tab menu) now is fully created by the addon.
We can change it easily.

**Comment by groovecoder** [comment]
@johngruen ping

**Comment by pdehaan** [comment]
@jgruen says "wontfix"
