### ISSUE TITLE
Saving and restoring of sessions (multiple tabs in different containers)

### ISSUE THREAD

**Issue by robsco-git** [mozilla/testpilot-containers#712]
When I first heard about this feature/extension I though it would come in very hand for handling multiple different email accounts with one service provider (Gmail for example) without having to sign in/out to switch between accounts. This is the case and working wonderfully. Now I am wondering how to retain my tabs/containers across system and Firefox reboots. I had a look for a feature like this but I can't seem to find one directly related to containers.

One approach to aiding this would be to have support for containers in bookmarks. Store the container information along with the URL for a bookmark. 

I imagine this is something someone has already thought about but I though I'd chime in as I couldn't find anything.

**Comment by groovecoder** [comment]
Container tabs should be restored across Firefox reboots just like other tabs. Can you verify you've got session restore configured correctly?

https://support.mozilla.org/en-US/kb/restore-previous-session?redirectlocale=en-US&redirectslug=Session+Restore

**Comment by robsco-git** [comment]
Ah, I was unaware of that feature. It worked flawlessly :) Sorry for the noise.
