### ISSUE TITLE
Scroll blocked on tabs with default container

### ISSUE THREAD

**Issue by janw-oostendorp** [mozilla/testpilot-containers#720]
I open a new default tab `ctrl + t`
go to reddit.com
FF switched to my "fun" container group. Page loads.
No I can't scoll. No scrollwheel, arrow keys, space, PgUp, PgDn.
I can grap the scroll bar with the left mouse and scroll.

This happens on all containers and sites.

I am on Ubuntu with Cinnamon Desktop. Firefox 54

**Comment by groovecoder** [comment]
Which Firefox version?

**Comment by janw-oostendorp** [comment]
Currently 54
55 isn't in the updates (yet)

**Comment by janw-oostendorp** [comment]
FF55 doesn't appear to have this issue

**Comment by jonathanKingston** [comment]
Hmm this is odd, thanks for the follow up in closing this.
