### ISSUE TITLE
stop working on FF Developer Edition 56.0b2 (64-bit)

### ISSUE THREAD

**Issue by Westfallx** [mozilla/testpilot-containers#727]
Mind vid has stopped working, the menu to add videos is no longer displayed.
Windows 10 and Ubuntu 14.04
3 month ago, from test pilot
Dosent work on youtube, http://www.dailymotion.com and Similar

**Comment by groovecoder** [comment]
Did you mean to file this under the min-vid repo? https://github.com/meandavejustice/min-vid

**Comment by jonathanKingston** [comment]
Closing as it looks like it was filed on the wrong repo. Please reopen if this impacts containers.
Thanks
