### ISSUE TITLE
Question / Feature request: move an already existing tab to a container?

### ISSUE THREAD

**Issue by donlencho** [mozilla/testpilot-containers#729]
Hello,
Is this possible? Right-click on a tab, "move to container ...", something like this?
It seems like a basic feature I expected from this extension but I can't find a way to do this directly (of course I could copy the link, open a new tab in a container then copy the link, but it's not really convenient). Maybe I just couldn't find this option, or maybe it's not there and in that case I would love to see that included!
Thanks for the help,

**Comment by ArchangeGabriel** [comment]
Please use the search function/look at existing issues. ;) This has been requested many times, but they are apparently big issues with providing this feature.

**Comment by donlencho** [comment]
Alright, sorry... I'll close it then.
I can see #719 is the same problem.

**Comment by ArchangeGabriel** [comment]
Actually, this is a different topic. What you want to read is https://github.com/mozilla/testpilot-containers/wiki/Moving-between-containers.

**Comment by donlencho** [comment]
OK, sorry again then, thank you for the link, I get it now.
One thing though: I assume many people would want to use containers like this, so if it's not part of the plan, maybe it's better to say so when presenting the project. Reading the description, I expected this behaviour.
