### ISSUE TITLE
Install foundation.min.css via npm?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot-containers#73]
Currently we're bundling _some_ version of Foundation CSS framework with our code ([in the repo](https://github.com/mozilla/testpilot-containers/blob/a6bfaabb9c8f67eec24aa5b7e61ae014c9efd5e5/webextension/css/foundation.min.css)), but I'm not sure what version it is because everything is minimized, and the only comment/version I see is normalize.css v3.0.3.

Not sure if we want to try and install [**foundation-sites** via npm](http://npm.im/foundation-sites) and include the code that way, or if we're happy with including their 3rd party source code in our repo and manually maintaining it and keeping it in sync if we need a newer build.

**Comment by groovecoder** [comment]
I tend to avoid build-chains whenever possible. Aside from explicit version declaration, do we get other advantages from installing foundation via npm?
