### ISSUE TITLE
No way to assign a site to a container?

### ISSUE THREAD

**Issue by hobarrera** [mozilla/testpilot-containers#736]
As of the latest update, a bunch of features seem to have gone missing -- including assigning a site to always open on a specific container. Nor right-clicking on the site works, nor clicking on the "containers" button when a site is open on a specific container.

It also seems that previously saved sites have been forgotten; sites previously liked to a certain container now open in the "default" container.

Due to both regressions,  the addon has basically lost all it's core functionality -- I now need to open a tab manually for a given container, and *then* open a site on it, basically negating it's main functionality, which was not having to deal with that.

**Comment by groovecoder** [comment]
Are you using the latest Nightly and the latest 3.1.0 Containers release? We pushed 3.1.0 yesterday to fix these issues in Nightly.

**Comment by aproposnix** [comment]
I'm using FF56.0b3 (64-bit) and I have this issue as well.  It appears that when I disable and re-enable, the container selection icon appears (from here I can assign sites to a specific container).... but then after restarting, the container menu disappears again and I cannot assign sites to containers.

**Comment by PureTryOut** [comment]
Running Firefox 55, I have these same issues. Together with #739, the last update basically made the addons useless for me... Responses are mainly talking about Firefox Nightly, but can this be fixed in the latest stable releases as well?

**Comment by aproposnix** [comment]
In the end I have to completely wipe the profile and the sync account. Once I did this, I was able to use it again without issue.

**Comment by hobarrera** [comment]
This seems to have been fixed for me on recent updates too (on the stable channel). Thanks!
