### ISSUE TITLE
Container color does not consistently appear on tabs in FF56 with light/dark theme

### ISSUE THREAD

**Issue by nkestrel** [mozilla/testpilot-containers#737]
With the new 3.1.0 update on FF56 using light/dark theme, the container color is not always visible on all container tabs. Selected tabs show it and sometimes pinned tabs but other unselected tabs do not.

FF55 and FF57 light/dark themes do not have this problem with the same 3.1.0 update.

Edit: FF56 comparison of container appearance in different themes.
![Theme comparison](https://i.imgur.com/1IO6oeU.png)

**Comment by jonathanKingston** [comment]
Could you provide a screenshot please?

**Comment by nkestrel** [comment]
@jonathanKingston sure, updated with a screenshot comparison.

**Comment by nkestrel** [comment]
The 4.0.1 update appears to have fixed the issue.
