### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by Zlewness** [mozilla/testpilot-containers#741]
Hello, I know there are some very similar enhancement requests to this but could it be possible to add the following?

1. Exclusive containers option: For example if I have a container for "google.com" and middle click links to a few not-google results (to open in a new tab), can it let me kick the new tabs out of the google container automatically? If I click a link in the container, it should convert it back out of the google container, if I press back it should convert it back into the google container (or give a warning).

2.  Wildcards option: Is it possible to set a wildcard/negative container for any site that isn't already defined in containers? (This matches/extends issues #434 #573 ).

3. Same as above but if it matches/does not match a certain pattern (eg. "maps.google.*" or "maps.google.tld")? (This matches issue #473 #691 )

4. Temporary containers option: Is it possible to have some sort of temporary container option, sort of like how [Private Tab](https://github.com/Infocatcher/Private_Tab) works right now, when the last instance of the container is closed it deletes all history/cookies/cache for it? (Default Firefox also does this with private windows, when the last window is shut the "session" is ended)

**Comment by jonathanKingston** [comment]
1. Is covered by #503
4. is likely covered by #47 and #318 

Given there are similar bugs for all these requests is it safe to say this can be closed?

Please let me know if this isn't the case.
