### ISSUE TITLE
Latest update (unsure if firefox itself or containers) breaks containers

### ISSUE THREAD

**Issue by SiriusStarr** [mozilla/testpilot-containers#743]
After Firefox and Containers updated the other day (at the same time, so I can't say which it was), they are no longer working for me.  The Container menu is absent when I open Firefox, and "always open this site in *container*" doesn't work, though any tabs I already have open remain in their containers.  Upon toggling the addon off and back on again, the menu is back, though all preferences for what sites to open where are forgotten.  Upon exiting and reopening Firefox, however, the menu is gone once more.  Needless to say, this is really annoying to have to toggle the addon every time the browser closes (and re-set all "open with" preferences).

Edit:
Firefox 55.0.1 on Fedora
Containers 3.1.0

**Comment by elementh** [comment]
Same for me.

Firefox 57.0a1 64bits on Arch Linux
Containers 3.1.0

**Comment by Edicatad** [comment]
I am on the same setup as the OP, and for me too the containers addon has stopped working on a restart.  I just want to add, in this new version of Firefox, it seems that there is another (perhaps integrated?) container tabs option, and I suspect that this may be interfering with the function of the addon.  The functionality seems to be mostly the same save for the unavailable "always open in x" functionality, which is gone.

**Comment by boltwatts** [comment]
Same for me.

Firefox 55.0.2 (64-bit)  on Windows 10
Containers 3.1.0

**Comment by jonathanKingston** [comment]
When clicking the containers squares icon and in a container tab can you
assign to a container using the tick box there? Could you provide a
screenshot of what clicking the square icon does.
Also listing any other extensions you have would be helpful.

**Comment by SiriusStarr** [comment]
There is no containers squares icon; it disappears after every restart of Firefox.  I have attached screenshots of the region it should be, as well as my addon list.  (The problem persists with all addons disabled except test pilot/containers.)


![Addons](https://user-images.githubusercontent.com/2049163/29546482-9b33ce80-86a9-11e7-8a26-1a73eaae3381.png)
![Icon Location](https://user-images.githubusercontent.com/2049163/29546483-9b358536-86a9-11e7-872d-1eee3379e720.png)

**Comment by Edicatad** [comment]
Can confirm the same thing.  Attached is also a screenshot of the customize menu showing that I haven't just forgotten to put it on the bar.  It also shows the new container tab button that isn't added by test pilot/containers, which seems to lack the always open functionality.
![screenshot from 2017-08-22 06-09-49](https://user-images.githubusercontent.com/25881205/29548473-7274313a-8701-11e7-9795-bec74c3040f8.png)
![screenshot from 2017-08-22 06-09-26](https://user-images.githubusercontent.com/25881205/29548475-768c4c26-8701-11e7-9a1b-2ebbf7318705.png)

**Comment by jonathanKingston** [comment]
Ok that's super odd then. Long pressing on the plus button I assume still
works.
Are you able to see anything in the logs when you open the browser console
(should be Ctrl+shift+j or cmd on Mac) maybe toggle the enable/disable when
you have that open.

I really appreciate the debugging here. My only hunch is we have a fatal
exception reading the old format to restore.

Thanks.

**Comment by elementh** [comment]
![screenshot from 2017-08-22 12-17-27](https://user-images.githubusercontent.com/4228758/29560949-fdaf8150-8733-11e7-862a-ba22f5a252de.png)

This is my log. Also  the message on tespilot-containers says: 

message:"Module `./index.js` is not found at resource://testpilot-containers/index.js"

**Comment by SiriusStarr** [comment]
Yes, long press on the plus sign still works (though I actually didn't know that was a thing before now  XD).  And yes, previously configured websites to open don't work.

My log messages (pertinent to containers) are the same as @elementh 

![puush-linux 2017-08-22 at 09 48 14](https://user-images.githubusercontent.com/2049163/29577160-53d981f8-871f-11e7-9187-09bfc545f258.png)

**Comment by jonathanKingston** [comment]
@groovecoder this is the bug for testing that we spoke about that makes me nervous.

**Comment by SiriusStarr** [comment]
Same, can confirm that Firefox 55.0.2 fixed the issue for me.

**Comment by jonathanKingston** [comment]
Sounds like there was a patch to web extensions in 55.0.2 then I don't
think anything we did would fix this.
Thanks
