### ISSUE TITLE
Some icons missing in the add containers menu

### ISSUE THREAD

**Issue by collectorgeneral** [mozilla/testpilot-containers#745]
Firefox 55.0.2 x64
Platforms: Both windows and Linux

When customising the Containers, the user is allowed to choose icon shapes and colours. Some of the shapes do not show up in the add container option. See image below:

![firefox_2017-08-20_17-25-55](https://user-images.githubusercontent.com/15972594/29499656-f9944260-85ec-11e7-9562-ea52a477bf74.png)

Opening the "Manage Containers" from the new tab menu and inspecting the containers suggests that there are only 5 icons present, while the addon suggests 12. Some of them are missing and thus do not show up properly.

**Comment by jonathanKingston** [comment]
This will be fixed in 57 when this becomes release. We added more icons in
the experiment and we can't fix them in Firefox until it updates.
Thanks

**Comment by collectorgeneral** [comment]
@jonathanKingston Makes sense, thanks!

**Comment by jonathanKingston** [comment]
Going to close this as I don't think there is much we can do about this and it will fix itself.

Thanks for raising.
