### ISSUE TITLE
Move tabs to new window does not work

### ISSUE THREAD

**Issue by falolaf** [mozilla/testpilot-containers#746]
Hello,

I just got back to work after vacation and upgraded FF to 55.0.2 and it seems containers 3.1.0. This on Windows 7.

I have used the "Move tabs to new window" a lot in the past but now it seems to have stopped working as expected. I can unhide/hide container though.

If no tabs for given container is open, "Move tabs to new window" will do nothing. 

If the container is open, "Move tabs to new window" will move ONE tab to a separate window. Another "Move...." will move another tab to its own window.

Anyone else seen this?

I can also add that all tabs in all containers were gone after the upgrade.

**Comment by falolaf** [comment]
I tested with a new profile with the same result.

I thought I should try to downgrade the addon but I didn't find any signed version of 2.4.1. Any suggestions on how to downgrade?

**Comment by groovecoder** [comment]
I believe the `.xpi` file attached to the 2.4.0 release here on GitHub is signed:

https://github.com/mozilla/testpilot-containers/releases/tag/2.4.0

**Comment by falolaf** [comment]
FF did not want to install that one as it seems not to be signed.

**Comment by jiripospisil** [comment]
> If the container is open, "Move tabs to new window" will move ONE tab to a separate window. Another "Move...." will move another tab to its own window.

I'm seeing the same thing with the latest Nightly 57.0a1 (2017-08-22) (64-bit) and Containers 3.1.0.

**Comment by jonathanKingston** [comment]
> FF did not want to install that one as it seems not to be signed.

You will have to turn off signing which isn't advised for anything other than debugging.

**Comment by jonathanKingston** [comment]
> FF did not want to install that one as it seems not to be signed.

You will have to turn off signing which isn't advised for anything other than debugging.

**Comment by SoftVision-EmilPasca** [comment]
This issue is no longer reproducible on the latest Containers (3.1.0 build on 08/24/2017).

**Comment by falolaf** [comment]
I'm now on Firefox Multi-Account Containers 4.0.1. If all tabs for a container are hidden then "Move tabs to a new window" still does nothing. 

I can do "Show this container" and then "Move tabs to a new window".

FF 55.0.3
Windows 7

**Comment by falolaf** [comment]
It seems that:
tabId: list.shift().id
throws an error. shift() is not a method of list.

**Comment by jonathanKingston** [comment]
I think this used to be disabled too but let's make a new bug for it.

**Comment by falolaf** [comment]
Do you want me to open a new issue?

**Comment by jonathanKingston** [comment]
@falolaf I raised #797 thanks!
