### ISSUE TITLE
Icon spacing issue

### ISSUE THREAD

**Issue by jiripospisil** [mozilla/testpilot-containers#749]
The spacing between the icons seems wrong. There's too much space between the "Edit this bookmark" and the container's name. On the other hand there's very little space between the name and the end of the bar.

![image](https://user-images.githubusercontent.com/20820/29574817-fcaa1930-8762-11e7-933c-e9527fa1cdc8.png)

macOS 10.12.6
Nightly 57.0a1 (2017-08-22) (64-bit)
Containers 3.1.0

**Comment by jonathanKingston** [comment]
This has an issue on Bugzilla which will be resolved in [Bug 1378560](https://bugzilla.mozilla.org/show_bug.cgi?id=1378560)
