### ISSUE TITLE
Selected container tab's window doesn't get focus

### ISSUE THREAD

**Issue by jiripospisil** [mozilla/testpilot-containers#750]
Steps:

1. Create a new container tab and move it to a new window.
2. Go back to the previous window, click Containers -> View <name> container and finally the name of the tab.

Expected:

The window focus should change to the new window and the selected tab should get focus as well.

Actual:

The new window doesn't get focus. The tab itself in the new window *gets* focus (when there's multiple of them) so it seems it's just the window switching.

macOS 10.12.6
Nightly 57.0a1 (2017-08-22) (64-bit)
Containers 3.1.0

**Comment by jonathanKingston** [comment]
Sounds actually like that list isn't getting updated, I don't think it should be showing across containers.
