### ISSUE TITLE
An infinite number of each hidden container is shown when choosing "Show this container" option in Private Browsing mode

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/testpilot-containers#756]
**[Notes]:**
- On the latest Firefox Release 55.0.2 the issue is not reproducible. However, when choosing the "Show this container" option, two of the same container tabs are opened in the non-private window.

**[Affected versions]:**
- Firefox unbranded build (56.0b2-20170810113054)
- Nightly build (57.0a1-20170822171841)

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest Containers add-on version (3.1.0) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Open two or more tabs of the same container type.
3. Click on the "Containers" toolbar button.
4. Choose the "Hide this container" option for the current container type.
5. Open a New Private Window (CTRL+Shift+P).
6. Click on the "Containers" toolbar button.
7. Choose the "Show this container" option for the hidden container tabs.
8. Switch to the non-private Firefox window and observe the browser behaviour.

**[Expected result]:**
- Only one instance of each hidden container tab is shown in the non-private window.

**[Actual result]:**
- An infinite number of each hidden container tab is shown in the non-private window.

**[Additional Notes]:**
- Attached a screen recording of the issue:
![containers_issue](https://user-images.githubusercontent.com/20083658/29619104-d4723b12-8822-11e7-82f3-886380eb02ad.gif)

**Comment by jonathanKingston** [comment]
This should have never worked (we don't provide native container functionality in pb mode), I'm not sure if this bug in normal windows though. My solution is to disable the extension for pb mode.

**Comment by jonathanKingston** [comment]
This still happens even in a non pb mode window, so looking into this.

**Comment by Softvision-MariusComan** [comment]
The issue is no longer reproducible on the latest "Firefox Multi-Account Containers" build (4.0.1 from 09/07/2017). I have verified it on Windows 10 x64 and Mac 10.12, with the latest Firefox unbranded build (55.0.4) and the latest Nightly (57.0a1).
