### ISSUE TITLE
Tabs from a hidden container are not re-opened, if the hidden container is opened from long press context menu

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/testpilot-containers#765]
**Notes**
- If the hidden container is opened from "Containers" panel, the related tabs are opened as well

**[Affected versions]:**
- Firefox release 55 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the containers add-on (3.1.0) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites;
2. From the context menu add websites ( 2 or 3 ) to a specific container;
3. Click the "Containers" button under the toolbar and click ">" ( View personal container ) button choosed at step 2;
4. Click "Hide this container" button;
5. Long press the "New tab" button, and choose the hidden container(steps 2 or 3);
6. Observe the browser behaviour.

**[Expected result]:**
- All tabs from the choosed container should open.

**[Actual result]:**
- Only the new tab opens in the container.

**[Additional Notes]:**
- Attached a screen recording of the issue:
![002](https://user-images.githubusercontent.com/31243259/29717848-57dd65e8-89b9-11e7-8c39-19474ba437e4.gif)

**Comment by jonathanKingston** [comment]
This is an artifact of changing the plus button to the native solution, we will need to use tab monitoring instead.

**Comment by Softvision-MariusComan** [comment]
The issue is no longer reproducible on the latest "Firefox Multi-Account Containers" build (4.0.1 from 09/07/2017). I have verified it on Windows 10 x64 and Mac 10.12, with the latest Firefox unbranded build (55.0.4) and the latest Nightly (57.0a1).
