### ISSUE TITLE
"Always Open in This Container" option does not appear in the context menu on specific websites

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/testpilot-containers#769]
**Notes**
- If you switch to another tab and then come back, "Always Open in This Container" option appears under the right click context menu for container.

- The issue is reproducible on the following websites:
			1) https://9gag.com/
			2) https://testpilot.firefox.com/ 
			3) https://www.instagram.com/ 
			4) https://soundcloud.com/ 
There may be more websites like this, but I have not found them yet.

**[Affected versions]:**
- Firefox release 55 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the containers add-on (3.1.0) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Open a new container from the "Container" button under the toolbar.
3. Access https://9gag.com/.
4. Open the context menu.
5. Observe the context menu.

**[Expected result]:**
- "Always Open in This Container" option appear under the right click context menu for container.

**[Actual result]:**
- "Always Open in This Container" option does not appear under the right click context menu for container.

**[Additional Notes]:**
- Attached a screen recording of the issue:
![003](https://user-images.githubusercontent.com/31243259/29771811-569da732-8bfe-11e7-9dde-302c934da9bc.gif)

**Comment by jonathanKingston** [comment]
This from my testing is fixed by: #776

**Comment by Softvision-MariusComan** [comment]
The issue in no longer reproducible on the latest version of Containers 3.1.1 (built on 2017-09-04).
