### ISSUE TITLE
allow the user to choose a container for a new window

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/testpilot-containers#770]
## Actions

1. File menu

## Expected

- New window in container …
- submenu of containers

## Actual result

- nothing Window-specific for containers

## Workaround

- New Container Tab
- select the container
- (no menu bar option, as far as I can tell, for what follows)
- <kbd>Control</kbd>-Click the tab
- contextual menu
- Move to New Window

**Comment by jonathanKingston** [comment]
This seems like a dupe of: https://github.com/mozilla/testpilot-containers/issues/319
Let me know if you think otherwise, thanks.

**Comment by grahamperrin** [comment]
Maybe different. From the opening of #319: 

> … open a specific container (as its default) in a browser window … 

This issue is not about a single default. It's about multiple choices whenever a new window is opened.
