### ISSUE TITLE
about:preference tabs in containers break them

### ISSUE THREAD

**Issue by qxu21** [mozilla/testpilot-containers#773]
[This pastebin](https://pastebin.com/NB9yb0A2) contains the contents of about:support.

Reproduction steps for two bugs:

Bug 1:
1. Make a new container
2. Open about:preferences in the container's tab
3. Hide the container
4. The container cannot be shown. It's tab can be opened in a new window, and you can open new tabs in the container and use them, but the container does not want to ever be "shown."

Bug 2:
1. Make a new container
2. Open two tabs in it
3. In one tab, open about:preferences. Open any other site in the other tab.
4. Hide the container.
5. Show the container. The second tab will open repeatedly until Firefox is forcequit.

I'm happy to offer any help reproducing, or to submit these as two separate issues.

**Comment by jonathanKingston** [comment]
Unfortunately about: paths can't be opened by an extension for security reasons so we ditch opening them. The crash sounds like a bug though. We will just have to throw away that tab in history though (at least for the time being)
