### ISSUE TITLE
Container tabs can no longer be open from the "Containers" panel

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/testpilot-containers#781]
**Notes**
- The issue is reproducible for any container type (Personal, Work, Banking, Shopping) or any other custom created container type.
- The issue is not reproducible when opening a new container tab using the "+" new tab button.
- If you untick the "Enable Container Tabs" checkbox from "about:preferences" page you can no longer open a new container tab using the "+" new tab button.

**[Affected versions]:**
- Nightly build (57.0a1-20170824100243)
- Firefox Release build (55.0.3)

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the "xpinstall.signatures.required;" pref set to "false" value and "extensions.legacy.enabled;" pref set to "true" value.
- Have a Firefox profile with the latest Containers add-on version (3.1.1-dev 08/31/2017) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click on the "Containers" toolbar button.
3. Click on "Personal" to open a "Personal" tab.
4. Observe the browser behavior.

**[Expected result]:**
- The "Containers" panel is closed and a "Personal" tab is successfully opened.

**[Actual result]:**
- The "Containers" panel is closed without opening a new "Personal" tab.

**[Additional Notes]:**
- Attached a screen recording of the issue:
![container_tab_access_issue2](https://user-images.githubusercontent.com/20083658/29927713-d377c332-8e6f-11e7-8e5c-0ef4bb9077ea.gif)

**Comment by jonathanKingston** [comment]
This will depend on this: https://bugzilla.mozilla.org/show_bug.cgi?id=1395659

In 55+56 we can likely already fix this somewhat, however having an actual event will mean that we can disable the browser action which was @groovecoder's suggested solution to this.

**Comment by jonathanKingston** [comment]
Also a little odd that I am getting outcomes here, I was able to create container tabs with the extension which worries me more.

@groovecoder do we think this is a blocker to launch?

**Comment by groovecoder** [comment]
The pop-up is still used more to open container tabs than either the tab-bar or the plus button, so I think this should block launch. 😢

**Comment by groovecoder** [comment]
BTW, I was unable to create container tabs via the browserAction pop-up as soon as I installed the extension. 😢 So this seems like serious regression/breakage to me.

**Comment by jonathanKingston** [comment]
Ah I got confused yesterday. This is the but I meant should be a blocker.
I'll look at it right away.

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest Containers version (4.0.1 built on 09/06/2017).
