### ISSUE TITLE
userContext prefs are not reset when removing the add-on

### ISSUE THREAD

**Issue by groovecoder** [mozilla/testpilot-containers#782]
When a user removes the add-on, we should reset all of their `userContext` prefs to the values they had when they first installed the add-on.

**[Affected versions]:**
- Unbranded Firefox Release (55.0.1)
- Others?

**[Affected Platforms]:**
- Mac OS
- Others?

**[Prerequisites]:**
- Have a Firefox profile with the "xpinstall.signatures.required;" pref set to "false" value and "extensions.legacy.enabled;" pref set to "true" value.

**[Steps to reproduce]:**

0. Build a fresh `.xpi` from `master`
1. Open the browser with the profile from prerequisites.
2. Go to `about:config` and note the values for `privacy.usercontext.`*
3. Go to `about:addons`
4. Install the `.xpi` from master
5. Use Containers as much or as little as you like
6. Go back to `about:addons`
7. Click "Remove" on Mozilla Containers
8. Go back to `about:config`

**[Expected result]:**
- The `privacy.usercontext.`* values should be back to their original values

**[Actual result]:**
- The `privacy.usercontext.`* values are still the values from the add-on

![image](https://user-images.githubusercontent.com/71928/29934143-b600dd0a-8e3f-11e7-865a-f25ae04a02d4.png)

**Comment by groovecoder** [comment]
### During install

I see this error in browser console:
```
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIURI.hostPort]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/PopupNotifications.jsm :: PopupNotifications_refreshPanel/< :: line 806"  data: no]  (unknown)
	PopupNotifications_refreshPanel/< resource://gre/modules/PopupNotifications.jsm:806:13
	forEach self-hosted:267:13
	PopupNotifications_refreshPanel resource://gre/modules/PopupNotifications.jsm:748:5
	PopupNotifications_showPanel resource://gre/modules/PopupNotifications.jsm:929:5
	PopupNotifications_update resource://gre/modules/PopupNotifications.jsm:1097:9
	PopupNotifications_show resource://gre/modules/PopupNotifications.jsm:490:9
	showInstallConfirmation chrome://browser/content/browser-addons.js:206:17
	showNotification chrome://browser/content/browser-addons.js:417:9
	observe chrome://browser/content/browser-addons.js:433:7
	installNotifyObservers resource://gre/modules/AddonManager.jsm:2006:5
	setupPromptHandler/install.promptHandler/< resource://gre/modules/AddonManager.jsm:2878:11
	Promise resource://gre/modules/Promise-backend.js:390:5
	setupPromptHandler/install.promptHandler resource://gre/modules/AddonManager.jsm:2813:37
	checkPrompt/< resource://gre/modules/addons/XPIInstall.jsm:1756:17
	InterpretGeneratorResume self-hosted:1272:8
	next self-hosted:1179:9
	checkPrompt resource://gre/modules/addons/XPIInstall.jsm:1747:6
	install resource://gre/modules/addons/XPIInstall.jsm:1481:7
	install resource://gre/modules/addons/XPIInstall.jsm:2178:5
	install resource://gre/modules/addons/XPIInstall.jsm:2701:5
	startInstall resource://gre/modules/AddonManager.jsm:2073:5
	installAddonFromAOM resource://gre/modules/AddonManager.jsm:2178:5
	installAddonFromAOM resource://gre/modules/AddonManager.jsm:3680:5
	doCommand/</< chrome://mozapps/content/extensions/extensions.js:1469:15
	safeCall resource://gre/modules/AddonManager.jsm:195:5
	makeSafe/<
```
And console logging shows that `bootstrap.js` executes `getConfig`, but seems to fail on the `const bytes = await OS.File.read(filename());` line?


### During un-install
I see this error in browser console:
```
TypeError: parentDocShell.getDocShellEnumerator is not a function[Learn More]  tab.js:62:23
error occurred while processing 'sources: TypeError: can't access dead object
Stack: createNonSourceMappedActor@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/utils/TabSources.js:298:1
createSourceActors/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/utils/TabSources.js:382:19
process@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/Promise-backend.js:922:23
walkerLoop@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/Promise-backend.js:806:7
scheduleWalkerLoop/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/Promise-backend.js:742:11
Line: 298, column: 1  main.js:1662
	_unknownError resource://devtools/server/main.js:1662:5
	_queueResponse/responsePromise< resource://devtools/server/main.js:1680:25
	reject resource://devtools/shared/deprecated-sync-thenables.js:50:41
	then resource://devtools/shared/deprecated-sync-thenables.js:26:51
	resolve resource://devtools/shared/deprecated-sync-thenables.js:74:11
	reject resource://devtools/shared/deprecated-sync-thenables.js:51:16
	process resource://gre/modules/Promise-backend.js:925:21
	walkerLoop resource://gre/modules/Promise-backend.js:806:7
	walkerLoop self-hosted:941:17
	bound walkerLoop self-hosted:941:17
	scheduleWalkerLoop/< resource://gre/modules/Promise-backend.js:742:11
```

**Comment by jonathanKingston** [comment]
Replicated, nearly have a fix.

**Comment by jonathanKingston** [comment]
Users who didn't upgrade through sdk from what I can tell won't get a saved config, why this doesn't throw errors on fresh install or why the error is so crappy is beyond me really.

Either way, I set a new code path for worst case scenario when they remove which is at least a good interim path. I would like to look further into if we can fix the install path and saving the config etc so we reset the correct prefs however for most users there won't be any real impact. Potentially we will break some users with more than one container addon or have different prefs for nightly etc.

**Comment by jonathanKingston** [comment]
Ignore that comment. I seem to have fixed the creation and all the paths into setting this config which means uninstall should never have to use the "default" route but I suggest we leave it in just in case.

**Comment by SoftVision-EmilPasca** [comment]
I've managed to reproduce the issue on Windows 10 x64 and Mac OS 10.12 with the latest Containers(3.1.1 - 09/01/2017) on the latest Unbranded Release (55.0.1).

**Comment by Softvision-MariusComan** [comment]
The issue is no longer reproducible on the latest "Firefox Multi-Account Containers" build (4.0.1 from 09/07/2017). I have verified it on on Windows 10 x64 and Mac 10.12, with the latest Unbranded Firefox release (55.0.4).
