### ISSUE TITLE
File not found for "Open this site in your assigned container?" redirect

### ISSUE THREAD

**Issue by gibfahn** [mozilla/testpilot-containers#787]
If I add a certain page to a container then when I reopen the page from the default tab (to prompt for the "always open in the specified container" popup) then I get this `File not found`, `Problem Loading Page` error. I'd guess it's the `%20`s in the URL, if I chop off everything after the `.com` then the link works (and once I've accepted the popup everything's fine).

Sorry if this was already raised (couldn't see anything).

### Platform:

- Latest nightly
- Ubuntu 16.04

#### Original link:

https://xx-yy.zz.com/wikis/home?lang=en#!/wiki/1a-2b-3c-4d-5e/page/Foo%20BAR%20Baz%20Bat

#### Firefox redirect:

moz-extension://c2da68ab-7451-4ae6-8eb8-17321413a4ce/confirm-page.html?url=https%3A//xx-yy.zz.com/wikis/home%3Flang%3Den%23!/wiki/1a-2b-3c-4d-5e/page/Foo%2520BAR%2520Baz%2520Bat&cookieStoreId=firefox-container-2

**_EDIT:_** Forgot to mention that I changed the link text (as it's an internal link for my company). I only changed letters and numbers though, I tried to keep the special characters the same (and it still crashes with this link).

#### Result:

![image](https://user-images.githubusercontent.com/15943089/30025528-da87d366-9170-11e7-99c0-0ab82573b26f.png)

**Comment by jonathanKingston** [comment]
Looks like the ! operator. I guess they aren't valid as a get attribute and only as a fragment portion.
