### ISSUE TITLE
Collect Final Icon Assets

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot-containers#8]
Let's use this bug to track receipt of final image assets for the experiment. Based on the prototype UX we'll need the following:

- [ ] Site icon PNG files for both light and dark themes in white and `#4d4d4d` at 24px, 48px, 96px and 192px sizes
All other icons should be SVG
- [ ] container sort icon
- [ ] container unhide icon
- [ ] container hide icon
- [ ] edit pencil icon
- [ ] delete container icon
- [ ] 12-16 individual container icons

**Comment by jonathanKingston** [comment]
The container icons likely won't change unless we need more of them? (The initial 4+Circle) would be good to reuse.

**Comment by johngruen** [comment]
@jonathanKingston yeah, let's start with those, but we'll add a few more so we understand how people use them

**Comment by jonathanKingston** [comment]
@johngruen so long as my containers stickers are still valid after I am happy haha - https://twitter.com/KingstonTime/status/805155141691158528

**Comment by fangshih** [comment]
Hey~Here are the container icon assets for now. 
- container delete icon 
- container hide icon 
- container unhide icon
- edit pencil icon
- container sort icon 
- container add icon
- container site icon in PNG in 4 sizes with white and #4d4d4d
For the container site icon and sort icon, I'd like to make some small adjustment later on, but the size should be the same. 
And for the 12-16 individual container icons, still in progress. 
I'll keep upload it~ 
[Container icon Assets.zip](https://github.com/mozilla/testpilot-containers/files/660790/Container.icon.Assets.zip)

**Comment by groovecoder** [comment]
Thanks @fangshih. I'll add these to the repo today and see if I can update the popup UI to incorporate them.

**Comment by TanviHacks** [comment]
Can we close this?

**Comment by groovecoder** [comment]
Worksforme. We can open individual issues for icon updates or anything else.
