### ISSUE TITLE
Please keep the Hide/Show feature

### ISSUE THREAD

**Issue by sere** [mozilla/testpilot-containers#804]
With the last update I can't find this option anymore.

This feature is, in my opinion, the single most useful feature of these containers, even with its actual problems (tabs are loaded all at once on "Show").

I think there are several different use-cases with this feature (it provides a lightweigh and official way to save a browsing session and restore it later), and I would like to see it in the definitive addon.

**Comment by groovecoder** [comment]
You should see the "Hide" feature when you click on the container's details arrow in the pop-up?

**Comment by sere** [comment]
I had a "new" version of the containers feature which didn't let me do that (the icons and looks were the same as https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers, with only 4 icons, a different tool icon and the coloured bar above the tab as in #739).
I reinstalled the addon "Containers Experiment 2.4.0", which restored the old look and functionality, but I wonder if the "new" version will be the definitive one.

**Comment by groovecoder** [comment]
That's the core Containers feature. You should be able to install this add-on at testpilot.firefox.com or now from https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/ to get the add-on experience.

**Comment by jonathanKingston** [comment]
Closing as I think this is confusion over the filing cabinet icon which I suspect we should remove soon.

**Comment by jonathanKingston** [comment]
Please reopen if that isn't the issue
