### ISSUE TITLE
Write/run containers snippets

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/testpilot-containers#806]
We should run some containers snippets. Kirby can help.

**Comment by groovecoder** [comment]
Tagging @TanviHacks so she can follow along ...

@hoosteeno can you ping back here when we have snippet text/copy ready?

**Comment by hoosteeno** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1399272

**Comment by hoosteeno** [comment]
This thread is a good place for people who love this feature to suggest snippets. Think "tweet length advertising copy". Go!

* Tired of using Chrome to watch your 2nd email or social account? Now you can do it all in Firefox with Firefox Multi-Account Containers!
* Using private browsing mode to juggle multiple accounts? Now there's a better way. Try Firefox Multi-Account Containers?
* Juggling multiple online personalities? Firefox Multi-Account Containers was built for you. Try it now!

**Comment by groovecoder** [comment]
Those sound great to me. :)

Maybe also: "Want to keep your personal, work, and bank accounts separate? Try Firefox Multi-Account Containers!"

**Comment by TanviHacks** [comment]
We should put the snippets on FF 55 (release) and FF56 (beta), but not FF57 (nightly).  We can wait to do 57 snippets after we have resolved the AMO warning issue.

**Comment by hoosteeno** [comment]
I added these variations and specs to the bug. I asked about timing. 

https://bugzilla.mozilla.org/show_bug.cgi?id=1399272

**Comment by groovecoder** [comment]
This is done!
