### ISSUE TITLE
Uncomfortably long context menu entry text

### ISSUE THREAD

**Issue by UserNaem** [mozilla/testpilot-containers#809]
I know you want to clarify what Containers do for the "average users" to understand, but this text stretches the context menu way too hard, I really want to open the XPI and change the text myself. I think the "tutorial" that shows when running Containers for the first time is enough of an introduction, context menus don't need explanations on individual entries.

![image](https://user-images.githubusercontent.com/21028464/30373695-96f6fe4c-989b-11e7-8ae2-82a6b3cc4c50.png)
![image](https://user-images.githubusercontent.com/21028464/30373736-baa62cf0-989b-11e7-9296-c49fee872614.png)

**Comment by jonathanKingston** [comment]
@hoosteeno, @TanviHacks, @groovecoder I don't think we can do anything here other than change the extension name. We can however make the listing have Firefox and the extension not for example though.

**Comment by grahamperrin** [comment]
> use "Containers" for name for context menu

With 6.1.0 I don't see a _Containers_ context menu item for the page. 

Please, am I missing something? (I don't see anything relevant in release notes https://github.com/mozilla/multi-account-containers/releases at a glance.)
