### ISSUE TITLE
Firefox Multi-Account Containers hiding incompatibility with Containers On The Go 1.11

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/testpilot-containers#816]
A [Containers On The Go](https://addons.mozilla.org/en-us/firefox/addon/containers-on-the-go/) container is lost without warning when hidden by Firefox Multi-Account Containers.

**Comment by groovecoder** [comment]
This is a symptom duplicate of https://github.com/mozilla/testpilot-containers/issues/802. Please upvote and comment there.

**Comment by grahamperrin** [comment]
Thanks, I missed that one. Apologies for the noise.
