### ISSUE TITLE
Question: what's the difference now btw the addon and the pilot experiment?

### ISSUE THREAD

**Issue by klint** [mozilla/testpilot-containers#820]
I have installed Containers as a pilot experiment. 
What should I do now with the addon? Can I opt out from the pilot experiment itself?
Which one should I advertise to my friends and colleagues?
Thanks for clarifying... :)

**Comment by groovecoder** [comment]
Please broadcast the AMO listing page. We've kept both channels so we could smooth out AMO issues before closing off the Test Pilot channel.

In the next couple weeks, we will "graduate" Containers completely off of Test Pilot onto AMO.
