### ISSUE TITLE
Black icon on dark FF theme hardly visible

### ISSUE THREAD

**Issue by Symbai** [mozilla/testpilot-containers#832]
Hi,

I'm using:

FF 55.0.3
Container addon 4.0.1
Compact dark theme (from Mozilla)

and the addon has a black icon. When searching for this issue I came on multiple tickets where there was a white icon mentioned but all these tickets were about a nightly FF version and I haven't found a way to enable a white icon.

![grafik](https://user-images.githubusercontent.com/14368203/30591770-71c51ee4-9d44-11e7-91f4-a54d2ccc429a.png)

**Comment by jonathanKingston** [comment]
This is fixed in Firefox 57, unfortunately we can't back date the fix for this.
