### ISSUE TITLE
Tab colours stay after uninstalling

### ISSUE THREAD

**Issue by LIyoai** [mozilla/testpilot-containers#836]
After I uninstalled the addon the colours on the tabs are not removed.

Firefox Portabel 55.0.3
Addon version 4.0.1

**Comment by jonathanKingston** [comment]
This has been fixed in Firefox code, some changes made 56 and the full fixes should be in 57.
The current extension keeps the tabs if it doesn't fully disable containers, you should be able to do this in about:preferences.
