### ISSUE TITLE
Move tabs to and between containers

### ISSUE THREAD

**Issue by LIyoai** [mozilla/testpilot-containers#840]
Would be nice to move tabs to and between containers.

**Comment by groovecoder** [comment]
There are some duplicate issues for this already:

https://github.com/mozilla/testpilot-containers/issues?q=is%3Aissue+sort%3Areactions-%2B1-desc+convert+is%3Aclosed

Context Plus is another add-on that provides this functionality:

https://addons.mozilla.org/nn-no/firefox/addon/context-plus/
