### ISSUE TITLE
Implement new container creation UI

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot-containers#94]

**Comment by TanviHacks** [comment]
Needs icons, colors, etc.

**Comment by fangshih** [comment]
@TanviHacks Here are the color spec: https://www.dropbox.com/sh/jczak1kfm80q334/AAAvoNwz5lrcPZn1rreRD1E_a?dl=0
And here are the icon assets:
https://www.dropbox.com/sh/dy8fupo92slp7kd/AADWHRqfqN6sfKqJ4k22NPv-a?dl=0

Please let me know if you need anything else. Thanks!

**Comment by groovecoder** [comment]
Let's call this done and file any UI bugs as new issues.
