### ISSUE TITLE
Visual Polish for release in Test Pilot

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot-containers#95]

**Comment by kjozwiak** [comment]
I've added some screenshots of visual issues that I ran into when I initially ran through the test pilot on my macOS 10.12.2 machine.

* dropdown arrow overlaps the "New Tab" button

<img width="84" alt="arrowoverlap" src="https://cloud.githubusercontent.com/assets/2602313/22226614/26a93726-e195-11e6-9545-98afb158903e.png">

* summary text is aligned to the left.. should probably add some margin

<img width="280" alt="removecontainer" src="https://cloud.githubusercontent.com/assets/2602313/22226721/809a1e30-e195-11e6-9c9c-83eb73b072c2.png">

* the ui under the tab bar for custom containers appears broken.. Possibly related to #96 

<img width="280" alt="customcontainer" src="https://cloud.githubusercontent.com/assets/2602313/22226873/543392f8-e196-11e6-9a00-a315192d7b57.png">

* new tab button overlaps custom container tabs

<img width="241" alt="customcontaineroveralp" src="https://cloud.githubusercontent.com/assets/2602313/22226941/a13c860e-e196-11e6-8543-2b75d762e144.png">

* the list of currently opened tabs for a specific container is really hard to read

<img width="276" alt="currentopened" src="https://cloud.githubusercontent.com/assets/2602313/22227012/f4e203d8-e196-11e6-92ab-e6b79901467d.png">
