### ISSUE TITLE
Focused Container Tab on MacOS looks wrong

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot-containers#96]

**Comment by kjozwiak** [comment]
Adding screenshots... This is also happening on the Win platform but isn't as visible as macOS..

macOS example:

<img width="256" alt="macos" src="https://cloud.githubusercontent.com/assets/2602313/22342637/11c0d0f0-e3c3-11e6-9678-ab9b9f5115eb.png">

Win example:

![win](https://cloud.githubusercontent.com/assets/2602313/22342677/2da966b0-e3c3-11e6-8e20-1dd90c0a4b6e.PNG)

With the above Win screenshot, you can see the same focus issue but it's a lot more subtle, which makes it harder to see... On a really good monitor, you'll be able to notice it a lot easier... With the currently broken UI, you can see the square on focused tabs a lot easier which demonstrates the issue really well.

<img width="261" alt="winui" src="https://cloud.githubusercontent.com/assets/2602313/22342765/814032a4-e3c3-11e6-9ee2-0a2c857010ee.png">

**Comment by jonathanKingston** [comment]
This depends on edits that @johngruen has been working on.

**Comment by kjozwiak** [comment]
You'll get a similar UI issue when you move container tabs into their own windows on all the platforms.

**Ubuntu 16.04.1 LTS x64:**

<img width="698" alt="screen shot 2017-02-13 at 8 38 21 pm" src="https://cloud.githubusercontent.com/assets/2602313/22911251/b147c0ee-f22c-11e6-93fd-8d95b8697056.png">

**_Windows 10 Pro x64:_**

![windowsissue](https://cloud.githubusercontent.com/assets/2602313/22911300/eed350d6-f22c-11e6-9f2b-c8a3f8da7389.PNG)

**_macOS 10.12.3 x64:_**

<img width="360" alt="osx" src="https://cloud.githubusercontent.com/assets/2602313/22911402/8b53e826-f22d-11e6-9334-e6a68176efb6.png">

**Comment by TanviHacks** [comment]
John fixed.
