### ISSUE TITLE
Make sure experiment is E10S compatable

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot-containers#97]

**Comment by TanviHacks** [comment]
So far, Peter and Kamil haven't found any issues.

**Comment by kjozwiak** [comment]
Just a quick heads up, enabling e10s via `browser.tabs.remote.autostart;true` doesn't work. Once you restart the browser, you'll get `Multiprocess Windows: 0/1 (Disabled by add-ons)` under about:support.

* Services.appinfo.browserTabsRemoteAutostart -> false under the browser console

You'll need to create `browser.tabs.remote.force-enable;true` by running  the standalone fx executable without jpm . Once you've created the pref, launch fx via the jpm and you'll get `Multiprocess Windows: 1/1 (Enabled by user)` in about:support.

* Services.appinfo.browserTabsRemoteAutostart -> true under the browser console

**Comment by bakulf** [comment]
With this patch, the addon doesn't block e10s in nightly.

**Comment by TanviHacks** [comment]
So far so good.

**Comment by kjozwiak** [comment]
@bakulf, it looks like you still need to use `browser.tabs.remote.force-enable;true` to get e10s enabled with the test pilot... This affects both fx51 and fx52...

I'm pretty sure it's due to the "devpref" add-on that needs to be installed alongside the test pilot.. I can enable e10s on a standalone version of fx and enable e10s without any issues, but whenever I install "devpref" and restart the browser, about:support displays `Multiprocess Windows: 0/1 (Disabled by add-ons)`.

**Comment by bakulf** [comment]
@kjozwiak I see this behavior, can you confirm?

- beta unbranded (51) without addon:  Multiprocess Windows 	0/1 (Disabled)
- beta unbranded (51) with addon:  Multiprocess Windows 	0/1 (Disabled)
- aurora (52) without addon: Multiprocess Windows 	1/1 (Enabled by default)
- aurora (52) with addon: Multiprocess Windows 	1/1 (Enabled by default)

I don't have devpref installed. These results are taken executing jpm run -b </path/of/firefox>

**Comment by kjozwiak** [comment]
@bakulf, it looks like things are working as expected when it comes to enabling e10s.. With fx51.0.1 [1] and fx52.0b5 [2], it seems like e10s is eventually enabled automatically. I'm assuming this has something to do with automatically opting users into e10s that meet certain requirements.

Sometimes it takes a few minutes for e10s to enable automatically on those builds, so simply enabling e10s when the container add-on is installed via `browser.tabs.remote.autostart;true` works without any issues.

I think the issues I was having earlier was when I was using the devpref add-on installed.

[1] fx51.0.1, buildid: 20170125094131, changeset: 327e081221b0
[2] fx52.0b5, buildid: 20170209120619, changeset: 49b3ad9f467d

**Comment by kjozwiak** [comment]
I went through a bunch of test cases and ensured that:

- e10s stays enabled when installing/uninstalling containers if it's already enabled
- e10s stays disabled when installing/uninstalling containers if it's already disabled

I'm going to close this off as we discussed in IRC... If there's any issues related to e10s, we'll create a new bug.

**Platforms Used:**

macOS 10.12.3 x64 - PASSED
Windows 10 x64 - PASSED
Ubuntu 16.04.1 LTS x64 - PASSED

**Builds Used:**

fx51.0.1, buildid: 20170125094131, changeset: 327e081221b0
fx52.0b6, buildid: 20170213070939, changeset: 7b8aa893944b
