### ISSUE TITLE
What survey question do we want to ask users?

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot-containers#99]
We should ask users what they think it means to hide a container. Are tabs closed or suspended. We should ask users who have hidden containers how long they've hidden them for.

**Comment by groovecoder** [comment]
I think we're able to **measure** how long containers hide wih Telemetry. Roughly maybe:

When user clicks to hide a container, send a Telemetry payload:
```
{
  "containerUUID": <generated-uuid-value>,
  "hiddenTimestamp": <current-datetime>
}
```
When a user clicks to show a container, send a Telemetry payload:
```
{
  "containerUUID": <the-same-generated-uuid-value>,
  "shownTimestamp": <current-datetime>
}
```
In Telemetry Redash SQL:
```
SELECT (shownTimestamp - hiddenTimestamp) as hiddenDuration WHERE containerUUID = containerUUID
```

**Comment by bakulf** [comment]
Right. I'm curios to know:

1. do they use this feature?
2. how many times
3. how long.
4. do they hide more than 1 container at the same time?
5. how many times are they hiding per container?
6. they hide containers... but do they restore them?

So I guess we just to need to add: "tabCount" in the telemetry payload.

**Comment by groovecoder** [comment]
@johngruen - if you think we can measure this instead of using a survey, should we close this issue and just add this hide metric to #113?

**Comment by jonathanKingston** [comment]
- When opening tabs what should we default the new container to? (search, clicking links and ctrl+t etc)
- Should we show a modal when clicking a site you know about to pick a container to 'jump' into?

**Comment by TanviHacks** [comment]
> Should we show a modal when clicking a site you know about to pick a container to 'jump' into?

What do you mean?

**Comment by johngruen** [comment]
@groovecoder @bakulf @TanviHacks I will be communicating extra questions to be put in the survey to the S&I Team today. Last call!

**Comment by TanviHacks** [comment]
Do you have a doc with the list of questions you have drafted?

**Comment by TanviHacks** [comment]
What do they find most useful about this feature?

(Then we can see - do they use it to login to multiple accounts, for privacy reasons, for organization, etc)

**Comment by johngruen** [comment]
Passed questions along to @rayborn. Closing.
